### ISSUE TITLE
Viivakoodin generointi niteelle - ksdev/ks-0005-bug-30328-gen-barcode

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#1]
### Siirrettävä ominaisuus

Kohassa on niteen viivakoodigenerointi, johon lisätty Koha-Suomessa prefix-vaihtoehto.

Liittyvät järjestelmäasetukset:

autoBarcode
Tänne lisätty vaihtoehto <prefix>yyyymm0001

BarcodePrefix
asetuksella voi määrittää esim., että tietyn kirjaston viivakoodeihin tulee tietynlainen prefiksi, esim. kuntakoodi.

**Comment by emta001** [comment]
Tehdään tästä uusi versio tiketin [KS22-772](https://github.com/KohaSuomi/Koha/issues/772) mukaan, eli käytetään timestampia juoksevana arvona

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 20.11.2023: Siirretään

**Comment by emta001** [comment]
> Tehdään tästä uusi versio tiketin [KS22-772](https://github.com/KohaSuomi/Koha/issues/772) mukaan, eli käytetään timestampia juoksevana arvona

Hieman tästä suunnitelmasta poiketen, toin muutoksen jo nexteille. Muuten ei niteiden luominen onnistu (ellei vaihtele autoBarcode-asetusta).

**Comment by Kati-Helle** [comment]
Helle-nextillä toimii oikein. 
Esimerkiksi Loviisan pääkirjaston niteelle muodostui niteen viivakoodi 
![Image](https://github.com/KohaSuomi/Koha-23x/assets/99952449/ad388771-fb0e-4c08-87e5-617e467eafb4)

**Comment by MikkoLiimatainen** [comment]
Vaski-nextilläkin toimii oikein.

**Comment by ElinaUotila** [comment]
Kirkes-nextilläkin toimii oikein.

**Comment by emta001** [comment]
Kolme testin perusteella todettu toimivaksi. Suljen tiketin.
