### ISSUE TITLE
Kohan itsepalvelun palautus-toiminto - ksdev/ks-0020-bug-22322

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#10]
### Siirrettävä ominaisuus

Koha-Suomelle lisätty toiminnallisuus, jolla lainat voidaan palauttaa itsepalvelulainauksen kautta ilman kirjautumista.

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 20.11.2023: Siirretään

**Comment by AnneliO** [comment]
Kun menen osoitteeseen https://outi-next.koha-suomi.fi/cgi-bin/koha/sco/sco-main.pl avautuu tämän näköinen sivu:

![Image](https://github.com/KohaSuomi/Koha-23x/assets/33121325/75632c9b-956c-4062-9d16-901e95202fcd)


Pitäisi avautua tämän näköinen sivu:

![Image](https://github.com/KohaSuomi/Koha-23x/assets/33121325/08b700d9-5b8e-446c-abd6-53887edd37f1)

**Comment by ghost** [comment]
Korjattu.

**Comment by AnneliO** [comment]
Jos menen https://outi-next.koha-suomi.fi/cgi-bin/koha/sco/sco-main.pl -osoitteeseen niin, että olen kirjautuneena toisella välilehdellä superlibrarian-tunnuksella niin näkymä on tällainen vääränlainen:

Ilman SCOUserCSS-määrityksiä:
![Image](https://github.com/KohaSuomi/Koha-23x/assets/33121325/0e4b19c3-920c-42bc-92d4-d94f1c0e6b72)


SCOUserCSS-määritysten kanssa:
![Image](https://github.com/KohaSuomi/Koha-23x/assets/33121325/be1b1650-045e-43ac-9e42-6b0ba5f4d59c)

Mutta jos menen sivulle niin, että en ole kirjautuneena, tulee edelleen vääränlainen kirjautumisnäkymä:

![Image](https://github.com/KohaSuomi/Koha-23x/assets/33121325/5eb93847-df7e-4228-9835-7af4428350b6)

**Comment by AnneliO** [comment]
Näkymä on siis vähän korjaantunut, mutta ei ole oikeanlainen edelleenkään.

**Comment by ghost** [comment]
Taitaa liittyä CSS:iin, omassa testiympäristössäni kirjautumissivu näyttää oikealta.

**Comment by AnneliO** [comment]
Poistin CSS:t käytöstä testatessa (keskimmäinen kuva), joten voineeko niistä johtua?

Vai tarkoitatko jotain muita CSS:iä kuin SCOUserCSS-järjestelmäasetusta?

**Comment by ghost** [comment]
SCSS:istä generoitavia CSS:iä tarkoitin. Outoa kyllä kun noihin SCSS:iin ei tässä branchissa ole tehty mitään muutoksia.

**Comment by ghost** [comment]
OPAC:in CSS:t puuttuivat kokonaan, nyt ovat paikallaan.

**Comment by AnneliO** [comment]
Jes, nyt näyttää oikealta. Kiitos!

Miepä testailen lisää.

**Comment by pirliis** [comment]
Testasin myös OUTIn itsepalvelutoimintoa. Toimi muuten kuin tuotannossakin, mutta kaksi huomiota:

1. Saisiko Lainat- ja Varaukset-välilehdeltä piiloon nämä toiminnot:
![image](https://github.com/KohaSuomi/Koha-23x/assets/98814860/7b05acdb-beed-4c76-81f0-cbbe906e1baf)

2. Varaukset-välilehdellä vain keskeytetylle varaukselle tulee "Muuta-toiminto, jolla voisi muuttaa varauksen noutopaikan. Jos toiminnossa sallitaan noutopaikkamuutokset, noutopaikkamuutos pitäisi pystyä tekemään myös voimassa olevalle varaukselle, joka ei ole vielä jäänyt kiinni. 
Jos yrittää muuttaa keskeytetyn varauksen noutopaikan, tule virheilmoitus:
![image](https://github.com/KohaSuomi/Koha-23x/assets/98814860/c0486280-8051-45cb-9763-c9354115fd01)

Myös tuotannossa on näin, että vain keskeytetylle varaukselle tulee "Muuta"-toiminto ja tulee sama virheilmoitus, jos noutopaikkaa yrittää muuttaa.

**Comment by AnneliO** [comment]
> Testasin myös OUTIn itsepalvelutoimintoa. Toimi muuten kuin tuotannossakin, mutta kaksi huomiota:
> 
>     1. Saisiko Lainat- ja Varaukset-välilehdeltä piiloon nämä toiminnot:
>        ![image](https://private-user-images.githubusercontent.com/98814860/325561843-7b05acdb-beed-4c76-81f0-cbbe906e1baf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNDA4NTQsIm5iZiI6MTcxNDA0MDU1NCwicGF0aCI6Ii85ODgxNDg2MC8zMjU1NjE4NDMtN2IwNWFjZGItYmVlZC00Yzc2LTgxZjAtY2JiZTkwNmUxYmFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDEwMjIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiYmUzZDEwMWVjZmRiZTJiNDRlNzdmZDYxMzk5NGU0ZGNhMzlmNDBhMjZjZDNmMTU0OTdjMzRjMjY3ZmUzYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZXX578eezxMFubB2uHb0I-Lm9v6Gp2RUAupXyC6CNxo)
> 

Tutkitaan. :)

>     2. Varaukset-välilehdellä vain keskeytetylle varaukselle tulee "Muuta-toiminto, jolla voisi muuttaa varauksen noutopaikan. Jos toiminnossa sallitaan noutopaikkamuutokset, noutopaikkamuutos pitäisi pystyä tekemään myös voimassa olevalle varaukselle, joka ei ole vielä jäänyt kiinni.
>        Jos yrittää muuttaa keskeytetyn varauksen noutopaikan, tule virheilmoitus:
>        ![image](https://private-user-images.githubusercontent.com/98814860/325560617-c0486280-8051-45cb-9763-c9354115fd01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNDA4NTQsIm5iZiI6MTcxNDA0MDU1NCwicGF0aCI6Ii85ODgxNDg2MC8zMjU1NjA2MTctYzA0ODYyODAtODA1MS00NWNiLTk3NjMtYzkzNTQxMTVmZDAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDEwMjIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwMTQ5N2FhNzdjMTg2MWQyOTRhMmNmMGQ0ZDdiNDk3NWRjMzQxMWYwMTNiNTgxZTQxNjU5OGIyMzFmZDk3ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.koKBO88krppn18rAfX_a_ZsyxXaPxfPmVJGS4ZhaZ2k)
> 
> 
> Myös tuotannossa on näin, että vain keskeytetylle varaukselle tulee "Muuta"-toiminto ja tulee sama virheilmoitus, jos noutopaikkaa yrittää muuttaa.

Kun Muuta-nappia painaa ja valitsee uuden noutopaikan, ja klikkaa Tallenna/Save, niin ohjelma siirtyy osoitteeseen

https://outi-next.koha-suomi.fi/cgi-bin/koha/opac-modrequest.pl

Tuota osoitetta ei varmaan ole avattu opacin puolelta "sallituksi".

**Comment by AnneliO** [comment]
outi-nextillä SCOUserCSS-asetuksessa on nyt tällainen rimpsu, joka ainakin minun testien mukaan piilottaisi nuo napit.

```
/* Piilota Kopioi-, Tulosta- ja CSV-napit */

body#sco_main.sco button.dt-button.buttons-copy.buttons-html5, button.dt-button.buttons-csv.buttons-html5, button.dt-button.buttons-print { display: none; }
```

**Comment by pirliis** [comment]
> outi-nextillä SCOUserCSS-asetuksessa on nyt tällainen rimpsu, joka ainakin minun testien mukaan piilottaisi nuo napit.
> 
> ```
> /* Piilota Kopioi-, Tulosta- ja CSV-napit */
> 
> body#sco_main.sco button.dt-button.buttons-copy.buttons-html5, button.dt-button.buttons-csv.buttons-html5, button.dt-button.buttons-print { display: none; }
> ```

Kiitos Anneli! Toiminnot eivät näy enää kummallakaan välilehdellä. :)

**Comment by pirliis** [comment]
> > Testasin myös OUTIn itsepalvelutoimintoa. Toimi muuten kuin tuotannossakin, mutta kaksi huomiota:
> > ```
> > 1. Saisiko Lainat- ja Varaukset-välilehdeltä piiloon nämä toiminnot:
> >    ![image](https://private-user-images.githubusercontent.com/98814860/325561843-7b05acdb-beed-4c76-81f0-cbbe906e1baf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNDA4NTQsIm5iZiI6MTcxNDA0MDU1NCwicGF0aCI6Ii85ODgxNDg2MC8zMjU1NjE4NDMtN2IwNWFjZGItYmVlZC00Yzc2LTgxZjAtY2JiZTkwNmUxYmFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDEwMjIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiYmUzZDEwMWVjZmRiZTJiNDRlNzdmZDYxMzk5NGU0ZGNhMzlmNDBhMjZjZDNmMTU0OTdjMzRjMjY3ZmUzYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZXX578eezxMFubB2uHb0I-Lm9v6Gp2RUAupXyC6CNxo)
> > ```
> 
> Tutkitaan. :)
> 
> > ```
> > 2. Varaukset-välilehdellä vain keskeytetylle varaukselle tulee "Muuta-toiminto, jolla voisi muuttaa varauksen noutopaikan. Jos toiminnossa sallitaan noutopaikkamuutokset, noutopaikkamuutos pitäisi pystyä tekemään myös voimassa olevalle varaukselle, joka ei ole vielä jäänyt kiinni.
> >    Jos yrittää muuttaa keskeytetyn varauksen noutopaikan, tule virheilmoitus:
> >    ![image](https://private-user-images.githubusercontent.com/98814860/325560617-c0486280-8051-45cb-9763-c9354115fd01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNDA4NTQsIm5iZiI6MTcxNDA0MDU1NCwicGF0aCI6Ii85ODgxNDg2MC8zMjU1NjA2MTctYzA0ODYyODAtODA1MS00NWNiLTk3NjMtYzkzNTQxMTVmZDAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDEwMjIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwMTQ5N2FhNzdjMTg2MWQyOTRhMmNmMGQ0ZDdiNDk3NWRjMzQxMWYwMTNiNTgxZTQxNjU5OGIyMzFmZDk3ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.koKBO88krppn18rAfX_a_ZsyxXaPxfPmVJGS4ZhaZ2k)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Myös tuotannossa on näin, että vain keskeytetylle varaukselle tulee "Muuta"-toiminto ja tulee sama virheilmoitus, jos noutopaikkaa yrittää muuttaa.
> 
> Kun Muuta-nappia painaa ja valitsee uuden noutopaikan, ja klikkaa Tallenna/Save, niin ohjelma siirtyy osoitteeseen
> 
> https://outi-next.koha-suomi.fi/cgi-bin/koha/opac-modrequest.pl
> 
> Tuota osoitetta ei varmaan ole avattu opacin puolelta "sallituksi".

Olisiko helpointa, että Muuta-linkki otetaan pois näkyviltä myös keskeytetyiltä varauksilta?

**Comment by AnneliO** [comment]
> Olisiko helpointa, että Muuta-linkki otetaan pois näkyviltä myös keskeytetyiltä varauksilta?

Jos toimintoa ei tarvita, niin todennäköisesti olisi. Miepä tutkin, saako sen piiloon.

**Comment by AnneliO** [comment]
> > Olisiko helpointa, että Muuta-linkki otetaan pois näkyviltä myös keskeytetyiltä varauksilta?
> 
> Jos toimintoa ei tarvita, niin todennäköisesti olisi. Miepä tutkin, saako sen piiloon.

Tämän saa itse asiassa OPACAllowUserToChangeBranch -järjestelmäasetuksella piiloon ottamalla rastin pois Keskeytetyt-kohdasta. Olemme edellisen versionvaihdon aikaan testanneet, että tuo asetus ei vaikuta Finnaan, joten sen voi ottaa pois.

**Comment by pirliis** [comment]
> > > Olisiko helpointa, että Muuta-linkki otetaan pois näkyviltä myös keskeytetyiltä varauksilta?
> > 
> > 
> > Jos toimintoa ei tarvita, niin todennäköisesti olisi. Miepä tutkin, saako sen piiloon.
> 
> Tämän saa itse asiassa OPACAllowUserToChangeBranch -järjestelmäasetuksella piiloon ottamalla rastin pois Keskeytetyt-kohdasta. Olemme edellisen versionvaihdon aikaan testanneet, että tuo asetus ei vaikuta Finnaan, joten sen voi ottaa pois.

Piilotettu OUTIn tuotannosta ja nextiltä.

**Comment by AnneliO** [comment]
Toimii, suljetaan.
