### ISSUE TITLE
Laina- ja maksusäännön varaus sarakkeita ei pysty tallentamaan tai muokkamaan

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-23x#101]
### Mikä vikana?

Yhteisön muutos [8367](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=8367) on rikkonut laina- ja maksusääntöjen lisäyksen/muokkauksen. Sarakkeet "Varauksia sallittu (yhteensä)", "Varauksia sallittu (päivittäin)" ja "Varauksia tietuetta kohti (määrä)" eivät tallennu kantaan ja niissä näkyy taulukossa arvona "Unlimited". Tiketissä 8367 on vahingossa tiputettu koodista noiden sarakkeiden muuttujat, joten niiden arvoja ei koskaan lähetetä tietokantaan asti.

**Comment by AnneliO** [comment]
Korjattu yhteisöversiossa.

**Comment by pknuuti** [comment]
Testasin Vaaran nextillä muuttamalla yhtä laina- ja maksusääntöä varausten määrän osalta. Varausten määrä 1 ei muuttunut, vaikka tallensin siihen arvoksi 2. Taulukossa edelleen näkyy 1 varaus sallittu. Lainamäärän muuttaminen onnistuu ihan hyvin, mutta sallittujen varausten määrä ei muutu tallennuksesta huolimatta.

**Comment by Kati-Helle** [comment]
Helle-nextilläkään ei tallennu Laina- ja maksusääntöjen Varauksia sallittu (yhteensä) -arvoon tehty muutos, vaan  alkuperäinen arvo jää edelleen voimaan.

**Comment by pknuuti** [comment]
Milloin saadaan korjaus nexteille?

**Comment by AnneliO** [comment]
Pistin tiketin vielä Odottaa-tilaan, koska yhteisön korjaus pitänee ensin tuoda.

**Comment by emta001** [comment]
Tämän korjauksen olisi pitänyt tulla nolla-branchin mukana nexteille. Ainakin koodi on paikallaan siellä. Testaatteko uudestaan.

**Comment by pknuuti** [comment]
Ei Vaaran nextillä toimi vieläkään tuo varausten määrän muuttaminen. Tallennus ei pysy.

**Comment by Kati-Helle** [comment]
Hellen nextilläkään varausmäärän muuttaminen ei tallennu.

**Comment by emta001** [comment]
Noniiih... muutos on kyllä 0-branchissa, mutta se ei vaan ole nexteillä :sweat_smile: Muistelin kovasti, että se olis ollut siellä. Elikäs, joko tuodaan se tai sitten tuon tän muutoksen erikseen omassa branchissaan.

**Comment by emta001** [comment]
0-branch on viety testeille.

**Comment by Kati-Helle** [comment]
Helle-nextissä muutokset tallentuivat.

Arvot ennen muutosta
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/0def4a0b-0dc4-4408-9dec-8ace43499847)

Arvot muutoksen tallennuksen jälkeen
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/1a6d538d-fa36-424b-865c-3989dbcb6852)

**Comment by pknuuti** [comment]
Onnistuu nyt Vaaran nextilläkin.

**Comment by ajrajala** [comment]
Myös Vaski-nextille testattu, että muutokset tallentuvat.

**Comment by emta001** [comment]
Siispä tää toimii. Suljen tiketin.
