### ISSUE TITLE
Elasticsearch record -linkistä tulee Error 404 tietueen perustiedot-näytöllä

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#102]
### Mikä vikana?

Tietueen perustiedot-näytöllä on uusi toiminto Elasticsearch record, jota painamalla pitäisi saada näkyville tietueen tiedot indeksissä.
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/33121325/bd77370d-68f7-42f0-bfcb-bc9e30b67eaa)

Jos sitä klikkaa, tulee Virhe 404

![kuva](https://github.com/KohaSuomi/Koha-23x/assets/33121325/8db68c2d-de6c-43e8-9102-d600871be805)

**Comment by emta001** [comment]
Tämmöstä tuuttas plack-intranet-error.logille

`[2024/01/04 14:18:25] [WARN] [Request] ** [http://localhost:9200]-[400] no handler found for uri [/outi-next_biblios/data/1] and method [GET], called from sub Search::Elasticsearch::Role::Client::Direct::__ANON__ at /home/koha/Koha/catalogue/showelastic.pl line 61. With vars: {'status_code' => 400,'request' => {'qs' => {},'body' => undef,'path' => '/outi-next_biblios/data/1','method' => 'GET','serialize' => 'std','ignore' => []},'body' => {'error' => 'no handler found for uri [/outi-next_biblios/data/1] and method [GET]'}}`

**Comment by emta001** [comment]
Ilmeisesti tämän ominaisuuden käyttämä urli ei ole yhteensopiva Elasticsearchin 8 version kanssa, joka tulee käyttöön seuraavassa versiossa. Yhteissö korjaus tehty tiketissä [35618](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=35618).

**Comment by emta001** [comment]
Korjaus viety nexteille, odottaa vielä buildia.

**Comment by pknuuti** [comment]
Vaaran nextillä testattu: Elasticsearch tietue: 'Näytä' avaa ikkunan, joka näyttää Elasticiin indeksoidut tiedot.
![Image](https://github.com/KohaSuomi/Koha-23x/assets/73887264/ba350285-d68f-4005-833d-741fcfad1946)

**Comment by Kati-Helle** [comment]
Helle-nextilläkin linkki toimii.

**Comment by AnneliO** [comment]
Kiitos testeistä, suljen tiketin, koska homma toimii nyt. :)
