### ISSUE TITLE
Asiakashaussa tulee Internal server error

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#103]
### Mikä vikana?

Asiakashaussa jos klikkaa vaikkapa A-kirjainta sukunimen mukaan selatessa, tulee **Internal server error** ja teksti *Properties not allowed: password*

![kuva](https://github.com/KohaSuomi/Koha-23x/assets/33121325/e794a77f-5a5c-452a-a236-cb92510ee1e1)

Konsoliin tulee https://outi-next.koha-suomi.fi/api/v1/patrons?-alkuisesta api-kutsusta herja.

**Comment by emta001** [comment]
Enpä nyt saa toistettua tätä omassa ympäristössäni. Ja jännä, kun tuon api-kutsun tekee sellaisenaan selaimessa, ei tule mitään herjaa.

**Comment by emta001** [comment]
Tämä korjaantui, kun skeema rakennettiin Vaskin eikä OUTIn kautta. Nykyinen outi-nextin kanta on siivoamaton, siellä oli varmaan jotain mikä rikkoi haun.

**Comment by AnneliO** [comment]
Kiitos, toimii!
