### ISSUE TITLE
UpdateNotForLoanStatusOnCheckin: ONLYMESSAGE-tyyppiset nidetilat tippuvat palautuksessa

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#104]
### Mikä vikana?

Kun palauttaa notforloan-tilaisen niteen, joka on määritetty UpdateNotForLoanStatusOnCheckin-järjestelmäasetuksessa määritteellä ONLYMESSAGE, tippuu notforloan-arvo niteeltä palautettaessa, vaikka ei pitäisi.

### Mitä pitäisi tapahtua

Niteellä pitäisi säilyä notforloan-tila ja palautuksessa pitäisi vain näkyä notforloan-tilan selite.

### Kuinka toistaa ongelma/asia

1. Lisää niteelle esim. Laskutettu-tila (arvo 6).
2. Palauta nide, jolloin saat ilmoituksen, jossa näkyy notforloan-tilan selite (Laskutettu...).
3. Mene teoksen tietoihin ja tarkista, onko niteellä edelleen Laskutettu-tila.

### Jotain muuta?

Yhteisössä on tähän signed off -tilassa korjaus: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=35293.

Korjaus on otettava mukaan, koska muuten laskutettujen aineistojen käsittely ei toimi oikein.

**Comment by emta001** [comment]
Korjaus viety nexteille, odottaa buildia.

**Comment by AnneliO** [comment]
Yhteisössä tiketti pushed to 24.05.

**Comment by AnneliO** [comment]
Pushed to 23.11.x for 23.11.02

**Comment by Kati-Helle** [comment]
Helle-Nextillä 
lisäsin niteelle 638N053614512 (itemnumber 1609987) Ei lainata -nidetilan Laskutettu
![Image](https://github.com/KohaSuomi/Koha-23x/assets/99952449/de3cbb4a-6bd2-4e45-8304-8a82af71f884)

Palautin niteen
![Image](https://github.com/KohaSuomi/Koha-23x/assets/99952449/346cd1e3-a69b-4859-8009-99713fb656b8)

Tietueen Perustiedot-näytöllä nide palautuksen jälkeen: Laskutettu-nidetila on niteellä edelleen 
![Image](https://github.com/KohaSuomi/Koha-23x/assets/99952449/f369d4ee-a7ea-4cdb-980f-da65d1b9d9c5)

**Comment by ajrajala** [comment]
Vaski-nextillä not for loan -tilat poistuvat asetuksen määritysten mukaisesti.

**Comment by AnneliO** [comment]
Testasin outi-nextillä ja ONLYMESSAGE-määrityksellä olevat tilat säilyivät palautettaessa. Muutenkin tilat käyttäytyivät palautuksessa kuten määritetty eli poistuivat tai säilyvät oikein.

Suljen tiketin.
