### ISSUE TITLE
OAI/Apache

### ISSUE THREAD

**Issue by CodoDerDritte** [KohaSuomi/Koha-23x#105]
### Mikä vikana?

Normaalisti OAI näkyy maailmalle OPAC:in kautta, mutta meillä se tarjoillaan ulos kunkin Kohan SC-osoitteesta, kuitenkin ilman asiakasvarmennevaatimusta. Tällä hetkellä tämä vaatii oai.pl:n linkkaamisen OPAC:in alta SC:n alle, muuten tuloksena on 404.

### Mitä pitäisi tapahtua

Muutetaan versiopäivityksessä Apachen konfiguraatiota niin että oai.pl linkkiä ei enää tarvita.

### Asiasanat/tagit

OAI/PMH, OAI, Haravointi

**Comment by CodoDerDritte** [comment]
Muutos on tehty nextien apache-konfiguraatioon.

**Comment by AnneliO** [comment]
Koha-Suomi testaa.

**Comment by CodoDerDritte** [comment]
Testattu ja toimii nexteillä.
