### ISSUE TITLE
outi-nextillä tulee palautuksessa Virhe 500

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#106]
### Mikä vikana?

Yritin palauttaa varauksia sisältävän tietueen niteen [564N26998419](https://outi-next.koha-suomi.fi/cgi-bin/koha/catalogue/moredetail.pl?itemnumber=3505792&biblionumber=2279923&bi=2279923#item3505792) outi-nextillä, mutta tuli Virhe 500.

### Mitä pitäisi tapahtua

Nide pitäisi palautua ja jäädä varaukseen kiinni.

### Kuinka toistaa ongelma/asia

1. Mene outi-nextillä palautukseen ja liitä kenttään viivakoodi 564N26998419
2. Huomaa saaneesi Virhe 500 -ilmoituksen

**Comment by AnneliO** [comment]
Virheilmoitus tulee myös ei-varatun tietueen nidettä palautettaessa.

**Comment by pknuuti** [comment]
Vaaran nextillä sama ongelma, palautuksessa tulee virheilmoitus.

**Comment by emta001** [comment]
Korjattu, johtui siitä, että buildi oli ajettu outi-nextiltä jonka kanta on vielä höps.

**Comment by AnneliO** [comment]
Palautus toimi, kiitos!
