### ISSUE TITLE
 Työkalut/Asiakkaan muokkaus eräajona -toiminto: asiakasmääreen käyttömahdollisuutta tarkentavassa tekstissä virheellisesti asiakasmääreen nimi

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-23x#107]
### Mikä vikana?

Asiakkaan muokkaus eräajona -toiminnossa on asiakasmääreen käyttömahdollisuutta tarkentavassa tekstissä virheellisesti asiakasmääreen nimi eikä asiakastyyppi, kun asiakasmääreen käyttö on rajoitettu tietylle asiakastyypille. 

Helle-Nextillä esimerkiksi näin:
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/2063bbe8-a8cf-46ce-b77e-e8e5dbe96164)

Annelin vinkkaama yhteisön bugitiketti 
https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=35817

**Comment by Kati-Helle** [comment]
Nyt Helle-nextissä näkyy asiakastyypin nimi, kun asiakasmääreen käyttö on rajoitettu tietylle asiakastyypille.

![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/b9c27bde-06d9-4531-937e-7b7f12188a6e)

**Comment by pknuuti** [comment]
Vaaran nextillä tulee ihan oikeanlaiset valinnat Asiakasmääreen kohdalla.

**Comment by sksandel** [comment]
Vaskin Nextillä tulee ihan oikeanlainen tarkentava teksti. Esim  "Tämä määre voidaan asettaa vain asiakastyypille Automaatti"

**Comment by emta001** [comment]
Testattu ja toimii. Suljen tiketin.
