### ISSUE TITLE
Käsittelyerät-toiminnon etusivulta puuttuu valikko vasemmasta reunasta

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#108]
### Mikä vikana?

Käsittelyerät-toiminnossa pitäisi olla etusivulla vasemmassa reunassa valikko, josta saa mm. tehtyä asetuksia ja lisätä käsittelyjonoja. Etusivu on nyt tyhjä.

![kuva](https://github.com/KohaSuomi/Koha-23x/assets/33121325/343d625e-6b67-46c9-825a-dde7a27021c5)

Näkymä sandboxista:

![kuva](https://github.com/KohaSuomi/Koha-23x/assets/33121325/45ef5e9e-5878-4417-8c5a-e9071a52bf24)

**Comment by emta001** [comment]
Toistuuko tämä myös jos kileksi vaihtaa englannin?

**Comment by AnneliO** [comment]
> Toistuuko tämä myös jos kileksi vaihtaa englannin?

Unohtui kirjata, että myös englanninkielinen etusivu on tyhjä. :)

**Comment by emta001** [comment]
`[2024/01/22 13:00:19] [WARN] File not found : js/vue/dist/preservation.js at /home/koha/Koha/Koha/Template/Plugin/Asset.pm line 84.`

Minnehän lie tuommonen on sitten hävinnyt? :D

**Comment by emta001** [comment]
Sovittiin, että Johanna kattoo tätä tarkemmin, miulle tää Vue on hepreaa.

**Comment by johannaraisa** [comment]
Nää ilmeisesti pitää ajella kuten ne sass-tiedostot, on tuo kirjastopolku gitignoressa.

**Comment by johannaraisa** [comment]
Mistä tuonne siis pääsee?

**Comment by AnneliO** [comment]
PreservationModule-järjestelmäasetus pitää olla päällä. Sen jälkeen etusivulle tulee linkki. Laitoin sen nyt päälle outi-nextille.

**Comment by johannaraisa** [comment]
Nyt löytyy valikko sieltä, voi joutua tekemään ctrl+f5

**Comment by AnneliO** [comment]
Kiitos! Valikko näkyy nyt, mutta toimintoon mennessä tulee tällainen ilmoitus vielä:
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/33121325/a19aac74-8ea2-42f5-9b53-ea2ed4f40dc3)

**Comment by johannaraisa** [comment]
> Kiitos! Valikko näkyy nyt, mutta toimintoon mennessä tulee tällainen ilmoitus vielä: ![kuva](https://private-user-images.githubusercontent.com/33121325/298903235-a19aac74-8ea2-42f5-9b53-ea2ed4f40dc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzY5MTcsIm5iZiI6MTcwNjA3NjYxNywicGF0aCI6Ii8zMzEyMTMyNS8yOTg5MDMyMzUtYTE5YWFjNzQtOGVhMi00MmY1LTliNTMtZWEyZWQ0ZjQwZGMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA2MTAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkOGMwMWQzYTliZGNkM2VhYzdkMDU1MTRhZjcwNTVmM2RlNjNkMjk2MjRlMzY3MmQ1MDE2NTU0MjBmZTYzNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.odEwdTvh6mjmGaRkYZAaYvCnUlc0nQtZrITBrI4XELA)

En tiedä mihin tuo liittyy, sillä tuosta preservation-rajapinnasta ei tule virhettä. Ehkä toiseen rajapintaan, mikä on ristiriidassa meidän yhden plugin kanssa.

**Comment by Kati-Helle** [comment]
Helle-nextillä näkyy näin, kun klikkaa Uusi käsittelyerä -linkkiä
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/c4b852e6-afb1-4393-a8d9-e6c64716fb8f)

Kun vaihdoin Koha-kielen, sain tämän
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/3466db84-fbc3-48b7-ba1d-ec3816c97e5e)

**Comment by Kati-Helle** [comment]
Koha-kielen vaihto toiminnon etusivulla toimii kyllä
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/19a6dd7f-ce82-4b6f-a21d-aeb833fb117a)

**Comment by AnneliO** [comment]
Törmäsin myös tuohon Error 400 -virheeseen eilen kieltä vaihtaessa.

**Comment by AnneliO** [comment]
Noista erroreista vois tehdä erilliset tiketit, ei raportoida useita ongelmia yhteen tikettiin. :)

**Comment by AnneliO** [comment]
Alkuperäinen ongelma korjattu. Suljen tiketin. :)
