### ISSUE TITLE
Asiakastiedot: huollettavan muokkausnäytöllä ei näy kirjastokortittomasta huoltajasta/takaajasta mitään tietoja - ksdev/ks-0021-bug-29768-hidepatronname

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#11]
### Siirrettävä ominaisuus

Hidepatronname-järjestelmäasetus piilottaa takaajan tiedot täysin, jos tällä ei ole kirjastokorttia. Tällä muutoksella tuodaan huoltajan nimi näkyville.

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 20.11.2023: Siirretään

**Comment by Kati-Helle** [comment]
Helle-Nextillä näkyy kirjastokortittoman huoltajan/takaajan nimi huollettavan tietojen muokkausnäytöllä

huollettavan muokkausnäyttöä
![Image](https://github.com/KohaSuomi/Koha-23x/assets/99952449/1b0f34a5-8c8a-4315-9e01-5823e2e8e054)

huoltajan/takaajan tietoja
![Image](https://github.com/KohaSuomi/Koha-23x/assets/99952449/3d1383b9-fdfb-4a98-9b7d-d2527a0a8f67)

**Comment by ajrajala** [comment]
Vaski-nextillä huollettavan muokkauksessa näkyy huoltajan nimi + kirjastokortti kuten pitääkin.

**Comment by emta001** [comment]
Testattu ja toimii.

**Comment by emta001** [comment]
Avvan tiketin uudelleen. Edellisen version vaihdon [tiketin 112](https://github.com/KohaSuomi/Koha-22x/issues/122) ongelma on palannut, vaikka siihen tehty korjaus on nexteillä.

**Comment by Kati-Helle** [comment]
Helle-nextissä huollettavan muokkausnäytöllä näkyy nyt kirjastokortittoman takaajan nimi. Nimen linkki vie takaajan asiakastiedon Tiedot-näytölle.
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/d2ff2c4e-ef5b-4f4d-81f4-86795e9c528d)

**Comment by emta001** [comment]
@Kati-Helle korjaantuiko myös "Varaa asiakkaalle"-linkki? Sitä voi testata näin:

1. Hae jokin asiakas
2. Klikkaa "Hae ja varaa" -nappia.
3. Hae jokin teos, esim. Kaikki tiet vievät Roomaan
4. Avaa jokin teos.
5. Klikkaa "Varaa"-nappia.
6. Napista tulisi aueta valikko, jossa on kaksi linkkiä ja toisella voi varata tietueen asiakkaalle.

**Comment by Kati-Helle** [comment]
Joo, korjaantui.

Tietueen Perustiedot-näytöllä Varaa-painikkesta aukeaa tämä (kirjastokorttiarvon piilotin)
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/191d394c-dbdc-4c34-b30d-1ef9fcc9caeb)

Varauksen teko onnistuu tuota tapaa käyttäen.

**Comment by Kati-Helle** [comment]
Hakutulosnäytöllä Varaa-painikkeesta tämä näkymä, kun hakutuloksesta on valittu varattavat tietueet
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/f6c010a1-4d36-4620-85f5-ebd0808832b4)

**Comment by MikkoLiimatainen** [comment]
Kortiton takaaja näkyy huollettavan muokkausnäytöllä ja hae ja varaa -toiminnolla varaaminen toimii nyt oikein.

**Comment by emta001** [comment]
Toimii siis, suljen tiketin.
