### ISSUE TITLE
Käsittelyerät-toiminto: Koha-kielenvaihdosta Virhe 404

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-23x#111]
### Mikä vikana?

Käsittelyerät-toiminnossa käyttöliittymäkielen vaihdosta Virhe 404
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/a5279fef-268e-4a10-9479-8fa36555e579)

Koskien näitä 
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/30e818e2-2c3c-4d8b-9b1b-b6b07cc2c085)

**Comment by AnneliO** [comment]
Testailin tätä PTFS Europen sandboxissa ja siellä ei tule virhettä, kun vaihtaa kielen noilla Käsittelyerä-toiminnon "alasivuilla".

**Comment by emta001** [comment]
Tämä johtui siis puuttuvasta apache-konfin asetuksesta:

`RewriteRule ^/cgi-bin/koha/preservation/.*$ /cgi-bin/koha/preservation/home.pl [PT]`

Kävin lisäämässä tuon helle-nextille ja lisäilen vielä muillekin. Lisään samalla vastaavan asetuksen ERM-toiminnolle.

**Comment by emta001** [comment]
> Tämä johtui siis puuttuvasta apache-konfin asetuksesta:
> 
> `RewriteRule ^/cgi-bin/koha/preservation/.*$ /cgi-bin/koha/preservation/home.pl [PT]`
> 
> Kävin lisäämässä tuon helle-nextille ja lisäilen vielä muillekin. Lisään samalla vastaavan asetuksen ERM-toiminnolle.

Nämä olikin muualla kunnossa paitsi Hellessä.

**Comment by Kati-Helle** [comment]
Kiitos, nyt kunnossa myös Hellessä.
