### ISSUE TITLE
Käsittelyerät-toiminto: Uusi käsittelyerä ja kenttien nimet

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-23x#112]
### Mikä vikana?

Käsittelyerät/Uusi käsittelyerä - kenttänimissä muokattavaa
- nimi-kenttä: nimi on pienellä alkukirjaimella, muiden kenttien nimissä iso alkukirjain
- Oletuskäsittelypol-kenttä: kentän nimestä osa jää piiloon

![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/dd06aefb-67c2-4f18-8bf8-11e99f77cb5e)

**Comment by AnneliO** [comment]
Nimi-sanan alkukirjain on korjattu yhteisössä: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=35387

**Comment by pirliis** [comment]
OUTIssa testattiin Käsittelyerä-toimintoa. Kun niteet vastaanotetaan käsittelystä, niteiden notforloan-arvo ei poistunut.

**Comment by AnneliO** [comment]
> OUTIssa testattiin Käsittelyerä-toimintoa. Kun niteet vastaanotetaan käsittelystä, niteiden notforloan-arvo ei poistunut.

Tekisitkö Pirlii tästä ongelmasta oman tikettinsä? :)

**Comment by AnneliO** [comment]
> OUTIssa testattiin Käsittelyerä-toimintoa. Kun niteet vastaanotetaan käsittelystä, niteiden notforloan-arvo ei poistunut.

Itse asiassa, tässä taitaa olla minun tulkintavirhe ajalta ennen kunnon dokumentaatiota. Testasin tätä nyt myös sandboxissa ja notforloan-tila ei poistu sielläkään. Lisäksi [toiminnon kuvauksessa yhteisön manuaalissakaan](https://koha-community.org/manual/23.11/en/html/preservation.html) ei kerrota notforloan-arvon poistuvan. Sen sijaan siellä on nimenomaan yhdessä kohtaa maininta, että notforloan-tila ei poistu, jos nide poistetaan käsittelyerästä (train). Eli käytännössä tila pitänee määrittää poistuvaksi palautuksessa UpdateNotForLoanStatusOnCheckin -järjestelmäasetuksella.

**Comment by pirliis** [comment]
> > OUTIssa testattiin Käsittelyerä-toimintoa. Kun niteet vastaanotetaan käsittelystä, niteiden notforloan-arvo ei poistunut.
> 
> Itse asiassa, tässä taitaa olla minun tulkintavirhe ajalta ennen kunnon dokumentaatiota. Testasin tätä nyt myös sandboxissa ja notforloan-tila ei poistu sielläkään. Lisäksi [toiminnon kuvauksessa yhteisön manuaalissakaan](https://koha-community.org/manual/23.11/en/html/preservation.html) ei kerrota notforloan-arvon poistuvan. Sen sijaan siellä on nimenomaan yhdessä kohtaa maininta, että notforloan-tila ei poistu, jos nide poistetaan käsittelyerästä (train). Eli käytännössä tila pitänee määrittää poistuvaksi palautuksessa UpdateNotForLoanStatusOnCheckin -järjestelmäasetuksella.

Okei, kiitos tiedosta! 
(Sori, kun en vielä ehtinyt tekemään uutta tikettiä. On kyllä ollut työlistalla.) :)

**Comment by AnneliO** [comment]
Nexteille on viety uusimmat käännökset ja ne yksistään eivät auttaneet korjaamaan näitä kenttien nimiä. Onko ongelma niin iso, että korjaus pitäisi tuoda erikseen meidän versioon? Vai voimmeko elää tämän kanssa, kunnes korjaus tulee mukaan, kun siirrymme versioon 24.xx? :)

**Comment by pirliis** [comment]
Mielestäni voidaan odottaa versio 24.xx.
