### ISSUE TITLE
Tilausta tallennettaessa tulee virhe 500

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#113]
### Mikä vikana?

Jos tekee uuden tilauksen tai tallentaa jo olemassa olevan tilauksen, tulee virhe 500. Tiedot kyllä tallentuvat virheestä huolimatta.

**Comment by Kati-Helle** [comment]
Helle-testauksessa tietue tallentui ja tilaus muodostui. Nidettä ei sen sijaan muodostunut
![Image](https://github.com/KohaSuomi/Koha-23x/assets/99952449/42cdc4ea-8de8-406a-80e0-902c89d05113)

Tilauskoria tallentaessa valittuna tämä
![Image](https://github.com/KohaSuomi/Koha-23x/assets/99952449/bbe0d23c-d3ae-4af4-a7d9-e98302e4d192)

**Comment by emta001** [comment]
Outi-nextillä on luultavasti kannassa/skeemassa jotain vinksallaan.

**Comment by AnneliO** [comment]
> Outi-nextillä on luultavasti kannassa/skeemassa jotain vinksallaan.

Ymmärsin Katin toisen tiketin kommentista, että myös Hellessä tulee virhe 500 tilausta tallennettaessa.

**Comment by ajrajala** [comment]
Samoin vaski-nextillä tulee virhe, tietue tallentuu mutta nide ei.

**Comment by emta001** [comment]
> > Outi-nextillä on luultavasti kannassa/skeemassa jotain vinksallaan.
> 
> Ymmärsin Katin toisen tiketin kommentista, että myös Hellessä tulee virhe 500 tilausta tallennettaessa.

Tosiaan, lokiin on tullut Helleen:

```
Can't call method "value" on an undefined value at /home/koha/Koha/acqui/addorder.pl line 432.
DBIx::Class::ResultSetColumn::new(): Attempting to retrieve non-unique column 'biblionumber' on a resultset containing one-to-many joins will return duplicate results. at /home/koha/Koha/Koha/Objects.pm line 426
```

Vaski-next:

```
DBIx::Class::ResultSetColumn::new(): Attempting to retrieve non-unique column 'biblionumber' on a resultset containing one-to-many joins will return duplicate results. at /home/koha/Koha/Koha/Objects.pm line 426
DBIx::Class::ResultSet::_construct_results(): Unable to properly collapse has_many results in iterator mode due to order criteria - performed an eager cursor slurp underneath. Consider using ->all() instead at /home/koha/Koha/Koha/Objects.pm line 317
```

Tuo Hellen eka virhe voi olla ihan jokin hassu arvo kannassa. Mutta nuo muut virheet on kyllä skeemahäröilyjä.

**Comment by emta001** [comment]
Ongelma on siis siinä, ettei meillä ole vielä meidän viivakoodin generointi muutos mukana. Joten tilauksen niteille yritetään luoda viivakoodia muodossa, jolle ei ole vielä koodia. Vaihdoin "autoBarcode" asetuksen outi-nextillä ja nyt rupesi toimimaan.

**Comment by emta001** [comment]
Toin nyt viivakoodien generoinnin nexteille, toimiiko tilauksen tallennus nyt?

**Comment by AnneliO** [comment]
Ensin ei tullut viivakoodia ollenkaan outi-nextillä, mutta vaihdoin autoBarcode-asetukseen prefix-vaihtoehdon, niin viivakoodi muodostui.

**Comment by ajrajala** [comment]
Tarkistin meidänkin nextillä, nyt pelittää.

**Comment by Kati-Helle** [comment]
Helle-nextilläkin toimii nyt autobarcode-asetusmuutoksen jälkeen.

**Comment by Kati-Helle** [comment]
> > > Outi-nextillä on luultavasti kannassa/skeemassa jotain vinksallaan.
> > 
> > 
> > Ymmärsin Katin toisen tiketin kommentista, että myös Hellessä tulee virhe 500 tilausta tallennettaessa.
> 
> Tosiaan, lokiin on tullut Helleen:
> 
> ```
> Can't call method "value" on an undefined value at /home/koha/Koha/acqui/addorder.pl line 432.
> DBIx::Class::ResultSetColumn::new(): Attempting to retrieve non-unique column 'biblionumber' on a resultset containing one-to-many joins will return duplicate results. at /home/koha/Koha/Koha/Objects.pm line 426
> ```
> 
> Vaski-next:
> 
> ```
> DBIx::Class::ResultSetColumn::new(): Attempting to retrieve non-unique column 'biblionumber' on a resultset containing one-to-many joins will return duplicate results. at /home/koha/Koha/Koha/Objects.pm line 426
> DBIx::Class::ResultSet::_construct_results(): Unable to properly collapse has_many results in iterator mode due to order criteria - performed an eager cursor slurp underneath. Consider using ->all() instead at /home/koha/Koha/Koha/Objects.pm line 317
> ```
> 
> Tuo Hellen eka virhe voi olla ihan jokin hassu arvo kannassa. Mutta nuo muut virheet on kyllä skeemahäröilyjä.

Helle-tuotannossahan on havaittu joitakin tietueita, jotka tulevat tiedonhaun hakutulokseen tuplana. Onkohan tässä jotain samaa/tuohon liittyvää vai jotain ihan muuta?

**Comment by AnneliO** [comment]
Tämä tuntuis nyt toimivan, joten suljen tiketin.
