### ISSUE TITLE
outi-nextillä tulee virhe 500, kun yrittää tallentaa uuden asiakkaan ilman pakollista holdid/varaustunnus-tietoa

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#114]
### Mikä vikana?

Jos outi-nextillä yrittää tallentaa uuden asiakkaan ilman pakolliseksi merkittyä HOLDID / varaustunnus-tietoa, tulee virhe 500. Testasin myös vaski-nextillä ja siellä tulee asianmukainen huomautus, että pakollinen tieto puuttuu.

**Comment by emta001** [comment]
Ilmeisesti tämä on jo korjaantunut? Kokeilin lisätä asiakkaan ilman varasutunnusta ja Tallenna-napin painaminen täräytti kentän viereen "Tämä kenttä on pakollinen" tekstin.

![image](https://github.com/KohaSuomi/Koha-23x/assets/37581745/de964b25-bd9d-4c0e-a88b-018fdd77898d)

**Comment by AnneliO** [comment]
Jeps, tämä näyttäis nyt toimivan! Suljen tiketin.
