### ISSUE TITLE
JS-rimpu: Ylimääräisten välilyöntien poisto ei toimi 952o-kentässä

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#117]
### Mikä vikana?

Tällä JS-rimpsulla poistetaan niten muokkausnäytöllä kentistä ylimääräiset välilyönnit. Se toimii kaikissa muissa kentissä paitsi 952o-kentässä eli Kohan koko signum -kentässä. Testi-kannassa se vielä toimii tuossakin kentässä.

```
/* Poista niteen muokkausnäytön kentistä välilyönnit alusta, lopusta ja useammat peräkkäiset välilyönnit välistä*/
$(document).ready(function() {
  $('body#cat_additem.cat input').blur(function() {
     var tmp = $(this).val();
     tmp = tmp.replace(/^ +/, '');
     tmp = tmp.replace(/ +$/, '');
     tmp = tmp.replace(/  */g, ' ');
     $(this).val(tmp);
  });
});
```

Sama ongelma on myös kausijulkaisujen vastaanotossa nidetietojen  muokkauksessa 952o-kentässä:

```
/* Poista kausijulkaisun vastaanottonäytön kentistä välilyönnit alusta, lopusta ja useammat peräkkäiset välilyönnit välistä*/
$(document).ready(function() {
  $('body#ser_serials-edit.ser input').blur(function() {
     var tmp = $(this).val();
     tmp = tmp.replace(/^ +/, '');
     tmp = tmp.replace(/ +$/, '');
     tmp = tmp.replace(/  */g, ' ');
     tmp = tmp.replace(/(^[1-2][0-9]{3}) *: */, '$1 : ');
     $(this).val(tmp);
  });
});
```

**Comment by atarnus** [comment]
Tuossa kenttäelementissä ei ole mikään muttunut, se on edelleen input tekstityypillä tuon saman body id:n alla. Näin yhtäkkiä arvailisin, että mahdollisesti tuo kentän vieressä oleva kolmen pisteen linkista tuleva funktio, joka muodostaa automaattisen signumin kenttään, tekisi jotain, joka disabloi tuon blur-eventin siitä kentästä.

**Comment by atarnus** [comment]
Yritin katsella tätä uudestaan, ja tosiaan sekä fokus että blur eventit eivät tartu ollenkaan tuohon input kenttään, vaikka ne toimivat ihan hyvin muissa kentissä. Click eventit toimivat myös tuossa kentässä. Tuo signumin tekevä koodi näyttäisi sisältävän omia määrittelyjä kentän blurrille ja fokusille, niin täytynee johtua siitä. Sitä en kyllä keksi, että miksi aiemmin toimi, ehkä nyt joku latausjärjestys tässä on muuttunut tms. Omassa testissä ei ole signumin luontia niin en vielä päässyt kokeilemaan muutoksia.

**Comment by AnneliO** [comment]
Lisätiedoksi, ylimääräisten välilyöntien poisto toimii sellaisilla liitännäisillä, joissa ei haeta luokkaa 084a-kentästä. Eli esim. fi_signumbuilder_942khm_branch_loc.pl -liitännäisen ollessa käytössä ylimääräiset poistuu.

**Comment by atarnus** [comment]
Uskoisin että ongelma poistuu yksinkertaisesti kun poistetaan noista 084.pl -versioista

```
function Blur$function_name(index) {
    // No action
}

function Focus$function_name(subfield_managed, id, force) {
    // Uncomment the below line to have the signum updated when the field gets focus
    // return Clic$function_name(id);
}
```

Näillä ei ole käyttötarkoitusta kun signumn luodaan siitä kolmen pisteen linkistä.

**Comment by atarnus** [comment]
Testattu pikaisesti ja tuntuu toimivan.

**Comment by atarnus** [comment]
Yllä olevat rivit on nyt poistettu nexteillä noista 084-signum-buildereista, ja tämä JS-rimpsu toimii nyt.

084a_mainheading_branchloc_genre_signum_builder.pl  kuitenkin näyttää jättävän tuon signum-kentän lukkoon, niin vilkaisen vielä että mikä siinä on vikana. Ei liity kyllä tähän välilyöntiasiaan enää.

**Comment by atarnus** [comment]
Laitoin fiksin typoon 084a_mainheading_branchloc_genre_signum_builder.pl:ssä. Saattaa olla nexteillä vielä epäkunnossa. Muiden pitäisi toimia ok.

**Comment by atarnus** [comment]
Voisi vielä joku testata, että nämä rimpsut nyt toimivat 952o-kentissä. Varsinaista signumin muodostusta on jo testattu tuolla: https://github.com/KohaSuomi/Koha-23x/issues/17

**Comment by Kati-Helle** [comment]
Helle-nextissä ylimääräiset välilyönnit poistuivat 9520-kenttäarvosta sekä kentän alusta että lopusta. Ylimääräiset välilyönnit poistuvat heti kentästä poistuessa.

(Helle-nextissä toimii edelleen oikein signum-liitännäinen loc_ccode_084a_mainheading_signum_builder.pl)

**Comment by pknuuti** [comment]
Vaaran nextilläkin toimii oikein eli ei ole turhia välilyöntejä. Liitännäinen:branchloc_084a_mainheading_signum_builder.pl,

**Comment by MikkoLiimatainen** [comment]
Vaskissa toimii, ei turhia välilyöntejä liitännäisellä loc_084a_mainheading_signum_builder.pl

**Comment by pirliis** [comment]
OUTIssa toimii myös, ylimääräiset välilyönnit poistuvat.

**Comment by AnneliO** [comment]
Toimii, suljen tiketin.
