### ISSUE TITLE
Hyllyvaraukset-raportti - ksdev/ks-0022-KD-4630

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#12]
### Siirrettävä ominaisuus

Hyllyvaraukset-raportista on tehty oma versio, koska yhteisön raportti on liian hidas ja raskas suomalaiseen varausmäärään nähden.

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 20.11.2023: Siirretään

**Comment by CodoDerDritte** [comment]
Tuotu nextille, mutta sarakkeiden määrityksissä on vielä ongelmia.

**Comment by CodoDerDritte** [comment]
Sarakkeet nyt myös korjattu. Ongelmana oli editorin tekemä kepponen konfiguraatiotiedoston sisennyksissä.

**Comment by CodoDerDritte** [comment]
Raportin päivitys on ajastettu Next-kantoihin.

**Comment by AnneliO** [comment]
Pieni asia, mutta Lainaus ja palautus -sivulla Hyllyvaraukset-napista puuttuu kuvake/ikoni. :)

Näyttää nyt tältä:
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/33121325/773c1590-b364-4e34-88e0-773539a1a17f)

Kuuluisi olla tämän näköinen:
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/33121325/214e437a-ef8d-4b47-81ff-fe2497327f79)

**Comment by CodoDerDritte** [comment]
Jep, ikonin nimi on näköjään muuttunut, korjataan.

**Comment by CodoDerDritte** [comment]
Nyt on ikonikin kuosissa.

**Comment by AnneliO** [comment]
> Nyt on ikonikin kuosissa.

Siellähän se, kiitos!

**Comment by Kati-Helle** [comment]
Helle-nextissä vaikuttaa toimivalta. Käännöksiä puuttuu.

Tuotanto ja Next -näyttökuvat
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/b2368375-32d6-465b-af6e-a4216a07ed39)

**Comment by pirliis** [comment]
Testailin OUTIn hyllyvarausraporttia. Näytti toimivalta ja samat sarakkeet olivat kuin tuotannossa.

**Comment by MikkoLiimatainen** [comment]
Vaski-Nextillä toimii myös.

**Comment by AnneliO** [comment]
Toimii, suljen.
