### ISSUE TITLE
Onko nexteillä samaa hakuviiveongelmaa kuin tuotannoissa oli?

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#120]
### Mikä vikana?

Toistuuko tämä [tiketin 826](https://github.com/KohaSuomi/Koha/issues/826) hakuviiveongelma myös next-kannoissa?

Yritin itse testailla outi-nextillä, mutta sain aina taulukoiden haut ja suodatukset toimimaan ok ilman tuotantoon tehtyjä JS-rimpsujakin.

**Comment by lmstrand** [comment]
Datatable-elementtien sarakesuodatukseen tehty koodikorjaus on mennyt yhteisöön, mutta se ei ole meillä matkassa, koska muutos hyväksyttiin vasta sen jälkeen, kun branchattiin meidän 23-versio.
https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=35396
Ellei ongelma ole jostain syystä maagisesti poistunut, tuo branchi pitäisi ottaa mukaan.
Javascript-rimpsut ovat vielä erikseen ja koskevat vain sitä yleistä haku-kenttää datatablen ylälaidassa.

**Comment by lmstrand** [comment]
Yhteisöön hyväksytty, meiltä vielä puuttunut commit viety nollabranchiin. Teen javascript-pluginin korvaamaan intranetuserjs-rimpsujen tarpeen haku-kenttien viiveen lisäämiseen.

**Comment by lmstrand** [comment]
Javascript-plugin löytyy nexteiltä nimellä IntranetUserJS: Haku-kenttien viiveet.
Lisättyä rimpsua voi tarkastella pluginin tool-ominaisuudella. Jätin pluginin kaikille kimpoille päälle/aktiiviseksi.

**Comment by ajrajala** [comment]
> Yhteisöön hyväksytty, meiltä vielä puuttunut commit viety nollabranchiin. Teen javascript-pluginin korvaamaan intranetuserjs-rimpsujen tarpeen haku-kenttien viiveen lisäämiseen.

Olisiko tuon pitänyt korjata tietueen saatavuustiedoissa suodatuksessa oleva hakuviiveongelma? Siellä ongelma näkyy edelleen toistuvan, mutta esim. asiakashaun tuloksen suodatuksessa ongelmaa ei nähdäkseni enää ole.

**Comment by lmstrand** [comment]
Tutkin vielä tämän.

**Comment by lmstrand** [comment]
Missä tämä näkymä on? :D Voitko linkata esimerkin?

**Comment by ajrajala** [comment]
Esimerkki varmaan olisi selkiyttänyt. :D Eli esim. jos avaat [tämän tietueen](https://vaski-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=4298226&searchid=scs_1714052448298) ja sieltä suodatuksen niin näyttäisi tiputtelevan kirjaimia helposti pois kun rivakasti kirjoittaa:
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/44638512/d6c51ebf-4d55-458d-8093-b44ac328cb4e)

**Comment by lmstrand** [comment]
Korjaus on ollut nexteillä nolla-branchissa. Jokin on rikki nexteillä tuon Annin tapauksessa. Asiakashaun suodatuksessa suodatusviive toimii kuten pitää ja käynnistää suodatuksen 500ms päästä kirjoittamisen loputtua.

**Comment by lmstrand** [comment]
Korjaus poistettu nollabranchista omakseen ksdev/ks-0129-KD-G826-add-delay-for-datatables-search-filters. Korjaus ei jostain syystä toimi tietueen perusnäytöllä saatavuustiedoissa, mutta toimii ainakin asiakashaussa. En tiedä mistä kiikastaa.

**Comment by lmstrand** [comment]
Voisiko tietueen perusnäytöllä saatavuustietojen suodatuksen tökkimistä testata yhteisön sandboxissa? Jotain meiltä puuttuu, jos siellä toimii suodatus ok.

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 13.5.2024: Tämän korjaaminen vaatisi korjauksia yhteisöstä. Ne on sellaisia, jotka eivät istu sellaisenaan meidän version päälle. Korjaus tulee versioon 24.xx.
