### ISSUE TITLE
Nextiltä tuotantoon siirrettävät tiedot

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#121]
### Mikä vikana?

Mitä tietoja tarvitsee siirtää versionvaihdon aikaan nextiltä tuotantoon?

**Comment by pknuuti** [comment]
Järjestelmäasetukset ainakin :)

**Comment by ajrajala** [comment]
Tarvitseeko asiakasmääreitä siirtää? [Niiden asetuksiin on tullut hakuun liittyviä asetuksia.](https://github.com/KohaSuomi/Koha-23x/wiki/Uutta-23.x%E2%80%90versiossa#asiakasm%C3%A4%C3%A4reisiin-mahdollisuus-m%C3%A4%C3%A4ritt%C3%A4%C3%A4-haetaanko-niit%C3%A4-perushaussa)

Vaihtoehtoisesti voi tietty laittaa muistiin, että halutunlaiset asetukset pistetään paikoilleen tuotantoon päivityksen valmistumisen jälkeen, kun asiakasmääreitä ei kuitenkaan niin paljon ole.

**Comment by Kati-Helle** [comment]
Maksutyypit.
Arvoissa uusi valittava arvo: Estää lainauksen?

**Comment by Kati-Helle** [comment]
Hakukoneen asetukset/Nimeketietueet
Fasettien järjestys
liittyen tikettiin https://github.com/KohaSuomi/Koha-23x/issues/132

**Comment by AnneliO** [comment]
Pääkäyttäjien palaveri 16.4.2024

Kopioidaan nextiltä tuotantoon: järjestelmäasetukset

Lisätään muistilistalle, että pääkäyttäjät tekevät versionvaihdon jälkeen: asiakasmääreiden asetukset, Aineistotyyppi-fasetin siirto oikeaan kohtaan faseteissa.

**Comment by pirliis** [comment]
Lisätäänkö muistilistalle, että pääkäyttäjät käyvät versionvaihdon jälkeen määrittämässä maksutyypeille, vaikuttaako tyyppi lainauskieltoon? Vai siirretäänkö maksutyypit nextiltä tuotantoon versionvaihdon yhteydessä?

**Comment by AnneliO** [comment]
> Lisätäänkö muistilistalle, että pääkäyttäjät käyvät versionvaihdon jälkeen määrittämässä maksutyypeille, vaikuttaako tyyppi lainauskieltoon? Vai siirretäänkö maksutyypit nextiltä tuotantoon versionvaihdon yhteydessä?

Tämä taitaa jo olla muistilistalla: https://github.com/KohaSuomi/Koha-23x/wiki/P%C3%A4%C3%A4k%C3%A4ytt%C3%A4jien-muistilista#yll%C3%A4pitomaksutyypit

**Comment by ReettaSiili** [comment]
Ilmoitusten ja kuittien tekstejä EI siirretä, mahdolliset muutokset siis päivityksen jälkeen suoraan tuotantoon.

**Comment by AnneliO** [comment]
Suljen tiketin.
