### ISSUE TITLE
Tietueen muokkauksessa kentän muokkauksessa ongelmia

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha-23x#122]
### Mikä vikana?

Jos tietuetta menee muokkaamaan nextillä ja haluaa muuttaa kenttää, jossa on jo jotakin sisältöä, ei kursoria saa kohdistettua olemassaolevan merkkijonon loppuun vaan ainoastaan merkkijonon eteen. Kentässä olevaa tekstiä ei pysty myöskään tuplaklikkauksella maalaamaan.

### Kuinka toistaa ongelma/asia

1. Hae jokin tietue ja valitse "Muokkaa tietuetta"
2. Siirry kenttään, jossa on jo tietoa, esim. 245a
3. Huomaa, että kursoria ei saa kohdistettua muualle kuin merkkijonon alkuun eikä olemassaolevaa tekstiä pysty tuplaklikkauksella maalaamaan

**Comment by pknuuti** [comment]
Testasin Vaaran nextillä ja on todella hankala muokata tietuetta, kun ei voi korjata vaikka yksittäistä kirjainta lauseessa menemällä oikeaan kohtaan suoraan. Myöskään tekstin valinta ei onnistu tuplaklikkaamalla. Omituinen vika.

**Comment by AnneliO** [comment]
PTFS Europen Sandboxissa ei tapahdu tätä. Hiiren kohdistimen saa klikattua mihin kohtaan kenttää tahansa ja kaksoisklikkauskin toimii.

**Comment by atarnus** [comment]
En saa vikaa toistettua. Mahtoiko olla väliaikainen? Eilen ajettiin noita nextejä uusiksi, niin olisiko siinä ehkä muuttunut. Tarkistakaapa vielä, että onko ongelma poistunut.

**Comment by pknuuti** [comment]
Ilmeisesti jotain on muuttunut, ei Vaaran nextilläkään ole enää tuota ongelmaa. Tietueen kenttää voi hyvin muuttaa.

**Comment by ajrajala** [comment]
Jep, ongelma on poistunut. Olis pitänyt malttaa jättää tietueen sörkkimiset tälle päivälle. :D
