### ISSUE TITLE
Tukipyyntö: Kuvailu/Niteiden muokkaus eräajona -toimintoon piilotukset uusille toiminnoille: Jätä pois paikallisten varausten jonosta JA Palauta niteet

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-23x#123]
### Mikä vikana?

Kuvailu / Niteiden muokkaus eräajona -toiminnossa on kaksi uutta erämuokkaustapaa, jotka on tarpeen saada piiloon. Piilotustarpeesta on keskusteltu Koha-Suomen pääkäyttäjäpalaverissa tiistaina 19.3.2024. (Mahdollista erikoistilannetta varten toiminnot saa tarvittaessa käyttöön piilotuksen väliaikaisesti poistamalla.)

Muut määreet / Jätä pois paikallisten varausten jonosta
* Paikallisten varausten jono ei ole käytössä

Valinnat / Palauta niteet
* Testieni perusteella toiminnossa palautetusta lainasta ei jää jälkeä statistics-tauluun. Niteen perustiedoissa niteen viimeinen havaintoajankohta ei muutu.

![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/9c2973d9-713d-496e-ae02-eb03db1b0d3e)

Cataloging / Batch item modification

Other attributes / Exclude from local holds priority:

Options /Check in items:

**Comment by atarnus** [comment]
Lisättävissä itse Intranetuser.css:

```
/* Piilota niteiden eräajosta 'Muut määreet - Jätä pois paikallisten varausten jonosta' ja 'Valinnat - Palauta niteet' */
body#tools_batchMod-edit fieldset:has(select#exclude_from_local_holds_priority),
body#tools_batchMod-edit fieldset:has(select#mark_items_returned) { display: none; }
```

Minulla ei ole nyt mahdollisuutta nopsaan katsoa josko tällaisia samannimisiä kenttiä esiintyy jossain muualla, testatkaa ja ilmoittakaa jos katoaa jostain muualta. Tuohon on kuitenkin laitettu että pitää olla fieldset, jonka sisällä tuon id:n select, ja on aika yksilöivät vielä nuo id:t, niin yhtäkkiseltään voisi luulla olevan uniikkeja tapauksia.

**Comment by Kati-Helle** [comment]
Kiitos! Lisäsin rimpsun Helle-nextiin: piilotus toimii. 

Testasin niteiden erämuokkauksen piilotuksen jälkeen: toimii.
Testasin Palautus-toiminnossa niteen palautuksen: toimii ja palautusnäytöllä näkyvät sarakkeet ok.

**Comment by pknuuti** [comment]
Vaaran nextillä tämä ei toimi. Piilotusrimpsu lisätty IntraneUserCSS-asetukseen, mutta piilotettavat ovat edelleen hyvin näkyvillä erämuokkauksen sivulla.

**Comment by AnneliO** [comment]
> Vaaran nextillä tämä ei toimi. Piilotusrimpsu lisätty IntraneUserCSS-asetukseen, mutta piilotettavat ovat edelleen hyvin näkyvillä erämuokkauksen sivulla.

Oisko jokin välimuistijuttu, koska mulla ne eivät näy vaara-nextillä:

![kuva](https://github.com/KohaSuomi/Koha-23x/assets/33121325/aedd0403-87fc-4f20-bb9e-e41f5b33f4ba)

**Comment by pknuuti** [comment]
No kappas, niinpäs onkin. Ei ole kovin monesti tapahtunut tätä, että asetuksen muutos ei näy heti. Eli siis toimii :)

**Comment by atarnus** [comment]
Kun tulee tuonne selaimen puolelle muutoksia, niin aina kannattaa kokeilla päivittää sivua Ctrl+F5 (ei sillä että itsekään aina muistaisi). :)

**Comment by AnneliO** [comment]
Lisäsin rimpsun 23.xx-tietovarannon IntranetUserCSS-wikiin [Muita-osioon](https://github.com/KohaSuomi/Koha-23x/wiki/IntranetUserCSS#muita) tämän.

**Comment by MikkoLiimatainen** [comment]
Vaskissa CSS-rimpsu ei näytä toimivan. Epäilen, että ongelma on Firefoxin versiossa, koska meillä on käytössä 115.8 ESR ja tuo has() on tullut käyttöön vasta versiossa 121. Hienoa, että Firefox on vihdoinkin saanut tuen has()-valitsimelle, mutta meidän versiossamme se ei valitettavasti toimi. Toivottavasti pian tulee sellainen ESR-versio, jossa tämä ominaisuus on mukana.

**Comment by atarnus** [comment]
Jos ongelma on Firefoxissa ja has()issa, niin tämän pitäisi toimia:

```
/* Piilota niteiden eräajosta 'Muut määreet - Jätä pois paikallisten varausten jonosta' */
body#tools_batchMod-edit div#cataloguing_additem_newitem
fieldset.rows:nth-child(4),
body#tools_batchMod-edit div#cataloguing_additem_newitem
fieldset.rows:nth-child(5) { display:none; }
```

Saattaa kuitenkin olla myös kiinni joistain välimuistikeijuista. Pirlillä jäi nuo fieldsetit näkyviin Outi-nextillä, vaikka kaikilla muilla ne katosi. Ctr+F5 ei auta. Itsekään en saanut äsken muutoksia päivittymään, mutta näemmä oli laitettu kahteen kertaan Outille nuo rivit, ei ihme ettei omat muutokset tuntuneet tekevän mitään :)
Eli selvitetäänpä onko Pirlilläkin vanhempi selainversio.

**Comment by MikkoLiimatainen** [comment]
Juu, tuo pätkä toimi. Koitin tuon has()-version kanssa tyhjentää välimuistit, sulkea selaimen, crtl-f5 ja tarkistin tarkastele-toiminnolla, että kyseinen pätkä oli sivulla, mutta ei se vaan toiminut. No, ehkä joskus tulevaisuudessa voimme Vaskissakin siirtyä käyttämään tuota pätkää, mutta hyvä että nyt on versio vanhoillekin selaimille.

**Comment by atarnus** [comment]
Ja hyvä että tuli nyt ilmi ongelma tuon kanssa, niin on tiedossa ettei tällä hetkellä toimi kaikkialla. Pakottaa nyt joissakin tapauksissa pysyttelemään sitten JS:ssä.

**Comment by AnneliO** [comment]
Lisäsin kummatkin versiot [IntranetUserCSS](https://github.com/KohaSuomi/Koha-23x/wiki/IntranetUserCSS)-wikiin huomautuksilla Firefox-versiosta.

**Comment by AnneliO** [comment]
Toimii, suljen.
