### ISSUE TITLE
Yarn-buildattujen CSS:ien ja JS:ien käsittely buildiin

### ISSUE THREAD

**Issue by CodoDerDritte** [KohaSuomi/Koha-23x#124]
### Mikä vikana?

Buildin jälkeen Kohan käyttöliittymä on "sekaisin".

### Mitä pitäisi tapahtua

build-release -skriptiin täytyy lisätä käsittely yarn-buildatuille CSS- ja JS-tiedostoille, jotka ovat nykyään utilityn alla.

**Comment by CodoDerDritte** [comment]
Käsittely lisätty.

**Comment by CodoDerDritte** [comment]
Tämä on toistaiseksi erillisenä "fix-yarn.sh" skriptinä, koska ei haluta tapahtuvan tuotannossa. Yhdistetään build-releaseen versiopäivityksen jälkeen.

**Comment by AnneliO** [comment]
Tämä tiketti on suljettu, mutta sen tilana on Odottaa. Pitäisikö tiketti aukaista vai muuttaa tilaksikin suljettu?

**Comment by lmstrand** [comment]
Tämä ok, laitoin suljetuksi.
