### ISSUE TITLE
Asiakkaan viestiasetuksista piiloon saapumisilmoituksen vaihtoehto: Vain koosteilmoitus

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-23x#126]
### Mikä vikana?

Asiakkaan viestiasetuksiin tarvitaan piilotus saapumisilmoituksen Vain koosteilmoitus -vaihtoehdolle. 
Koskee kaikkia asiakastyyppejä.

![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/68d81061-2624-4756-ac3c-a3e5923a71c8)

Piilotustarve on mietitty/päätetty yhteisesti Koha-Suomen pääkäyttäjäpalaverissa 6.3.2024.

**Comment by AnneliO** [comment]
Mikko muisti, että [tiketissä 389](https://github.com/KohaSuomi/Koha/issues/389#issuecomment-1413567911) on piilotus jo olemassa koko kooste-sarakkeelle. Riittäisikö se?

**Comment by atarnus** [comment]
Koko sarakkeen piilotuksen sai muutettua CSS:ksi:

```
/* Piilota kooste-sarake Kohan viestiasetustaulusta */
fieldset#memberentry_messaging_prefs th:nth-child(5),
fieldset#memberentry_messaging_prefs td:nth-child(5),
div#patron-messaging-prefs th:nth-child(5),
div#patron-messaging-prefs td:nth-child(5) {
  display:none;
}
```

Jos tosiaan on käytössä sitten muita sarakkeita, niin muuttaa tuota lukua sen mukaan. Yo. piilottaa 5. sarakkeen.

**Comment by ElinaUotila** [comment]
Kirkes-Nextillä sarake poistui tuolla rimpsulla toivotusti näkyvistä sekä asiakkaan tiedot että muokkaus -sivuilta.

**Comment by Kati-Helle** [comment]
Helle-nextissä rimpsu toimii ok piilottaen Vain koosteilmoitus -sarakkeen.

**Comment by pirliis** [comment]
OUTIssa koko koosteilmoitus -sarakkeen piilotus CSS:llä toimii.

**Comment by pknuuti** [comment]
Miksi koko sarake piilotetaan? Eikö ole tarkoitus piilottaa koosteilmoituksen mahdollisuus vain saapumisilmoitukselta? Vai meneekö erääntymisilmoituksista automaattisesti koosteviesti ilman erillistä valintaa (jolloin saraketta ei tarvita)?

**Comment by AnneliO** [comment]
> Miksi koko sarake piilotetaan? Eikö ole tarkoitus piilottaa koosteilmoituksen mahdollisuus vain saapumisilmoitukselta? Vai meneekö erääntymisilmoituksista automaattisesti koosteviesti ilman erillistä valintaa (jolloin saraketta ei tarvita)?

Erääntymisilmoituksiin on pakotettu päälle koosteviesti, jottei asiakkaille lähde sadasta lainasta sataa viestiä. :) Eli sitä ei tarvitse koskaan valita ja koko sarakkeen voi piilottaa.

**Comment by AnneliO** [comment]
Meillä on käytännössä aina ollut pakotus kooste-täppiä varten. Tällä hetkellä pakotus on tehty triggerillä. :)

**Comment by pirliis** [comment]
Ilmeisesti koostetäppien piilotus Finna-nextiltä pitää tehdä taas erikseen, vaikka ne on tuotannosta piilotettu?

**Comment by AnneliO** [comment]
> Ilmeisesti koostetäppien piilotus Finna-nextiltä pitää tehdä taas erikseen, vaikka ne on tuotannosta piilotettu?

Tuotanto-Finna ja Next-Finna ovat eri näkymiä, joilla on omat säätönsä, joten todennäköisesti juurikin niin. Jos siis haluaa varmistaa, että ne toimivat edelleen ennen kuin tuotanto päivitetään seuraavaan versioon. :)

**Comment by ReettaSiili** [comment]
Myös Siili-nextiltä koostesarake nyt piilotettu.

**Comment by AnneliO** [comment]
Piilotusrimpsu lisätty [IntranetUserCSS-wikiin asiakastietojen suositeltuihin](https://github.com/KohaSuomi/Koha-23x/wiki/IntranetUserCSS#suositeltavat).

Suljen tiketin.
