### ISSUE TITLE
Takaajan tiedoissa näkyy taattavan julkisoikeudelliset maksut

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha-23x#128]
### Mikä vikana?

Meillä on intranetusercss-rimpsu:
/* Piilota Näytä takaajalle lainat ja Näytä takaajalle maksut -tiedot asiakkaan Tiedot-sivulta */
#patron-privacyguarantor + li { display: none; }
#patron-privacyguarantor { display: none; }

Rimpsu piilottaa tällä hetkellä takaajan tiedoista taattavan yksityisoikeudelliset maksut, mutta ei julkisoikeudellisia maksuja.

OUTIssa taattavan borrowernumber=162771 maksut:
![image](https://github.com/KohaSuomi/Koha-23x/assets/98814860/2c32aef1-69fe-4195-88be-52447fc671bd)

Näkymä takaajan borrowernumber=64487 tiedoissa: 
![image](https://github.com/KohaSuomi/Koha-23x/assets/98814860/0bf621bb-5d07-4a6b-a031-f127681fdbe8)

Samoin, takaajalla näkyy välilehti "Taattavat maksut":
![image](https://github.com/KohaSuomi/Koha-23x/assets/98814860/c270f36e-0ea6-434e-8178-1dd3dfc1aa7c)

### Mitä pitäisi tapahtua

CSS-rimpsun tulisi piilottaa takaajalta sekä taattavan julkis- että yksityisoikeudelliset maksut.

**Comment by emta001** [comment]
Välilehden saa piiloon lisäämällä tämän:

`#guarantees_finesandcharges-tab { display: none; }`

Mutta tuo viesti onkin sitten vähän hankalampi, koska siinä ei ole id:tä johon napata.

**Comment by emta001** [comment]
Kyllä tuon viestinkin sai piiloon, kun otti vaan silmän käteen ja huomas, että sillä on class :smile: Sen saa siis piiloon tällä:

`.guarantees-fines { display: none; }`

**Comment by atarnus** [comment]
Näillä CSS-pätkillä voi piilottaa halutut kohteet:

```
/* Piilota Taattavien maksut -välilehti */
#guarantees_finesandcharges-tab { display: none; }

/* Piilota taattavien maksut asiakassivun taattavat-listasta */
#pat_moremember li.guarantees-fines { display: none; }
```

Jos joissain kimpoissa ei näitä haluta piilottaa, niin sitten tulee miettiä, että millä korjataan näkymä todenmukaiseksi. Muutetaanko tekstejä kuvaamaan että näkyvät maksut on julkisoikeudellisia vai halutaanko molemmat maksut näkyviin.

Emmi näemmä ehtikin ensin jo vastaamaan. :)
Onkohan meillä kimppoja, joissa tämä pelkkä piilotus ei riitä?

**Comment by AnneliO** [comment]
Nuo aloituksessa mainitut rimpsut piilottavat Tiedot-sivulta nämä rivit:

![kuva](https://github.com/KohaSuomi/Koha-23x/assets/33121325/24f209c4-9670-41e9-a170-fae47f49db19)

Niiden ei pitäisi piilottaa varsinaisesti mitään maksuja (ellei vahingossa niin tee). Mutta noilla Emmin ja Kassun rimpsuilla sekin tosiaan onnistuu. :)

**Comment by pirliis** [comment]
OUTIssa halutaan näkyviin taattavan maksut takaajan tiedoissa. Olisiko mahdollista saada takaajan Tiedot-sivulle, jossa taattavan maksu näkyvät, vaikka samanlaisen tekstin kuin on varsinaisesti asiakkaan tiedoissa maksuista, jotta siinä näkyy myös maksujen yhteissumma?

Eli nyt takaajan tiedoissa näkyy taattavan maksut näin:
![image](https://github.com/KohaSuomi/Koha-23x/assets/98814860/256f4720-698b-41a8-b35b-f3599ecc8673)

Voisiko tekstin muuttaa näin:
"Asiakkaan taattavalla on lainauskieltoon vaikuttavia maksuja €5.00. Yhteensä (sis. maksut, jotka eivät vaikuta lainauskieltoon): €6.00.

Muutosta ei tarvitse toteuttaa ennen versionvaihtoa, jos ei ehditä. Tai jos tekstimuutos on mahdoton toteuttaa, OUTI tyytyy nykyiseen tekstiin, vaikka se antaa vähän väärää tietoa. :)

**Comment by AnneliO** [comment]
> OUTIssa halutaan näkyviin taattavan maksut takaajan tiedoissa. Olisiko mahdollista saada takaajan Tiedot-sivulle, jossa taattavan maksu näkyvät, vaikka samanlaisen tekstin kuin on varsinaisesti asiakkaan tiedoissa maksuista, jotta siinä näkyy myös maksujen yhteissumma?
> 
> Eli nyt takaajan tiedoissa näkyy taattavan maksut näin: ![image](https://private-user-images.githubusercontent.com/98814860/323919902-256f4720-698b-41a8-b35b-f3599ecc8673.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MjMwMTAsIm5iZiI6MTcxMzUyMjcxMCwicGF0aCI6Ii85ODgxNDg2MC8zMjM5MTk5MDItMjU2ZjQ3MjAtNjk4Yi00MWE4LWIzNWItZjM1OTllY2M4NjczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDEwMzE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiMmE2ZWJlYzc4MDc0N2I1YjBmMjQxYjU5MWZhMzQ1ZWUwMDYxZDdmNTE2MWZjOWE2ZDYxYjNkMTZiZDVlYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KB8SIi48wsBFdoK-L0STInZ1UJ-k1T40A8b_7p36DRA)
> 
> Voisiko tekstin muuttaa näin: "Asiakkaan taattavalla on lainauskieltoon vaikuttavia maksuja €5.00. Yhteensä (sis. maksut, jotka eivät vaikuta lainauskieltoon): €6.00.
> 
> Muutosta ei tarvitse toteuttaa ennen versionvaihtoa, jos ei ehditä. Tai jos tekstimuutos on mahdoton toteuttaa, OUTI tyytyy nykyiseen tekstiin, vaikka se antaa vähän väärää tietoa. :)

Se toinen muutos vaati koodimuutoksia, joten pelkkä tekstimuutos käännöstiedostoihin ei taida tässäkään riittää. Teetkö tästä toiveesta ihan erillisen kehitysehdotuksen, jos pääkäyttäjäpalaverissa löytyy muitakin ajatusta kannattavia? :)

**Comment by atarnus** [comment]
Jos ei muuta tehdä, niin voi tuota tekstiä muokata vaikka rimpsulla sanomaan että nuo on lainauskieltoon vaikuttavia maksuja. Tällöin olisi ainakin se annettu tieto oikein, jos nyt jotain tietoa puuttuu.

Kannattaa huomioida siihen toiseen tikettiin myös se, että halutaanko korjata samalla tuo taattavan maksut -välilehti. Sekään ei näytä kaikkia maksuja eriteltynä.

![taattavan-maksut](https://github.com/KohaSuomi/Koha-23x/assets/63994411/4c6024ec-0dab-4f87-9520-873f19facefd)

**Comment by AnneliO** [comment]
Luulen, että koodimuutosta odotellessa voisi tuon  "Asiakkaan taattavalla on yhteensä maksuja €5.00." muuttaa po-tiedostoissakin muotoon "Asiakkaan taattavalla on lainauskieltoon vaikuttavia maksuja yhteensä €5.00.". Vastaava muutos sopi tieteellisille, joten en näe siihen estettä tässäkään tapauksessa. Siitäkin voisi tehdä erillisen tiketin, niin pysyy erilaiset muutokset paremmin hallinnassa. :)

**Comment by pirliis** [comment]
Okei. Teen siis kaksi erillistä tikettiä. :)

**Comment by ReettaSiili** [comment]
Piilotin Siilin nextillä taattavien maksut ja viestit. Toimii!

**Comment by Kati-Helle** [comment]
Välilehden nimeksi Taattavan maksut ?
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/300b2af7-6d30-47ce-a7c3-968b68ad5239)

**Comment by AnneliO** [comment]
> Välilehden nimeksi Taattavan maksut ? ![kuva](https://private-user-images.githubusercontent.com/99952449/324791236-300b2af7-6d30-47ce-a7c3-968b68ad5239.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4Njc2MDEsIm5iZiI6MTcxMzg2NzMwMSwicGF0aCI6Ii85OTk1MjQ0OS8zMjQ3OTEyMzYtMzAwYjJhZjctNmQzMC00N2NlLWE3YzMtOTY4YjY4YWQ1MjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDEwMTUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhNzQ1ZTUzMzY2ZjhlNWY5ZTAyYjAyNjI2MGIyNTM2ZjEzYjYwNGIyMTU1YzRmMGVlODMxOTY2YTkxNjBmMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TqkZFttY7fatYPUDBxTK-Z33FDlPknJmAKl7Ne7zhlk)

Teetkö tästä erillisen tiketin? :)

**Comment by AnneliO** [comment]
Dokumentoitava.

**Comment by pirliis** [comment]
Tämän tiketin muutosehdotuksista on tehty omat tiketit:
https://github.com/KohaSuomi/Koha-translations/issues/46
https://github.com/KohaSuomi/Koha/issues/1173
https://github.com/KohaSuomi/Koha-23x/issues/141

Suljen tämän tiketin.
