### ISSUE TITLE
Lainassa olevien niteiden lainaus automaatilla

### ISSUE THREAD

**Issue by iinaniemi** [KohaSuomi/Koha-23x#129]
### Kehitysehdotukseni

Toiveena olisi, että lainausautomaateilla voisi lainata jo lainassa olevaa aineistoa.

Tämä olisi hyödyllistä esimerkiksi aineistonostoja ajatellen. Nostossa oleva materiaali voisi olla lainassa henkilökunnan nostot-kortilla, mutta asiakas voisi lainata ne suoraan automaatilla tulematta tiskille.

Sovittiin pääkäyttäjäpalaverissa 26.9., että tästä tehdään tiketti.

Samaa asiaa koskeva yhteisön tiketti: [Allow check out of already checked out items through SIP](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=18317)

**Comment by lmstrand** [comment]
SIP-palvelimen tunnuskonfiguraatioon voi lisätä parametrin prevcheckout_block_checkout="0" jonka luulisi sallivan jo lainassa olevan materiaalin lainauksen toiselle asiakkaalle.

**Comment by lmstrand** [comment]
Tuo asetus koskeekin näköjään vain asiakkaan omia aikaisempia lainoja.

**Comment by ajrajala** [comment]
Iina huomasi, että tuohon yhteisön tikettiin oli juuri tuotu patch+testaussuunnitelma. Olisko tämä mahdollista ottaa Bugitoniin mukaan ja saada vaski-testille testattavaksi, jolloin meillä voitaisiin kokeilla toimiiko korjaus automaatin kanssa?

**Comment by AnneliO** [comment]
Siirsin tiketin Bugiton-tietovarantoon.

**Comment by AnneliO** [comment]
Tämän testaaminen vaatii meidän oman yhteisöversiotestin.

**Comment by iinaniemi** [comment]
Onkohan tämä ominaisuus mahdollista ottaa testiin nextillä? Tuolla yhteisötiketissä on oman ymmärrykseni mukaan ainakin pari ihmistä signoffannut tuon patchin.

**Comment by lmstrand** [comment]
Vein muutoksen nexteille testattavaksi. AllowItemsOnLoanCheckoutSIP -asetus siis pitää laittaa päälle ja kokeilla automaatilla sen toiminta. OUTIn ja Vaskin SIP-palvelimet on käynnistetty uusiksi uuden koodin kanssa.

**Comment by lmstrand** [comment]
Lisätty ksdev/ks-0043-K23-15-SIP2 -branchiin. Joutui tekemään muutoksia sysprefs.sql-osioon patchista, jotta istui branchiin. Meinasin jättää muutoksen pois ongelmien välttämiseksi, mutta jos niitä tulee niin tämä tiedoksi.

**Comment by ajrajala** [comment]
Testasin tätä, kun AllowItemsOnLoanCheckoutSIP = Allow pystyi toisella asiakkaalla lainassa olevan niteen lainaamaan automaatilla eri asiakkaalle. 👍

**Comment by ajrajala** [comment]
Mietin vielä, että sign-offaanko tuon yhteisön tiketin vain odotanko kuitenkin, että tätä on OUTIssakin testattu?

**Comment by ajrajala** [comment]
Sellainenkin kysymys vielä, että saadaanko tämä sippimuutos mukaan jo versiopäivityksen yhteydessä tuotantoon vai tuleeko vasta myöhemmin?

**Comment by lmstrand** [comment]
Versiopäivityksen yhteydessä tulee mukaan, kun kerta testauksetkin ovat menneet hyvin.

**Comment by ajrajala** [comment]
Vaskin tuotannossa on versiopäivityksen jälkeen testattu, että lainassa olevan niteen lainaaminen automaatilla onnistuu. Suljenko jo tiketin?

**Comment by lmstrand** [comment]
Sulje vaan.
