### ISSUE TITLE
 Palautuskehotusmaksun määrittely -  ksdev/ks-0023-K22-59-overdue-notice-fines 

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#13]
### Siirrettävä ominaisuus

Myöhästymisilmoitusten määrittely -sivulla voi määrittää asiakastyyppikohtaisesti, mikä summa asiakkaalta veloitetaan palautuskehotuksen lähettämisestä. Maksun voi määrittää erikseen 1.-3. ilmoitukselle.

Tämä on riippuvainen overdue_notices.pl cron jobista.

Maksukenttä lisätty:
![226812512-4bd89293-2b77-4ac6-a55a-9244b616de51](https://github.com/KohaSuomi/Koha-23x/assets/33121325/16040650-4900-480b-a367-c422d9f5c171)

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 20.11.2023: Siirretään

**Comment by ajrajala** [comment]
Testailin, että asetusten määrittely ja muuttaminen toimii ok. Oliko tarkoitus testata myös maksun muodostuminen? Tein tuossa yhdelle testiasiakkaalle lainan, josta pitäisi muodostua 1. muistutus ja maksu huomenna, mutta vaatiiko erikseen ajon päälle pistämisen?

**Comment by emta001** [comment]
> Testailin, että asetusten määrittely ja muuttaminen toimii ok. Oliko tarkoitus testata myös maksun muodostuminen? Tein tuossa yhdelle testiasiakkaalle lainan, josta pitäisi muodostua 1. muistutus ja maksu huomenna, mutta vaatiiko erikseen ajon päälle pistämisen?

Juu vaatii maksuajon päälle laittamista.

**Comment by emta001** [comment]
@ajrajala Kävin ajamassa fines-ajon vaski-nextille, millekäs näyttää?

**Comment by ajrajala** [comment]
Myöhästymismaksut on muodostuneet, mutta 1. palautuskehotus -viestiä tai maksua siitä ei ole syntynyt. Asiakkaan lainan eräpäivä on ollut 18.1. ja myöhästymisilmoitusten asetuksissa on määritetty viiveeksi 8, joten minun laskujen mukaan tänään olisi tosiaan pitänyt muodostua 1. palautuskehotus. 🤔

**Comment by AnneliO** [comment]
fines-ajo ei luo palautuskehotusmaksuja/kirjeitä vaan overdue_notices.pl :)

**Comment by emta001** [comment]
> fines-ajo ei luo palautuskehotusmaksuja/kirjeitä vaan overdue_notices.pl :)

No höh :D Ajetaanpa sekin ->

**Comment by emta001** [comment]
Nonnih, jospa se siitä x)

**Comment by ajrajala** [comment]
Kyl maar, nyt muodostui testiasiakkaalle oikea viesti ja oikea maksu.

**Comment by pknuuti** [comment]
Vaaran nextillä testattu asetusten muuttamista ja se toimii.

**Comment by ElinaUotila** [comment]
Asetuksia muutettu Kirkes-Nextillä ja lisätty yhdelle lapsi- ja yhdelle aikuisasiakkaalle lainoja, joista pitäisi muodostua palautuskehotukset/maksut huomenna.

**Comment by ElinaUotila** [comment]
Aikuisasiakkaalle on muodostunut palautuskehotus ja asetusten mukainen kahden euron maksu. Lapsiasiakkaalle on muodostunut palautuskehotus, mutta ei maksua. Molemmat siis toimivat niin kuin pitikin.

**Comment by pirliis** [comment]
OUTIssa 1. ja 2. palautuskehotus on muodostunut oikein kuin myös niistä tulevat maksut. Kaukolainakirjastolle on muodostunut palautuskehotus, mutta ei maksua, kuin on määritelty.

**Comment by emta001** [comment]
Tämä on siis kunnossa. Suljen tiketin.
