### ISSUE TITLE
[Kehitysehdotus] Asiakkaan lainatietoihin uusinta-sarakkeeseen oletuksena rasti myös tänään erääntyville

### ISSUE THREAD

**Issue by atarnus** [KohaSuomi/Koha-23x#131]
### Siirrettävä ominaisuus

Toteutetaan suoraan versioon 23. Tiketti Koha-repositoriossa.
[Koha#261](https://github.com/KohaSuomi/Koha/issues/261)

**Comment by atarnus** [comment]
Githubissa. Tuotava nexteille.

**Comment by MikkoLiimatainen** [comment]
Vaski-nextillä ruksi tulee tänään erääntyville ja myös päivämäärän boldaus toimii.

**Comment by pirliis** [comment]
Myös OUTIn nextillä uusinta-ruksi tulee tänään erääntyville ja päivämäärät ovat boldattu.

**Comment by Kati-Helle** [comment]
Samoin Hellessä: uusinta-vaihtoehto on valmiiksi valittuna tänään erääntyville lainoille ja eräpäivä-arvot on lihavoitu.

**Comment by pirliis** [comment]
OUTIn tuotannossa Uusi valitut niteet -toiminapainike muuttuu aktiiviseksi vasta sen jälkeen, kun Uusinta-sarakkeessa käy poistamassa tai lisäämässä ruksin, vaikka ruksi on valmiina jo myöhässä oleville ja tänään erääntyville lainoille.

**Comment by VaisanRo** [comment]
Kyytissä toimii myös samalla tavalla kuin Outissa.

**Comment by AnneliO** [comment]
Koha-tietovarannon tikettiin kirjasin tällaisen aiemmin: Olen testannut tuota [epäaktiivista nappia] ennen Kassun muutosta ja nappula ei ollut aktiivinen sitä ennenkään. Tästä ongelmasta löytyy [Bugzillasta tiketti 36060](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=36060). :)

**Comment by lmstrand** [comment]
Siirsin tämän ominaisuuden branchiin ksdev/ks-0155-K23-G1207-issues-renew-return-fixes. Jos branchin mukana tulleet muutokset toimivat testeillä, poistetaan tälle tehty branch ksdev/ks-0138-K23-131-autocheck-renew-for-loans-due-today.

**Comment by lmstrand** [comment]
Liittyy siis tiketin https://github.com/KohaSuomi/Koha/issues/1207 korjauksen tuontiin yhteisöstä.
