### ISSUE TITLE
mtype-indeksille oma fasetti, koska aineistotyypin 942c-kenttä poistettiin itype-indeksistä

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#132]
### Mikä vikana?

Tiketissä  [Nidetyyppien indeksointitarve #833](https://github.com/KohaSuomi/Koha/issues/833) eriytettiin nidetyypit ja aineistotyypit omiin indekseihinsä. Nidetyypit ovat nextteillä itype-indeksissä ja aineistotyypit mtype-indeksissä. Aiemmin itype-indeksissä oli  mäpättynä myös siis 942c-kentästä aineistotyyppi. Tiedonhaun faseteissa taas on Nidetyypit-fasetti, johon aiemmin tuli mukaan myös aineistotyypit, mutta mäppäysmuutoksen myötä siellä on vain nidetyypit. 

### Mitä pitäisi tapahtua

Fasetteihin tarvitaan oma Aineistotyypit-fasetti mtype-indeksistä.

**Comment by lmstrand** [comment]
Vaaditaan muutos mäppäystiedostoon (mtype fasetoitavaksi) ja jonkin verran koodimuutoksia.
Yhteisössä on tiketti https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=35138, Elasticsearch - manage facets jota voisi kokeilla, jotta fasettien säätäminen onnistuisi virkailijan tekemänä auktorisoitujen arvojen kautta. Jos joutuu tekemään koodimuutoksia, niin sama kai sitten lisätä laajemmin toiminnallisuutta tuohon fasettien määrittelemiseksi. Kokeilen ainakin tuota yhteisömuutosta ratkaisuksi.

**Comment by lmstrand** [comment]
Branchissa ksdev/ks-0142-K23-132-facet-for-mtype. Viety testattavaksi nexteille.

**Comment by Kati-Helle** [comment]
Helle-nextissä aineistotyyppi-fasetit toimivat. Fasettinäkymää

![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/ea7b310d-1239-44fc-af79-da96af855e0b)

**Comment by lmstrand** [comment]
Ps. Hakukoneasetuksista voi siirtää fasettien sijaintia/järjestystä. Oletuksena päätyy viimeiseksi.

**Comment by Kati-Helle** [comment]
Kiitti vinkistä :)
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/df8687e8-1038-4e1a-891c-a0d26b0c63d3)

**Comment by lmstrand** [comment]
Fasetti muutettu käyttämään aineistotyypin kuvausta koodin sijaan. Muutos viety nexteille.

**Comment by Kati-Helle** [comment]
Helle-nextissä aineistotyypin kuvaus nyt näkyvillä
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/9cb6299e-8cd7-4f9a-b94b-08a0fada6591)

**Comment by AnneliO** [comment]
outi-nextillä testattuna ja Record-level item type -fasetti näkyy, arvot ovat kuvauksen mukaisia ja fasetilla rajaaminen toimii.

Fasetin otsikolle pitänee tehdä vielä käännös, mutta odotellaan ensin muiden Koha-Suomen muutosten valmistumista ennen kuin tehdään oma po-tiedosto.

**Comment by MikkoLiimatainen** [comment]
Tein tämän tiketin muutokset hakukoneen asetuksiin tuotantoon, mutta sehän vaatiikin taas uudelleenindeksoinnin.

**Comment by AnneliO** [comment]
Tuotannoissa oli käytössä väärä mäppäystiedosto, joten indeksoinnit joudutaan tekemään uudelleen. Pitää tarkistaa, että muutos on mukana oikeassa tiedostossa.

**Comment by AnneliO** [comment]
Aineistotyyppi-fasetti tuotannossa. Suljen tiketin.
