### ISSUE TITLE
Varauksen vanhenemispäivän muutos ei tallennu

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#133]
### Mikä vikana?

Jos yrittää varausjonossa muuttaa varauksen vanhenemispäivää, niin muutos ei tallennu. Päivän saa valittua, mutta se ei tallennu itsestään (kuten noutopaikka), eikä Päivitä varaukset -nappia painamalla. Nappi tuntuu kuin se ei tekisi mitään painettaessa.

Päivämäärä muuttuu tosiaan valinnan jälkeen, mutta jos käy toisella välilehdellä ja palaa Varaukset-sivulle, entinen päivämäärä on jälleen näkyvillä.

Valinnan jälkeen:
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/33121325/508b2071-1aad-4177-8b58-d9d5816a5822)

Muualla käynnin jälkeen päivämäärä palautunut alkuperäiseksi:
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/33121325/4da25c40-2cd3-4e4a-863b-de3a603e7fb1)

**Comment by ghost** [comment]
Testattu sen verran että tallentuu tietokantaan kun lataa sivun uudelleen tai esim. peruuttaa jonkin toisen varauksen Cancel selected -napista, mutta Päivitä varaukset -napista ei tosiaan tapahdu mitään.

**Comment by ghost** [comment]
Korjaus tulossa seuraavassa buildissä.

**Comment by AnneliO** [comment]
Emmi teki tänään buildin, joten testasin outi-nextillä. Varauksen viimeinen voimassaolopäivä tallentuu nyt samantien. Muutkin sivun toiminnot tuntuisi edelleen toimivan, kuten pitää.

**Comment by Kati-Helle** [comment]
Helle-nextissä tietueen varausjonossa olevan varauksen Vanhenee-kentän arvon muutos toimii. Testasin sekä noudettavan varauksen että voimassa olevan varauksen Vanhenee-kenttäarvon muuttaen. Noudettavan varauksen muutettu vanhenemispäivä muuttui myös asiakkaan varaustiedoissa ko. varaukselle.

**Comment by MikkoLiimatainen** [comment]
Vanhenee-kentän muutos päivittyy heti muutettaessa tärppäämättömille, kuljetettaville ja noudettaville varauksille. Toimii.

**Comment by ghost** [comment]
Testattu, suljen tiketin.
