### ISSUE TITLE
OUTI nextillä klikattu Vie/Tuo-nappi vie nextillä käsitellyn tietueen myös OUTIn tuotantoon

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha-23x#136]
### Mikä vikana?

OUTI nextillä klikattu Vie/Tuo (Tätiin) -nappi vie nextillä käsitellyn tietueen myös OUTIn tuotantoon.
 
Esim. tuotannon https://outi.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2318885&searchid=scs_1713178366080 -tietueen  osakohteiden "päälle" on tallentunut nextin tietueet:
https://outi-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2339938 (tämä tuotannossa nyt myös tuplana)
https://outi-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2339936&found1=1
https://outi-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2339946&found1=1
 
Onko Täti yhtäaikaa yhteydessä sekä nextiin että tuotantoon?

**Comment by johannaraisa** [comment]
Outille laitettiin se tuotantokanta ja varmaan ne säädöt on sen mukaiset. Otan tämän pois päältä, koska tuo tulee vaihtumaan kuitenkin siihen uuteen Melinda vientiin jota testataan testin puolella.
