### ISSUE TITLE
Ennakkovarattavissa-valinta piiloon Niteet-sivulta

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha-23x#137]
### Mikä vikana?

OUTIssa ei oteta ainakaan vielä käyttöön uutta Ennakkovarattavissa-toimintoa. Vosiko saada jonkin rimpsun, jolla Ennakkovarattavissa-valinnan saisi piiloon Niteet-sivulta?
![image](https://github.com/KohaSuomi/Koha-23x/assets/98814860/03050423-7aa7-4e85-8ea4-27b2763d89a5)

**Comment by AnneliO** [comment]
Tällä tuntuis menevän piiloon. Suosittelen testaamaan, ettei mene muutakin piiloon. :)

```
/* Piilota Ennakkovarattavissa-kohta Niteet-sivulla */
body#catalog_moredetail.catalog div.col-sm-10.col-sm-push-2 li:nth-child(2) { display: none; }
```

**Comment by pknuuti** [comment]
Missä tuollainen näkymä on? En löydä Vaaran nextiltä.

**Comment by pknuuti** [comment]
Vaarassa asetukset  LocalHoldsPriority, LocalHoldsPriorityPatronControl ja LocalHoldsPriorityItemControl ovat "pois päältä" eli ei priorisoida, joten meillä joutaisi koko Sija jonossa piilottaa. Liittyykö tuo ennakkovarattavissa vain paikallisiin varauksiin?

**Comment by pirliis** [comment]
> Tällä tuntuis menevän piiloon. Suosittelen testaamaan, ettei mene muutakin piiloon. :)
> 
> ```
> /* Piilota Ennakkovarattavissa-kohta Niteet-sivulla */
> body#catalog_moredetail.catalog div.col-sm-10.col-sm-push-2 li:nth-child(2) { display: none; }
> ```

Rimpsu piilotti Ennakkovarattavissa-valikon, mutta se piilotti sivulta myös nimeketiedoista ISBN:n, Nidetiedot-kohdasta Nidetyyppi-kohdan, Tilat-tiedoista Lainaustila-tiedon ja Historia-tiedoista Yhteensä lainassa -kohdan. Eli näyttäisi, että kaikista osioista toisen "tietorivin".

**Comment by AnneliO** [comment]
> > Tällä tuntuis menevän piiloon. Suosittelen testaamaan, ettei mene muutakin piiloon. :)
> > ```
> > /* Piilota Ennakkovarattavissa-kohta Niteet-sivulla */
> > body#catalog_moredetail.catalog div.col-sm-10.col-sm-push-2 li:nth-child(2) { display: none; }
> > ```
> 
> Rimpsu piilotti Ennakkovarattavissa-valikon, mutta se piilotti sivulta myös nimeketiedoista ISBN:n, Nidetiedot-kohdasta Nidetyyppi-kohdan, Tilat-tiedoista Lainaustila-tiedon ja Historia-tiedoista Yhteensä lainassa -kohdan. Eli näyttäisi, että kaikista osioista toisen "tietorivin".

Jei, mietitäänpä siis uudelleen.

**Comment by AnneliO** [comment]
Mien saa piiloon, joten pyysin Kassua katsomaan. :)

**Comment by atarnus** [comment]
Tämä piilottaa sen koko Sija jonossa-osion:

`body#catalog_moredetail div.listgroup:nth-child(3) { display: none; }`

Tämä pelkästään ennakkovarattavissa-kohdan:

`body#catalog_moredetail div.listgroup:nth-child(3) li:nth-child(2) { display: none; }`

Olettaen nyt, että nämä elementit ovat sitten kaikilla yhdenmukaisia :)

**Comment by pknuuti** [comment]
Kiitos atarnus, piilotus onnistui Vaaran nextillä enkä huomannut, että olisi mitään väärää piilottunut.

**Comment by Kati-Helle** [comment]
Helle-nextissä rimpsut toimivat myös. Niteet-välilehdellä piiloutuivat vain rimpsuilla piiloon määritellyt.

**Comment by atarnus** [comment]
Pirli huomasi, että teoksen tiedon kohdalta meni myös tietoja piiloon, eli siis alla olevasta näkymästä:
![image](https://github.com/KohaSuomi/Koha-23x/assets/63994411/3b84d3a6-af9b-4734-a57a-884c1a07e2cc)

Riippuen siitä, montako otsikkoa tuossa on, niin nuo bibliotiedot tosiaan osuivat välillä myös tuohon kolmanteen lapseen, jonka rimpsu piilottaa.

Tämän pitäisi korjata ongelma:

```
/* Piilota Sija jonossa -kohta Niteet-sivulla */
body#catalog_moredetail div.page-section:not(:first-child) div.listgroup:nth-child(3) { display: none; }
```

Tai vaihtoehtoisesti:

```
/* Piilota Ennakkovarattavissa -kohta Niteet-sivulla */
body#catalog_moredetail div.page-section:not(:first-child) div.listgroup:nth-child(3) li:nth-child(2) { display: none; }
```

Tosiaan molempia rimpsuja ei tarvitse, nämä ovat toistensa vaihtoehtoja.

**Comment by Kati-Helle** [comment]
Kiitos, nyt Helle-nextissä Piilota sija... -rimpsu ei piilota tarpeettomasti tietoja.
Minulta olikin aiemmin jäänyt huomaamatta teoksen tieto-osion piiloutumiset, kun olin katsonut vain nidekohtaisia tietoja.

**Comment by atarnus** [comment]
Joidenkin teosten kohdalla ne menivät piiloon ja joidenkin ei, joten ei ihme ettei kaikille osunut. :)

On mahdollista, että tuo :not() ei toimi taas kaikilla selaimilla, joskin se ei ilmeisesti ole niin uusi kuin se :has, jonka kanssa esiintyi ongelmia. Mutta työstetään sitten uusi versio jos näin käy.

**Comment by emta001** [comment]
Tämä pitää vielä dokumentoida.

**Comment by AnneliO** [comment]
Dokumentoitu [IntranetUserCSS-wikiin tiedonhaun vapaaehtoisiin](https://github.com/KohaSuomi/Koha-23x/wiki/IntranetUserCSS#vapaaehtoiset-4).
