### ISSUE TITLE
Niteet kuljetettavana ja saatavana samaan aikaan perustiedot näytöllä

### ISSUE THREAD

**Issue by MikkoLiimatainen** [KohaSuomi/Koha-23x#138]
### Mikä vikana?

Tietueen perustiedot sivulla niteen tila näkyy sekä kuljetettavana, että saatavana yhtä aikaa.
![Saatavana ja kuljetettavana 2024-04-18 132942](https://github.com/KohaSuomi/Koha-23x/assets/98884651/02637550-e2e8-42f7-8d51-395d78f7c972)

Tiketti bugzillassa https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=35226

**Comment by ajrajala** [comment]
Tässä tiketissä ilmeisesti korjaus? https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=35934

**Comment by emta001** [comment]
Näemmä tuplatikettina tuo, Annin laittamassa vaikuttaisi olevan oikea korjaus.

**Comment by Kati-Helle** [comment]
Helle-nextin tietueen perustiedoissa kuljetettavalla niteellä näkyy nyt Tila-sarakkeessa tieto vain kuljetuksesta
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/6de1f2b0-03da-49c9-96a3-86614bc10661)

**Comment by ReettaSiili** [comment]
Siili-nextillä Kuljetettavana-tilainen nide ei ole (enää) Saatavana-tilassa, ainoastaan Kuljetettavana.

**Comment by emta001** [comment]
Toimii kuten pitääkin, suljen tiketin.
