### ISSUE TITLE
Raporttipyyntö

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha-23x#139]
Kohan versiossa 23.11 on uusi ominaisuus, että kaikki rajoitteet voi ohittaa lainaustilanteessa klikkaamalla nappia "Ohita rajoitus tilapäisesti" 
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/98805552/3556f718-a57f-41ee-b0e1-b68c6f980358)

Koska rajoituksen voi ohittaa ihan mille tahansa asiakastyypille ja tilanteissa, joissa tilapäinen rajoituksen ohitus ei ole suotavaa (esim. kadonnut kirjastokortti, vanhentunut tili), saisimmeko raportin, jolla saa haettua sellaiset tapaukset?

Raportin rajauksena aikaväli.
Tulokseen asiakastyyppi, mikä rajoite on ohitettu ja milloin. Virkaijatunnuksen ID, joka ohituksen on tehnyt ja asiakastunnuksen ID, jolle ohitus on tehty.

**Comment by AnneliO** [comment]
Tämä ei taida onnistua tuollaisenaan ainakaan vielä, koska ohitukset eivät lokitu. Mutta juuri eilen tuli vastaan yhteisön tiketti, jossa lisätään lokitus rajoitusten ohittamisesta. Lisäsimme sen [Bugittoman listalle](https://github.com/KohaSuomi/Bugiton/issues/52).

Ennen tuota muutosta pystynee lähinnä tarkistamaan, onko lainoja sellaisilla asiakastyypeillä, joille lainaaminen ei ole sallittua.

**Comment by atarnus** [comment]
Tässä simppeli haku issueista tietyillä categorycodeilla. Old_issuesia ei tähän lienee tarpeellista yhdistää.

```
SELECT b.borrowernumber, b.cardnumber, i.issue_id, i.issuer_id,
       i.itemnumber, i.issuedate, i.date_due, i.timestamp
  FROM borrowers b
       INNER JOIN issues i USING (borrowernumber)
 WHERE b.categorycode IN ('VIRKAILIJA', 'AUTOM', 'API')
```

Kunhan nuo logitukset saadaan kuntoon, niin tehdään sitten se raportti noista ohituksista.

**Comment by piiaseme** [comment]
Kassun tekemä raportti asiakastyyppien VIRKAILIJA, AUTOM ja API lainoista on nyt OUTIn nextillä ja tuotannossa. Nextillä testattu ja toimii hienosti.

**Comment by AnneliO** [comment]
Ohitusten lokitus on vielä todennäköisesti pitkässä kuusessa, joten palataan sen osalta asiaan, kun ominaisuus on saatu meidän Kohaan.

**Comment by AnneliO** [comment]
Voiko tämän tiketin sulkea? :)

**Comment by piiaseme** [comment]
Mietin juuri samaa aiemmin tänään :) Mielestäni voi, joten suljen tiketin.
