### ISSUE TITLE
UserJS checksumming - ksdev/ks-0024-KD-4343

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#14]
### Siirrettävä ominaisuus

UserJS checksumming on ominaisuus, joka laskee mm. IntranetUserJS-järjestelmäasetuksen sisällölle tarkistussumman. Tietoturvaominaisuus.

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 20.11.2023: Siirretään

**Comment by CodoDerDritte** [comment]
Tähän on yhdistetty myös #27 ja #58, koska kysymyksessa on sama Koha-Suomi spesifi laajennus Kohan auth:iin. Branch 23x:ssä on ksdev/ks-0024-K23-14-auth-extra.

**Comment by CodoDerDritte** [comment]
Testattu, toimii.
