### ISSUE TITLE
 Viestitaulun lukitus kaataa Kohan

### ISSUE THREAD

**Issue by johannaraisa** [KohaSuomi/Koha-23x#140]
### Siirrettävä ominaisuus

Siirretään tämä ominaisuus, yhteisössä ei ole tehty parannuksia tähän.
ksdev/ks-0134-bug-35734-message-queue-table-lock

**Comment by johannaraisa** [comment]
Tästä pitäisi testata, että lainaus ja palautus toimivat vielä.

**Comment by johannaraisa** [comment]
Mielellään sellaiselle asiakkaalle, jolle muodostuu ilmoitus lainauksesta tai palautuksesta.

**Comment by pknuuti** [comment]
Vaaran nextillä testattu yhdellä asiakkaalla, että lainaus ja palauttaminen onnistuu.

**Comment by MikkoLiimatainen** [comment]
Vaski-nextilläkin lainaus ja palautus testattu yhdellä asiakkaalla, jolle lähtee molemmat kuitit. Ei ongelmia.

**Comment by johannaraisa** [comment]
Oukki doukki, tämä siis kunnossa, suljen tämän.
