### ISSUE TITLE
Käännösmuutos uudelle asiakastiedon välilehdelle Taattavat maksut

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-23x#141]
### Mikä vikana?

Uusi ominaisuus 'Takaajan tiedoissa näkyy taattavan julkisoikeudelliset maksut' muodostaa mm. uuden välilehden asiakkaan tietoihin, kun ominaisuus toteutuu.

Saako välilehden nimeen muutoksen 
Taattavat maksut -> Taattavan maksut

![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/187ca615-d757-4f8b-b549-aa2ab021c68f)

**Comment by atarnus** [comment]
Mahdollisesti 'taattavien maksut'? Voi kuitenkin olla useampia.

**Comment by Kati-Helle** [comment]
Vastaavan lainoihin liittyvän välilehden nimi on Perheenjäsenen lainat
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/e09cf1bc-4345-4991-9b76-1606d406e31e)

Samantyylinen myös maksuihin?

**Comment by AnneliO** [comment]
Teksti on englanniksi "Guarantees' charges (%s)" eli Kassun ehdottama Taattavien maksut olisi oikeampi käännös.

Eli teen muutoksen

Guarantees' charges (%s)
Taattavat maksut (%s) -> Taattavien maksut (%s)

**Comment by AnneliO** [comment]
Perheenjäsenen lainat on englanniksi Relatives' checkouts (%s), mikä kääntyisi oikeasti Perheenjäsenten lainat (%s). Vaikka tuntuisi loogiselta kääntää tuokin muotoon Taattavien lainat, niin se ei käy, koska välilehdellä näkyy oikeasti perheenjäsenten lainat. Eli jos vaikka samalla takaajalla on usemapi taattava, näkyy lasten tiedoissa Perhenjäsenten lainat -välilehdellä sekä takaajan että sisarusten lainat.

Korjaan tuon välilehden otsikon oikeaan monikkomuotoon.

Relatives' checkouts (%s)
Perheenjäsenen lainat (%s) -> Perheenjäsenten lainat (%s)

**Comment by AnneliO** [comment]
Muutokset viety Koha-transaltions-tietovarantoon ja yhteisön Weblateen. Tulee näkyviin, kun seuraavan kerran tehdään build.

**Comment by Kati-Helle** [comment]
Kenties joskus lainojen välilehden nimenä voisi olla Taattavien/Takaajien lainat ?
Sopisi paremmin Holhottava aikuinen -asiakastyypille.

**Comment by AnneliO** [comment]
> Kenties joskus lainojen välilehden nimenä voisi olla Taattavien/Takaajien lainat ? Sopisi paremmin Holhottava aikuinen -asiakastyypille.

Tuossa pitäisi minusta sitten jo alkuperäinen teksti muuttaa. Jos haluat, niin tee siitä tiketti yhteisöön. :)

**Comment by AnneliO** [comment]
Tämä muutos on jo tuotannossa, joten suljen tiketin.
