### ISSUE TITLE
Kyyti: Reklamaatiot-välilehden piilottaminen asiakastiedoista

### ISSUE THREAD

**Issue by Tuomas-Kyyti** [KohaSuomi/Koha-23x#142]
### Tukipyyntö

Kyytiin on tekeillä muutama nidepaketti. Kun nidepakettiasetukset laittaa päälle, tulee Nextillä näkyviin kaikille asiakkaille reklamaatiot-välilehdehti. Nykyisessä versiossa ei tule. Koska nidepakettien käyttö on hyvin vähäistä, näkyy uusi välilehti turhaan kaikilla asiakkailla. Saisiko välilehden piiloon jollain IntranetUser-rimpsulla? Koskee asiakastietojen lainus- ja tiedot-näkymiä.

Koskee Kohan versiota 23.11

### Jotain muuta?

![reklamaatiot](https://github.com/KohaSuomi/Koha/assets/99244794/924c9629-c8e3-4b3e-8d79-fbdca1c6bcde)

**Comment by emta001** [comment]
Koskee tulevaa versiota, siirrän tämän Versionvaihto-repoon.

**Comment by emta001** [comment]
Tällä menee piiloon:

```
/* Piilota Reklamaatiot-välilehti asiakkaan Tiedot-sivulta*/
a#return-claims-tab { display:none; }
```

**Comment by Tuomas-Kyyti** [comment]
Kiitos, toimii.

**Comment by AnneliO** [comment]
Rimpsu lisätty myös [IntranetUserCSS-wikiin Asiakkaat-osion vapaaehtoisiin](https://github.com/KohaSuomi/Koha-23x/wiki/IntranetUserCSS#vapaaehtoiset).
