### ISSUE TITLE
Lumme: varausviestien jäädytys ti 7.5.

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha-23x#143]
Lumme-kirjastot ovat kiinni myös ti 7.5. ja tällöin tehdään uuden Koha-version testausta, palautuksia, varausten noutoa, yms. Varausten noutoviestit olisi hyvä jäädyttää myös tiistaina, jotta asiakkaat eivät lähde turhaan kirjastoon. Viestit voivat lähteä normaalisti ke 8.5.

**Comment by AnneliO** [comment]
Tähän riittää, kun viestitys käynnistetään vasta 8.5.2024. Eli viestit kertyvät kyllä viestijonoon, mutta ne lähetetään eteenpäin vasta keskiviikkona.

**Comment by AnneliO** [comment]
Asiasana: asiakasviestinnän käynnistäminen

**Comment by AnneliO** [comment]
Käynnistetty
