### ISSUE TITLE
Vaara: Noutoilmoitusten viivästäminen

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha-23x#145]
### Tukipyyntö

Vaara-kirjastojen kaikki kirjastot ovat kiinni versionvaihtopäivinä 6.-7.5. eli jos/kun virkailijat käsittelevät palautuksia, niiden mahdolliset noutoilmoitukset saisivat lähteä vasta 8.5.

**Comment by pirliis** [comment]
OUTIssa on ohjeistettu, että aineistoja saa alkaa käsittelemään vasta sen jälkeen, kun kirjastot on avattu 7.5.

**Comment by AnneliO** [comment]
Asiasana: asiakasviestinnän käynnistäminen

**Comment by AnneliO** [comment]
Käynnistetty
