### ISSUE TITLE
Vahvista poisto-poppari ei toimi oikein, kun poistaa varausta tietueen varausjonosta

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha-23x#146]
### Mikä vikana?

Kun poistaa varauksen punaista roskakori-kuvaketta käyttäen, niin Vahvista poisto-poppari käväisee näytöllä noin 4 sekunnin ajan ja varaus poistuu. Vaikka klikkaa valintaa Peruuta, niin varaus silti poistuu.
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/98805552/b8edca5c-6af8-4a96-8200-aae2b157e7be)

### Mitä pitäisi tapahtua

Popparin tulisi odottaa, että virkailija kuittaa joko poiston tai peruu toiminnon ja, kun popparista klikkaa "Peruuta", niin varaus jää voimaan.

**Comment by ghost** [comment]
Toin takaisin vanhan poistonapin, jossa ei ole tätä ongelmaa.

**Comment by piiaseme** [comment]
Popparin toiminnot toimivat nyt oikein OUTI-nextillä.

**Comment by pknuuti** [comment]
Vaaran nextilläkin voi poistaa varauksen poistonapista ongelmitta.

**Comment by piiaseme** [comment]
Vanha poistonappi ja poppari toimivat oikein tuotannossa, joten suljen tiketin.
