### ISSUE TITLE
Sarakevalinnat eivät käyttäydy aina oikein niteiden eräpoistossa/erämuokkauksessa - ksdev/ks-0128-bug-32477-batch-mod-columns

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-23x#147]
### Siirrettävä ominaisuus

Niteiden eräpoistossa sarakkaiden näyttäminen/piilottaminen toimii oikein työkalua ensimmäisen kerran käyttäessä, mutta jos työkaluun siirtyy myöhemmin uudelleen, sarakkaiden näyttäminen/piilottaminen ei enää toimikaan oikein.

Alkuperäinen tiketti https://github.com/KohaSuomi/Koha/issues/769

**Comment by ajrajala** [comment]
Testasin tätä vaski-nextillä. Otin muutaman niteen erämuokkaukseen ja merkitsin joitakin sarakkeita pois näkyvistä. Avasin sitten niteiden erämuokkauksen toiselle välilehdelle ja vein sinne niteen. Uudella välilehdellä olevat sarakevalinnat ei täsmänneet valintoihin, jotka olin aiemmin tehnyt, mutta näkyvillä olevat sarakkeet kuitenkin täsmäsivät niihin valintoihin, jotka työkalussakin sillä hetkellä näkyivät. Eli sarakevalinnat käyttäytyivät sikäli ihan oikein.

Liittyykö nuo erot sarakevalinnoissa (kuvat alla) siihen, ettei muokkaukseen tuoduilla niteillä ole kaikkia sarakkeiden tietoja ja sarakevalintaa ei silloin näytetä ollenkaan? Onko tämä havainto ylipäätään asia, jolle voi tehdä mitään?

Alun perin tehdyt sarakevalinnat (niteiden viivakoodit NVask23051700436, NVask23051700437, NVask23051700438, NVask23051700439):
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/44638512/1913edbd-02f2-46d8-8228-3cdbbcadbaf0)

Työkalussa myöhemmin näkyvät sarakevalinnat (niteen viivakoodi 853N18235590):
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/44638512/7b3753a0-697d-479d-b5be-d20c4dd475e6)

**Comment by emta001** [comment]
Nyt kun kattelen omalla testillä, niin tuolla tosiaan on valittavana sarake "Ei lainattavissa" jota ei noissa Annin esimerkeissä näy. Myöskään ei näy esim. "Luokitus" saraketta.

**Comment by pirliis** [comment]
OUTIssa näyttäisi näkyvillä olevat sarakevalinnat toimivan myös oikein, mutta Varaukset-sarake ei ole valittavana, vaikka niteeseen kohdistuu varaus.


![Image](https://github.com/KohaSuomi/Koha-23x/assets/98814860/d10a9619-f804-4051-800d-502600407754)

**Comment by AnneliO** [comment]
Piilotukset toimivat oikein. Sarakkeiden oudosta käyttäytymisestä tehtävä oma tikettinsä.
