### ISSUE TITLE
Tarkan haun kielivalinnat, liittymän kielikuvaus ensin - ksdev/ks-0130-KD-G964-show-localized-language-description-first-on-advsearch

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-23x#148]
### Siirrettävä ominaisuus

Muutos, jolla kielikuvaukset järjestetään niin, että virkailijaliittymän kielivalinnan mukainen kuvaus näytetään ensin (jos ei tietokannasta löydy käännöstä, näkyy oletuksena englanninkielinen kuvaus), jonka perässä lokaali kielikuvaus omalla kielellään esim. Saksa (Deutch) / Tyska (Deutch). Lista aakkostetaan js-rimpsulla.

Alkuperäinen tiketti https://github.com/KohaSuomi/Koha/issues/964

**Comment by ajrajala** [comment]
Vaski-nextillä näyttäisi olevan ok.

**Comment by Kati-Helle** [comment]
Helle-nextissä toimii.

**Comment by pirliis** [comment]
OUTIn nextilläkin näyttäisi olevan ok.

**Comment by AnneliO** [comment]
Toimii, suljen tiketin.
