### ISSUE TITLE
Rajaukseen käytetty fasettivalinta "Nykyinen paikka" säilyy, vaikka hakutulosnäytöllä tehdään uusi haku - ksdev/ks-0131-K22-667-selecting-facet-changes-library

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-23x#149]
### Siirrettävä ominaisuus

Hae tietokannasta -haku muistaa tarpeettomasti aiemmassa haussa käytetyn fasettirajauksen Nykyinen paikka, kun Haun tulokset -näytöllä tehdään uusi haku.

Alkuperäinen tiketti https://github.com/KohaSuomi/Koha/issues/667

**Comment by ElinaUotila** [comment]
Kirkes-Nextillä ei jäänyt nykyinen paikka -rajaus kummittelemaan uuteen hakuun. Mutta huomasin samalla, että meiltä puuttuu nextillä faseteista "rajaa emokohteisiin" ja "rajaa osakohteisiin", enkä osaa sanoa missä välissä ne on kadonneet/mistä ne sinne saa. Muistelen että olisin viime viikolla tuota rajausta käyttänyt, mutta voin olla väärässä.

**Comment by atarnus** [comment]
Tämä koodimuutos vaikuttaa tasan tarkkaan vain tuohon pudotusvalikkoon ja sen arvon vaihtumiseen. Jos ei jotain tosi kummallista bugia satu, niin mitään muuta ei pitäisi tapahtua. Anneli vinkkasi tuosta rajauksesta ohjeen:
https://github.com/KohaSuomi/Koha-22x/wiki/Uutta#savedsearchfilters-eli-r%C3%A4%C3%A4t%C3%A4l%C3%B6idyt-rajaukset
Saako tuolla toiminaan?

**Comment by ElinaUotila** [comment]
> Tämä koodimuutos vaikuttaa tasan tarkkaan vain tuohon pudotusvalikkoon ja sen arvon vaihtumiseen. Jos ei jotain tosi kummallista bugia satu, niin mitään muuta ei pitäisi tapahtua. Anneli vinkkasi tuosta rajauksesta ohjeen: https://github.com/KohaSuomi/Koha-22x/wiki/Uutta#savedsearchfilters-eli-r%C3%A4%C3%A4t%C3%A4l%C3%B6idyt-rajaukset Saako tuolla toiminaan?

Kiitos, sain toimimaan. Ja pahoittelut tiketin viemisestä sivuraiteille! Itse testattava ominaisuus siis ainakin toimii meillä.

**Comment by atarnus** [comment]
> Kiitos, sain toimimaan. Ja pahoittelut tiketin viemisestä sivuraiteille! Itse testattava ominaisuus siis ainakin toimii meillä.

Eipäs mitään, aina oppii itsekin uutta.

**Comment by ajrajala** [comment]
Vaski-nextillä toimii, uudessa haussa ei säily "Nykyinen paikka" -rajaus mukana.

**Comment by Kati-Helle** [comment]
Helle-nextissä aiemmassa tiedonhaussa käytetty Nykyinen paikka -rajaus ei ole mukana, kun tekee uuden haun.

**Comment by AnneliO** [comment]
Toimii, suljen tiketin.
