### ISSUE TITLE
Lappi: Asiakasviestinnän käynnistäminen ke 8.5.2024

### ISSUE THREAD

**Issue by LeenaKinnunen** [KohaSuomi/Koha-23x#155]
### Mikä vikana?

Lapissa asiakasviestinnän saa käynnistää tiistaina 8.5.2024.

**Comment by emta001** [comment]
Niin, voiko tuon nyt tehdä 7.5. vai 8.5 :sweat_smile:

**Comment by LeenaKinnunen** [comment]
@emta001 olitpa nopea 😅 8.5. meille käyntiin.

**Comment by AnneliO** [comment]
Käynnistetty
