### ISSUE TITLE
Kyyti: Asiakasviestinnän käynnistäminen ti 7.5.

### ISSUE THREAD

**Issue by Tuomas-Kyyti** [KohaSuomi/Koha-23x#158]
### Siirrettävä ominaisuus

Asiakasviestinnän voi Kyytissä käynnistää tiistaina 7.5. klo 12 jälkeen.

**Comment by emta001** [comment]
Kyytissäkin viestit kulkevat ok, mutta lokeille tallentuu seuraavaa varoitusta:

>DBIx::Class::Storage::DBI::select_single(): Query returned more than one row.  SQL that returns multiple rows is DEPRECATED for ->find and ->single at /home/koha/Koha/Koha/Objects.pm line 96

Tutkaillaan vielä kuinka tuosta pääsisi eroon.

**Comment by emta001** [comment]
> Kyytissäkin viestit kulkevat ok, mutta lokeille tallentuu seuraavaa varoitusta:
> 
> > DBIx::Class::Storage::DBI::select_single(): Query returned more than one row.  SQL that returns multiple rows is DEPRECATED for ->find and ->single at /home/koha/Koha/Koha/Objects.pm line 96
> 
> Tutkaillaan vielä kuinka tuosta pääsisi eroon.

Tämä johtunee siitä, että Arena Driver-liitännäinen haluaa päättää lähettävän kirjaston sähköpostin perusteella. Koska Kyytissä on nyt kaikissa kirjastoissa sama sähköposti, liitännäinen saa hakutulokseksi useamman kuin yhden tuloksen ja lokille kertyy yllä olevia varoituksia. Tätä ei valitettavasti kyetä korjaamaan, koska lähettävän kirjaston selvittämiseen ei ole muuta vaihtoehtoa kuin käyttää message_queue-taulun from_address-saraketta. Hyvin sama ongelma siis kyseessä kuin PDF-tulostus liitännäisessä. Tiketin voi sulkea.

**Comment by AnneliO** [comment]
Käynnistetty
