### ISSUE TITLE
Toiminto piiloon: "Vie tänään palautettujen lainojen viivakoodit tiedostoon"

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha-23x#160]
Asiakkaan Tiedot-sivulla Muita toimintoja -alaspudotusvalikossa on toiminto "Vie tänään palautettujen lainojen viivakoodit tiedostoon". OUTIssa haluttaisiin tämä toiminto piiloon. Voisiko tehdä vaikka CSS-rimpsun piilotukseen?

**Comment by atarnus** [comment]
Tämä liittyy asetukseen intranetreadinghistory. Jos tuo ei ole päällä, niin valintaa ei tule näkyviin. En ole perillä, että mitä kaikkea asetus koskee, eli jos sen tarvitsee olla päällä jossakin muualla, niin annetaan sitten olla päällä ja piilotetaan tuo CSS:llä.

Samasta valikosta on jo piilotettu lapsen päivittäminen aikuiseksi seuraavalla koodilla:
```
/* Piilota asiakastietojen Muita toimintoja -valikosta Päivitä lapsi aikuiseksi */ 
body#pat_moremember.pat a#updatechild { display: none; }
```

Lisäisin kohdan tuohon ja muokkaisin tuotakin vähäsen. Yo. koodissa on määritelty tuo valinta piilotetuksi vain kun ollaan asiakkaan Tiedot-sivulla. Lainaus-, Maksut- ym. sivuilla valinta ilmestyy taas tuonne palkin pudotusvalikkoon. Katsoin ettei noita ID-tunnuksia olisi muualla käytössä, mutta lisätään nyt vielä sinne tuo toolbar, että ei heti piilota kaikkialta jos jossain muualla käytetään samannimistä ID:tä.

```
/* Piilota asiakastietojen Muita toimintoja -valikosta 'Päivitä lapsi aikuiseksi' ja 'Vie tänään palautettujen lainojen viivakoodit tiedostoon' */ 
div#toolbar a#updatechild { display: none; }
div#toolbar a#exportcheckins { display: none; }
```

**Comment by AnneliO** [comment]
intranetreadinghistory-asetus ei saisi olla päällä, koska se sallii pääsyn asiakkaan lainahistoriaan. Olisikohan se jäänyt minulla vahingossa päälle outi-nextillä. Otin sen nyt pois päältä, ettei se kopioidu tuotantoon.

**Comment by pirliis** [comment]
> Tämä liittyy asetukseen intranetreadinghistory. Jos tuo ei ole päällä, niin valintaa ei tule näkyviin. En ole perillä, että mitä kaikkea asetus koskee, eli jos sen tarvitsee olla päällä jossakin muualla, niin annetaan sitten olla päällä ja piilotetaan tuo CSS:llä.
> 
> Samasta valikosta on jo piilotettu lapsen päivittäminen aikuiseksi seuraavalla koodilla:
> 
> ```
> /* Piilota asiakastietojen Muita toimintoja -valikosta Päivitä lapsi aikuiseksi */ 
> body#pat_moremember.pat a#updatechild { display: none; }
> ```
> 
> Lisäisin kohdan tuohon ja muokkaisin tuotakin vähäsen. Yo. koodissa on määritelty tuo valinta piilotetuksi vain kun ollaan asiakkaan Tiedot-sivulla. Lainaus-, Maksut- ym. sivuilla valinta ilmestyy taas tuonne palkin pudotusvalikkoon. Katsoin ettei noita ID-tunnuksia olisi muualla käytössä, mutta lisätään nyt vielä sinne tuo toolbar, että ei heti piilota kaikkialta jos jossain muualla käytetään samannimistä ID:tä.
> 
> ```
> /* Piilota asiakastietojen Muita toimintoja -valikosta 'Päivitä lapsi aikuiseksi' ja 'Vie tänään palautettujen lainojen viivakoodit tiedostoon' */ 
> div#toolbar a#updatechild { display: none; }
> div#toolbar a#exportcheckins { display: none; }
> ```

Saisiko Lainaus- ja Maksut-sivulta "Päivitä lapsi aikuiseksi" toiminnon piiloon kuin on Tiedot-sivulla?

**Comment by atarnus** [comment]
Tässä tämä päivitys vain lapsen päivitykselle, niin että pitäisi toimia joka sivulla:

```
/* Piilota asiakastietojen Muita toimintoja -valikosta 'Päivitä lapsi aikuiseksi' */ 
div#toolbar a#updatechild { display: none; }
```

**Comment by pirliis** [comment]
> Tässä tämä päivitys vain lapsen päivitykselle, niin että pitäisi toimia joka sivulla:
> 
> ```
> /* Piilota asiakastietojen Muita toimintoja -valikosta 'Päivitä lapsi aikuiseksi' */ 
> div#toolbar a#updatechild { display: none; }
> ```

Kiitos! Rimpsu toimii. :)
