### ISSUE TITLE
Lappi : Korjaus IntranetuserJS-sääntöön

### ISSUE THREAD

**Issue by LeenaKinnunen** [KohaSuomi/Koha-23x#166]
### Mikä vikana?

Lapissa on jäänyt Avaa Finnassa -IntranetuserJS-sääntöön linkki OUTI:n Finnaan. Korjaatko ko. koodissa olevan osoitteen seuraavasti: 

https://outi.finna.fi/Record/outi
-> https://lapinkirjasto.finna.fi/Record/lapinkirjasto.

### Mitä pitäisi tapahtua

Avaa Finnassa-linkki teosnäkymässä vie Lapin kirjaston Finnaan.

**Comment by emta001** [comment]
Rimpsu korjattu.

En tuossa elementsissä hoksannut äsken sanoa, mutta näissä on rimpsujen päivityksessä tuotantoon on ollut työnjako niin, että pääkäyttäjät ilmottaa korjaus tarpeesta ja sopii kehittäjän kanssa milloin se muutos tehdään. Sitten kehittäjä käy laittamassa checksummin päälle ja pääkäyttäjä tekee lisäykset/korjaukset/poistot. Sitten pääkäyttäjä ilmoittaa, kun homma on valmis ja kehittäjä käy laittamassa checksummin takaisin päälle.

**Comment by LeenaKinnunen** [comment]
Kiitos Emmi! Yritän muistaa tämän jatkossa.
