### ISSUE TITLE
Asiakaslistat-välilehden piilotus

### ISSUE THREAD

**Issue by PiaKusmin** [KohaSuomi/Koha-23x#167]
### Mikä vikana?

Tällä CSS koodilla saa piilotettua asiakastiedoista asiakaslistat-välilehden.

/* Asiakaslistat välilehden piilotus */
a#pat_lists-tab { display:none; }

**Comment by AnneliO** [comment]
Kiitos, tämä nyt lisätty 23xx-repon wikiin. Sieltä pitää vielä jossain vaiheessa päivittää varsinaiseen IntranetUserCSS-kirjastoon kaikki.
