### ISSUE TITLE
Lainaus ja palautus-valikon piilottaminen

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha-23x#168]
### Mikä vikana?

Saisiko piilotettua Lainaus ja palautus -valikko sivun vasemmasta reunasta. Valikko avautuu https://vaara.koha-suomi.fi/cgi-bin/koha/circ/circulation-home.pl sivulta klikkaamalla toimintojen linkkejä.
![2023kuvat 402](https://github.com/KohaSuomi/Koha-23x/assets/73887264/ea048116-8a31-4f2f-9693-0cf1d76dc1ff)

**Comment by AnneliO** [comment]
Jos haluatte koko valikon piiloon, niin se onnistuu CircSidebar-järjestelmäasetuksella. Mutta jos haluatte vain sen Uusinta-kohdan, kuten oli palaverissa puhetta, niin pitää tutkia, onnistuisiko se css:llä. :)

**Comment by pknuuti** [comment]
Kiitos, tuo riittää. Suljen tiketin.

**Comment by IrinaHalminen** [comment]
Onko CSS-piilotus vaikea? Asiakaspalvelussa on totuttu käyttämään valikkoa siirtymisiin, uusinnalle ei ole kuitenkaan tarvetta.

**Comment by AnneliO** [comment]
> Onko CSS-piilotus vaikea? Asiakaspalvelussa on totuttu käyttämään valikkoa siirtymisiin, uusinnalle ei ole kuitenkaan tarvetta.

Miepä katon.

**Comment by AnneliO** [comment]
Tämä tuntuisi piilottavan Uusinta-linkin. Kannattaa kuitenkin testata huolellisesti, että mikään muu ei mene muualla piiloon.

```
/* Uusinta-linkin piilotus Lainaus ja palautus -osion vasemman reunan valikosta */
div#navmenulist a[href*="/cgi-bin/koha/circ/renew.pl"] { display: none; }
```

**Comment by IrinaHalminen** [comment]
Laitan tämän meille testille, @pknuuti & @auliran. Tutkitaan, hajoaako paikat. :)

**Comment by IrinaHalminen** [comment]
Olemme miettineet tätä valikon sisältöä. Meneekö liian hankalaksi, jos siitä poistaisi näkyviltä myös Myöhässä-otsikon alla olevat rivit sekä Varaukset-otsikon alta varausjonon?

**Comment by AnneliO** [comment]
Myöhässä otsikon -alaisille on piilotus olemassa: https://koha-suomi.fi/dokumentaatio/intranetusercss/#piilota-overduesmy%C3%B6h%C3%A4ss%C3%A4-otsikko--lainaus-ja-palautus--sivulta

Teetkö oman tiketin tuosta Varausjonon piilottamisesta? :)

**Comment by IrinaHalminen** [comment]
Kiitos, teen vähän myöhemmin tuosta Varausjonosta tiksun.

**Comment by IrinaHalminen** [comment]
Avaan uudelleen, kun tuo Myöhässä-otsikon piilotus koski nyt tässä tapauksessa Lainaus ja palautus -**sivuvalikkoa**. Lainaus ja palautus -sivulta ollaan se jo piilotettukin tuolla em. rimpsulla.

**Comment by atarnus** [comment]
Tässä olisi sivuvalikolle koko Myöhässä osion piilotus, ensin otsikko, joka on määritelty tosiaan taas tuolla järjestysnumerolla, eli jos otsikkojen järjestys muuttuu, niin saattaa joskus mennä sitten väärä otsikko piiloon. Linkit pystyi määrittelemään tarkemmin.

```
/* Piilota Myöhässä-osio Lainaus ja palautus -sivuvalikosta */
body.circ div#navmenulist h5:nth-of-type(4),
body.circ div#navmenulist a[href="/cgi-bin/koha/circ/overdue.pl"],
body.circ div#navmenulist a[href="/cgi-bin/koha/circ/branchoverdues.pl"] { display: none; }
```

**Comment by IrinaHalminen** [comment]
Kiitos, laitoin vielä testille tutkailtavaksi ja otetaan pienellä viiveellä tuotantoon. Pahoittelut, että vaivasin tuon valikon kanssa. Se on näppärä siirtymissä.

**Comment by AnneliO** [comment]
Kummatkin tiketissä mainitut rimpsut lisätty IntranetUserCSS-kirjastoon.
