### ISSUE TITLE
Signum- ja pääsanapluginit - ksdev/ks-0027-KD-4589

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#17]
### Siirrettävä ominaisuus

Signumeita ja pääsanoja varten on tehty monenlaisia liitännäisiä:

084a_mainheading_branch_loc_signum_builder.pl
084a_mainheading_branchloc_genre_signum_builder.pl
084a_mainheading_branchloc_signum_builder.pl
084a_mainheading_loc_signum_builder.pl
brancloc_084a_mainheading_signum_builder.pl
fi_JSON_084a_signum_builder_subfields.pl
fi_JSON_942khm.pl
fi_paakirjaus.pl
fi_paakirjaus_ohitusind_3merkkia.pl
fi_signumbuilder_942k_branchloc_942hm.pl
fi_signumbuilder_942k_loc_942hm.pl
fi_signumbuilder_942k_loc_ccode_942hm.pl
fi_signumbuilder_942khm_branch_loc.pl
fi_signumbuilder_942khm_branchloc.pl
fi_signumbuilder_942khm_branchloc_genre.pl
fi_signumbuilder_942khm_loc.pl
loc_084a_mainheading_signum_builder.pl
loc_ccode_084a_mainheading_signum_builder.pl
ykl_from_084a.pl

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 20.11.2023: Siirretään

**Comment by ajrajala** [comment]
Vaskissa käytössä plugari loc_084a_mainheading_signum_builder.pl, testattu nextillä että toimii.
Meillä myös NUOP-kuvailupohjassa käytössä plugari fi_signumbuilder_942k_loc_942hm.pl. Kuvailupohjaa tosin ei enää ilmeisesti uusilla tietueilla käytetä, joten en tiedä onko tuolla miten paljon enää tarvetta, mutta tuokin plugari siis kyllä toimii.

**Comment by Tuomas-Kyyti** [comment]
Kyytissä käytettävä 084a_mainheading_branch_loc_signum_builder.pl vaikuttaa toimivan.

**Comment by Kati-Helle** [comment]
Hellessä toimii oikein plugin 
loc_ccode_084a_mainheading_signum_builder.pl

**Comment by pknuuti** [comment]
Vaaran nextillä testattu plugin branchloc_084a_mainheading_signum_builder.pl toimivaksi.

**Comment by PiaKusmin** [comment]
Lapissa myös loc_ccode_084a_mainheading_signum_builder.pl ja todettu toimivaksi.

**Comment by emta001** [comment]
Testattu ja toimii. Suljen tiketin.

**Comment by atarnus** [comment]
Näitä muutettiin vähän, koska välilyöntejä poistava JS-rimpsu ei toiminut. Käytännössä poistettiin vain blur- ja fokus-funktiot, jotka eivät tehneet mitään, eli varsinaiseen signumin luontiin ei tuolla muutoksella ollutkaan mitään vaikutusta. Paitsi 084a_mainheading_branchloc_genre_signum_builder.p:n kohdalla, jossa oli typo yhden marc-kentän kohdalla. Tämäkin fiksattu.

Js-rimpsun tiketti: https://github.com/KohaSuomi/Koha-23x/issues/117
