### ISSUE TITLE
Varauksen poisto tietueen varausten kautta 

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-23x#171]
### Mikä vikana?

Olemassa olevan varauksen poisto tietueen Varaukset-välilehdellä: varauksen poiston jälkeen varaus ei poistu näytöltä, joten vaikuttaa siltä kuin varaus ei olisi poistunut. 

Voimassa olevan varauksen perumiseen 
valittuna peruttava varaus ja Peruuta varaus -painiketta klikataan
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/b5b1687b-7641-4883-80ec-aa6f502c3303)

Haluatko varmasti perua -vahvistus-popup
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/986da593-36a1-404e-93fb-39fc0a791ca0)

Vahvista poisto -painikkeen klikkaus ja varaus näyttäisi edelleen olevan voimassa (mutta ei ole)
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/2d34e31c-fe1c-4d14-b85b-45d6d8070beb)

Varaustieto häviää näkyvistä näytön päivittämällä.

**Comment by Kati-Helle** [comment]
Myös ainakin noudettavan varauksen poisto käyttäytyy samoin.

**Comment by VaisanRo** [comment]
Kyytissä toimii myös samalla tavalla, mutta jos peruutta käyttäen peruuta painiketta, niin varaus poistuu näkyvistä ilman päivittämistä.
![Huomautus 2024-05-06 150516](https://github.com/KohaSuomi/Koha-23x/assets/129718041/0de3e7c1-fa9a-4336-947d-671174cf93bc)

**Comment by AnneliO** [comment]
Tännekin ylös se, mitä Matrixissa puhuttu. Eli kun käyttää Peruuta valitut -nappia, menee poistotyö Taustatöihin. Siitä ei kuitenkaan tule Koha-Suomen tekemien muutosten vuoksi ilmoitusta, jolloin käyttäjä ei tiedä sen menneen taustatöihin. Varaus poistuu taustalla ja kun sivun päivittää, päivittyy tieto myös sitten varausjono-sivulle.

Tämä ongelma huomattiin jo version 22.11-versionvaihdossa ja siitä on puhuttu tiketissä https://github.com/KohaSuomi/Koha-22x/issues/37

**Comment by AnneliO** [comment]
Tämän voinee sulkea?

**Comment by Kati-Helle** [comment]
Joo.
