### ISSUE TITLE
Kirkes: asiakastiedon suojaus -valinta ei tallennu

### ISSUE THREAD

**Issue by ElinaUotila** [KohaSuomi/Koha-23x#173]
### Mikä vikana?

Kirkesissä asiakastiedon muokkauksessa oleva Suojattu: kyllä-valinta ei tallennu tuotannossa, nextillä eikä testillä, vaan palaa tallentamisen jälkeen aina ei-valinnaksi. Kokeilin ottaa pois intranetuserjs- ja intranetusercss-rimpsut Kirkes-nextiltä, mutta tilanne ei muuttunut.

**Comment by emta001** [comment]
Hmm, tallennuksen yhteydessä protected arvo kyllä lähtee matkaan, mutta jostain syystä se ei tallennu kantaan.

**Comment by emta001** [comment]
Vielä oudompaa, arvon tallennus toimii miun testeillä.

EDIT. Tallentuu myös Vaaran testillä, eli Kirkeksellä on nyt jotain hassusti.

**Comment by emta001** [comment]
Tämä ei myöskään johdu CSS-rimpsuista.

**Comment by emta001** [comment]
Haa, selvisi! Asetuksessa BorrowerUnwantedField oli ruksittuna tuo kenttä "Protected/Suojattu". Se siis näkyy asiakkaan lisäys/muokkauslomakkeella, mutta sen vaihtaminen ei onnistu. Kun otti ruksin asetuksesta pois, niin rupes toimimaan.

**Comment by emta001** [comment]
Kyseessä on muuten ihan bugi, kenttien pitäis piilottua silloin kun ne on ruksittu BorrowerUnwantedField-asetuksessa. Pitänee tutkia löytyykö yhteisöstä tikettiä tai tehä semmonen. Sitten voidaan päättää korjataanko meillekin tuo vai kärsiikö ootella.

**Comment by ElinaUotila** [comment]
Apua. Mielestäni tuijotin niitä kenttiä moneen kertaa, mutta en siltikään tarpeeksi tarkkaan. Ja pähkäilin mielessäni, että eihän se sitten näkyisi, jos se olisi siellä piilotettu. Ja nyt tosiaan toimii. Kiitos, Emmi!
