### ISSUE TITLE
MARC-virheraportit eivät toimi

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha-23x#175]
### Mikä vikana?

OUTIssa MARC-virheraportit "Virheelliset tietueet" ja "Virhemäärät" antavat virheilmoituksen "Error 404".

**Comment by AnneliO** [comment]
Piti hetken miettiä, mitä nää on, mutta nehän on https://outi.koha-suomi.fi/marc_virheet.outiprod.html ja https://outi.koha-suomi.fi/marc_virhemaara.outiprod.txt

**Comment by paxed** [comment]
Uusi tuotanto luotiin nexteistä, joissa ei noita ollut, nyt ne on linkitetty.
