### ISSUE TITLE
Asiakkaan vanhoja lainoja ei voi uusia eikä palauttaa

### ISSUE THREAD

**Issue by helasann** [KohaSuomi/Koha-23x#176]
### Mikä vikana?

Asiakkaan 80513 (Lapsi, jolla ei ole takaajaa) erääntynyttä tai vanhempia 10.5. erääntyviä lainoja ei pysty uusimaan tai palauttamaan. Jos palauttaa niteen uudelleen, sen tila näyttää "ei lainassa", mutta asiakkaan tiedoissa laina näkyy edelleen. Palauttaminen antaa virheilmoituksen:

![kuva](https://github.com/KohaSuomi/Koha-23x/assets/111975210/9623fb1c-04e7-4b18-b4ae-572e8a3cd544)

### Mitä pitäisi tapahtua

Lainat voi uusia ja/tai palauttaa normaalisti.

### Kuinka toistaa ongelma/asia

4. Palauta esim. nide 245N06366480

**Comment by AnneliO** [comment]
Lari katseli, että lokeilla näkyy merkintöjä puuttuvasta huoltajatiedosta. Kokeiletteko lisätä tuolle asiakkaalle jonkin väliaikaisen huoltajan sitten palauttaa uudelleen niteen?

**Comment by helasann** [comment]
Kiitos, tämä auttoi! Testitakaajaa ei vaan saa poistettua.

**Comment by AnneliO** [comment]
Kun takaajatieto on pakollinen, niin sitä ei tosiaan sitten saa pois ennen kuin asiakkaalle lisätään oikea takaaja.
