### ISSUE TITLE
Vaara: Lisää asiakas / Muokkaa asiakasta -näkymien asettelu

### ISSUE THREAD

**Issue by IrinaHalminen** [KohaSuomi/Koha-23x#177]
### Mikä vikana?

[Asiakkaan lisäyksessä](https://vaara.koha-suomi.fi/cgi-bin/koha/members/memberentry.pl?op=add&categorycode=HENKILO)/muokkauksessa muutamien kenttien otsikoinnit jäävät kenttien alle ja sanat katkevat hassusti kesken:

![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99409279/ef7916c0-7877-4c89-8076-60de7ba459da)
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99409279/8af6706b-83aa-4bfa-9d31-370594c430a4)

Voisiko kaikkiin saada saman tasauksen kuin suurimmassa osassa eli:
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99409279/defd7799-58f8-49f4-b6cb-f7644046e64b)

**Comment by atarnus** [comment]
Tuolle labelille on määritelty tietty leveys ja ongelmia ilmenee kun sopivat leveydet on määritelty englannin perusteella (jossa yhdyssanat kirjoitetaan pääsääntöisesti erikseen). Muistelisin nähneeni tästä valitusta yhteisön puolella myös.

Pikainen "fiksi" tähän voisi olla heittää vaikka intranetuser.css:ään vähän lisää leveyttä tuolle labelille:

Yleisesti:
```
/* Levennä otsikkokenttiä */
fieldset.rows label { width: 13rem; }
```

Asiakkaan muokkaussivulla pelkästään:
```
/* Levennä otsikkokenttiä asiakkaan muokkauksessa */
body#pat_memberentrygen fieldset.rows label { width: 13rem; }
```

Oletuksena leveys on 10rem, kahden lisäys riitti mahduttamaan ainakin nuo huomautuskentät. Itse voi säätää tietysti haluamakseen.

**Comment by MikkoLiimatainen** [comment]
Tuosta yleisesti otsikkokenttiä leventävästä koodista on hyötyä myös raporteissa, joissa voi pidemmät sanat mennä kentän otsikossa päällekkäin kentän/pudotusvalikon kanssa raporttia ajaessa.

**Comment by IrinaHalminen** [comment]
Kiitos, tuo yleinen versio otettu käyttöön ja hyvältä vaikuttaa.

**Comment by AnneliO** [comment]
Rimpsut dokumentoitu [IntranetUserCSS-kirjastoon](https://koha-suomi.fi/dokumentaatio/intranetusercss/).
