### ISSUE TITLE
Tulosta ilmoituksia -liitännäisen linkki ei näy työkalujen työkaluliitännäisissä

### ISSUE THREAD

**Issue by ReettaSiili** [KohaSuomi/Koha-23x#178]
### Mikä vikana?

Linkki on aiemmin ollut työkaluissa, nyt ei ole enää.

### Mitä pitäisi tapahtua

Muidenkin kuin ylläpitäjän pitäisi päästä tulostamaan ilmoituksia.

**Comment by atarnus** [comment]
Voisiko tämäkin johtua tästä CSS:stä, jonka oli tarkoitus piilottaa intranetJS-plugareita valikosta? Kannattaa kommentoida tämä pois ja katsoa onko siellä linkkejä, joita tarvii piilottaa, ja fiksaa sitten oikean numerot tuohon.

```
/* Piilota Työkalut-sivulta linkit JS-liitännäisiin Työkaluliitännäiset-osiosta. Rimpsut piilottavat tietyn rivin, joten kun liitännäisiä tulee lisää, kopioi yksi riveistä ja muuta nth-child(1)-kohtaan sopiva rivinumemero. JS-liitännäiset pitäisi tulla peräkkäin, mutta testaamalla löytyy oikea numero. */
body#tools_tools-home.tools div.col-sm-6 li:nth-child(1) { display: none; }
body#tools_tools-home.tools div.col-sm-6 li:nth-child(2) { display: none; }
```

**Comment by ReettaSiili** [comment]
Tämähän se oli. Pienen säätämisen jälkeen sain Tulosta ilmoituksia -linkin näkyviin. Yksi piilotettava meillä vain olikin. Kiitos :) ja suljen tämän.
