### ISSUE TITLE
Lumme: uuden asiakkaan tallennus ei onnistu

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha-23x#179]
### Mikä vikana?

Kun Lumpeissa yrittää tallentaa uutta asiakastietoa ja painaa Tallenna-nappia, mitään ei tapahdu. Jo tallennettujen asiakastietojen muokkaus kuitenkin onnistuu.

### Mitä pitäisi tapahtua

Uuden asiakastiedon pitäisi tallentua normaalisti, kun painaa Tallenna-näppäintä.

### Kuinka toistaa ongelma/asia

1. Lähde lisäämään uutta asiakasta.
2. Täytä tiedot.
3. Paina Tallenna-nappia.
4. Asiakastieto ei tallennu.

**Comment by emta001** [comment]
Ilmeisesti userid-kenttä on piilotettu, mutta samaan aikaan pakollinen.
