### ISSUE TITLE
Hyllytarkenne - ksdev/ks-0030-K22-7-item-api-subloc 

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#18]
### Siirrettävä ominaisuus

API-endpointiin item.yaml lisätty asetusmuutos, joka mahdollistaa mm. hyllytarkenteellisten niteiden haun APIn kautta.

**Comment by emta001** [comment]
Tätä tuodessa kannattaa myös muuttaa atomicupdate filun pääte perlistä pl:ksi. Muuten se ei asennu uusiin kantoihin.

**Comment by emta001** [comment]
> Tätä tuodessa kannattaa myös muuttaa atomicupdate filun pääte perlistä pl:ksi. Muuten se ei asennu uusiin kantoihin.

Väärä tiketti, tämä onkin apille :D

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 20.11.2023: Siirrettävä. Kokeillaan viedä yhteisöön.

**Comment by emta001** [comment]
Testailin tätä omilla testeillä ja vaikuttaisi sille, että tätä muutosta ei tarvita. Testataan vielä nexteillä mitä tapahtuu, mutta jätetään ainakin tässä vaiheessa muutos tuomatta.

Niin ja tiketin kuvaus on hieman vinossa, tämä branch ei koske itse kantaan lisättävää hyllytarkennetta vaan API-muutosta joka mm. mahdollistaa hyllytarkenteellisten niteiden hakemisen API-kutsulla.

**Comment by emta001** [comment]
Tätä tarvitaankin, muuten SUBLOC arvot eivät näy APIssa, jos niissä on rajoitus johonkin kirjastoon.

**Comment by emta001** [comment]
Tuotu nexteille. En oo kyllä ihan varma kuinka testata tätä. Kaipa niin että jos jokin menee rikki, niin tässä on potentiaalinen kanditaatti sen särkymisen aiheuttajaks :smile:

**Comment by AnneliO** [comment]
Toiminee
