### ISSUE TITLE
Kohan omat auktoriteetit ja suurennuslasit teoksen perustiedot näytöllä

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha-23x#181]
### Mikä vikana?

Oulun luetteloinnista Heikkisen Antti kysyy: 
Onko Kohan omat auktoriteetit jääneet päälle, koska nyt muodostuu taas 9-osakenttiin niiden auktoriteettitietueiden tunnuksia?
Suurennuslasit ovat tulleet takaisin: esim. 2348620 ja 2041270, mutta ei tosin ihan kaikissa tietueissa ja kentissä esim. 2350667.
![image](https://github.com/KohaSuomi/Koha-23x/assets/98814860/350de283-2349-45a7-9a58-9e5093e53d78)

**Comment by AnneliO** [comment]
OUTIssa on tuotannossa päällä nämä asetukset:  AutoLinkBiblios, CatalogModuleRelink, LinkerModule ja LinkerRelink 

Luulisin noiden nyt vaikuttavan asiaan. Noita ei kyllä lokien mukaan ole muutettu (ei nexteillä eikä tuotannossa), joten olisiko ne ollut aiemminkin päällä ja nyt niiden toiminta jotenkin realisoituu eri tavalla kuin aiemmin.

**Comment by AnneliO** [comment]
Nuo voisi koittaa ottaa pois päältä ja testata, onko sillä vaikutusta.

**Comment by AnttHeik** [comment]
Tapahtuuko samaa muissa tietokannoissa vai onko noiden asetusten päällä olo vain OUTIn juttu?

**Comment by AnneliO** [comment]
Katsoin nyt Vaaraa ja siellä ei ole päällä  AutoLinkBiblios ja CatalogModuleRelink. Enkä ainakaan hoksaa, että tietueissa olisi muodostunut auktoriteetteja (ja sen myötä suurennuslaseja).

LinkerModule ja LinkerRelink siellä on päällä.

**Comment by pirliis** [comment]
Laitoin OUTIn testille asetukset kuin Vaarassa eli otin pois päältä nämä asetukset:
![image](https://github.com/KohaSuomi/Koha-23x/assets/98814860/f5dd56c7-49fa-4c4f-ba58-a045a3623433)

Asetuksessa LinkerModule oli vaihtoehto "oletus", jonka jätin päälle:
![image](https://github.com/KohaSuomi/Koha-23x/assets/98814860/e15a3918-5df2-48be-a888-26fd0439317b)

Asetuksessa LinkerRelink oli vaihtoehto "uudelleen linkitä", jonka jätin päälle:
![image](https://github.com/KohaSuomi/Koha-23x/assets/98814860/7bb94e48-f7d7-473a-b44a-78ceaaeb2154)

@AnttHeik pystytkö testaamaan testillä toimiiko nyt halutulla tavalla vai haluatko, että laitan asetukset tuotantoon?

**Comment by AnttHeik** [comment]
Testillä ainakin näyttäisi nyt ihan hyvältä. Ei näy 9-kenttiä samoissa tietueissa kuin tuotannossa. OUTIn testillä ei muuten näy tietuesiirtäjän aktivointisilmukkaa eikä tietuesiirtäjän aktivointiarvon tarkastaja löydä tietuetta.

Mihin nuo LinkerModule ja Relink muuten liittyvät? Onko ne näitä vai jotain muuta:
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/116169663/b93ece2e-24e3-477c-adcc-3d8d14a447dd)

**Comment by AnneliO** [comment]
[LinkerModule](https://koha-community.org/manual/23.11/en/html/authoritiespreferences.html#linkermodule)

Default: Default

Asks: Use the ___ linker module for matching headings to authority records.

Values:

* Default
  * Retains Koha’s previous behavior of only creating links when there is an exact match to one and only one authority record; if the [LinkerOptions](https://koha-community.org/manual/23.11/en/html/authoritiespreferences.html#linkeroptions-label) preference is set to ‘broader_headings’, it will try to link headings to authority records for broader headings by removing subfields from the end of the heading
* First match
  * Creates a link to the first authority record that matches a given heading, even if there is more than one authority record that matches
* Last match
  * Creates a link to the last authority record that matches a given heading, even if there is more than one record that matches

Description:
This preference tells Koha which match to use when searching for authority matches when saving a record.


[LinkerRelink](https://koha-community.org/manual/23.11/en/html/authoritiespreferences.html#linkerrelink)

Default: Do

Asks: ___ relink headings that have previously been linked to authority records.

Values:
* Do
* Do not

Description:

When set to ‘Do’, the linker will confirm the links for headings that have previously been linked to an authority record when it runs, correcting any incorrect links it may find. When set to ‘Do not’, any heading with an existing link will be ignored, even if the existing link is invalid or incorrect.

**Comment by pirliis** [comment]
Järjestelmäasetukset AutoLinkBiblios ja CatalogModuleRelink on otettu OUTIn tuotannossa pois päältä.

**Comment by pirliis** [comment]
Järjestelmäasetusmuutosten jälkeen todettu toimivaksi. Suljen tiketin.
