### ISSUE TITLE
Lumme: Laskutustyökalun puuttuva linkki

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha-23x#183]
### Mikä vikana?

Lumpeissa on aikaisemmin ollut Työkaluliitännäiset-linkin alla linkki Laskutustyökaluun. Nyt tämä suora linkki puuttuu. Laskutustyökalu kyllä löytyy liitännäisistä ja on toiminnassa. 

<img width="131" alt="Laskutustyökalu" src="https://github.com/KohaSuomi/Koha-23x/assets/129748294/d0776c97-f358-4c8a-99be-48c39f61addd">

**Comment by AnneliO** [comment]
IntranetUserCSS:ssä tämä rimpsu piilottaa todennäköisesti sen:

```
/* Piilota Työkalut-sivulta linkit JS-liitännäisiin Työkaluliitännäiset-osiosta. Rimpsut piilottavat tietyn rivin, joten kun liitännäisiä tulee lisää, kopioi yksi riveistä ja muuta nth-child(1)-kohtaan sopiva rivinumemero. JS-liitännäiset pitäisi tulla peräkkäin, mutta testaamalla löytyy oikea numero. */
body#tools_tools-home.tools div.col-sm-6 li:nth-child(1) { display: none; }
body#tools_tools-home.tools div.col-sm-6 li:nth-child(2) { display: none; }
```

Tuotannossa taitaa olla noita js-liitännäisiä asennettuna vähemmän kuin nextillä oli, joten tuotannossa nyt piilottuu liikaa rivejä. Rimpsuilla siis piilotetaan työkaluliitännäiset-osiosta ensimmäinen ja toinen rivi. Korjauksena siis on, että poista noista alempi rivi, jolloin laskutustyökalun pitäisi tulla näkyville. :)

**Comment by Hanna-Lumme** [comment]
Kiitoksia, tuon alimman rivin kun poisti, niin tuli Laskutustyökalu taas näkyviin. 😄
