### ISSUE TITLE
Virheilmoitus osakohdevirheistä

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha-23x#186]
### Mikä vikana?

OUTIn luetteloinnista tuli tieto, että tänä aamuna (10.5.) oli tullut kahden tietueen kohdalla ilmoitus osakohdevirheestä. Tietueissa ei ole osakohteita. 

Tietueessa: https://outi.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2343471, kun henkilö oli palannut Muokkaa tietuetta -toiminnosta Peruuta-napilla takaisin Perustiedot-näytölle.
![image](https://github.com/KohaSuomi/Koha-23x/assets/98814860/a77c29dd-a9ee-429b-a814-95cf505a19e2)

Tietueessa: https://outi.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2339928&searchid=scs_1715333952628, kun henkilö oli palannut Muokkaa nidettä -sivulta tietueen Perustiedot-näytölle.

**Comment by AnneliO** [comment]
Nyt kummassakaan ei näy tuota ilmoitusta. Tuo ilmoitus voi tulla, jos indeksoinnissa on jotain häikkää. Voisiko olla, että tallennuksen jälkeen kun tietue on mennyt taustatöihin uudelleenindeksoitavaksi, niin se olisi vielä tuossa vaiheessa ollut kesken?

Jos tuo ilmoitus tulee vielä vastaan, niin voisiko käyttäjä kokeilla, auttaako, jos hetken kuluttua päivittää näkymän F5:lla? Katoaako ilmoitus?

**Comment by pirliis** [comment]
En myöskään saanut toistettua virheilmoituksia kummassakaan tietueessa. Indeksoinnin keskeneräisyys voisi tosiaan selittää ilmoitukset. Pyydetään käyttäjiä kokeilemaan F5:sta.

**Comment by Hanna-Lumme** [comment]
Meillä tuli vastaava yhden kausijulkaisun vastaanotossa, muut lehdet pystyi viemään Kohaan ilman ongelmia.

**Comment by pirliis** [comment]
OUTIssa käyttäjä oli noissa tilanteissa päivittänyt selaimen sivun, jotta oli päässyt eteenpäin, ja virheilmoitus oli kadonnut. Enää ei ole tänään virheilmoituksia tullut.

**Comment by AnneliO** [comment]
Voisin kuvitella, että varsinkin silloin, kun on meneillään paljon tietueiden päivityksiä (esim. valutusta), niin taustatöihin voi kertyä paljon uudelleenindeksointeja ja ne valmistuvat normaalia hitaammin.

**Comment by pirliis** [comment]
Tämä voi olla hetkellinen ongelma, jos indeksointi kesken, kuten Anneli laittoi edellä. 
Suljen tiketin ja avataan uudestaan, jos ongelmaa alkaa tulla enempi.
