### ISSUE TITLE
Testi-Finnat - ksdev/ks-0031-KD-5288

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#19]
### Siirrettävä ominaisuus

Versionvaihtoa varten tarvitaan testi-Finnat.

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 20.11.2023: Tarvitaan

**Comment by emta001** [comment]
Testailin tätä vaara-nextillä, 

- liitännäinen asentui onnistuneesti
- endpointit näkyvät /api/v1-sivulla
- koha-httpd:ssä on OAI-asetus paikallaan

Kunhan outi-next valmistuu, pyydetään Finna-toimistolta haravointia kaikkiin next-kantoihin.

**Comment by AnneliO** [comment]
Finna-toimistosta pyydetty kaikille olemassa oleville next-kannoille uudelleenharavointi ja sieltä ilmoitettiin tänään, että se on nyt tehty.

Kirjautuminen ei toimi vielä, pitää tutkia, mistä johtuu.

**Comment by AnneliO** [comment]
Testi-Finnat toimii.
