### ISSUE TITLE
Helle-next: tiedonhaku ei toimi

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-23x#190]
### Mikä vikana?

Helle-nextissä tiedonhaku ei toimi. Hakiessa tuloksena tämä

![kuva](https://github.com/user-attachments/assets/98fa113d-c9f5-4282-8971-8f5c3510e7b4)

**Comment by CodoDerDritte** [comment]
Elasticsearch tuntuu vähän kummittelevan tuolla helle-nextillä. Sen käynnistys-skripti "syö" oman run-hakemistonsa ja sitten käynnistyminen ei onnistu kun ei ole run-hakemistoa. En tiedä miksi näin tapahtuu helle-nextillä, kun niin ei kuitenkaan tapahdu muissa next-konteissa, joissa se skripti on sama. Loin hakemistoon tyhjän .placeholder tiedoston, jolloin se ei enää syö hakemistoaan ja haku toimii jälleen. Tosi omituinen tapaus.

**Comment by Kati-Helle** [comment]
Voihan omituisuutta! Kiitos erikoistoimenpiteestä. Tiedonhaku toimii.
