### ISSUE TITLE
Järjestelmäasetus: DebarmentsToLiftAfterPayment - ksdev/ks-0006-bug-16223-lift-debarr 

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#2]
### Siirrettävä ominaisuus

Koha-Suomen versiossa on aiemmin ollut käytössä järjestelmäasetus DebarmentsToLiftAfterPayment. Yhteisöön on kuitenkin tullut uusi ominaisuus "Patron restrictions/Asiakasrajoitukset", jolla voidaan määritellä käytettäväksi erityyppisiä rajoituksia. Maksurajoja on ehdotettu yhteisöön osaksi ominaisuutta ja järjestelmäasetuksesta voidaan luopua.

**Comment by emta001** [comment]
Tämän tarpeellisuutta pitäisi vielä harkita. Jos kimpoilla ei ole tarvetta tälle, niin tuskin tätä tarvitsee meidän kuljettaa mukana.

**Comment by pknuuti** [comment]
Vaarassa tämä ei ole enää tarpeen. Lainauskiellot hoituvat, kun julkisoikeudellisia maksuja on liikaa ja maksujen maksamisen jälkeen asia on kunnossa. Muuten lainauskieltoa ei saa edes asettaa.

**Comment by emta001** [comment]
Merkataan tähänkin ylös, että ominaisuus on viety yhteisön masteriin. Joten senkään puolesta tästä ei enää tarvitse huolehtia.

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 20.11.2023: Yhteisössä, ei tarvitse meidän siirtää.
