### ISSUE TITLE
GDPR logging improvements - ksdev/ks-0032-KD-2473

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#20]
### Siirrettävä ominaisuus

GDPR logging improvements.

Pitäisi siis lokittua seuraavat:

Jos BorrowersLog-järjestelmäasetus on päällä:

* asiakastietojen muokkaus ja muokkausyritys (Patron/Modification.pm)

Jos BorrowersViewLog-järjestelmäasetus on päällä:

* käsittelyä odottavien asiakastietojen muutosten katselu (Patron/Modifications.pm)
* asiakashaku ja asiakasvalinta (REST/V1/Patrons.pm)
*  lainausten katselu (circ/circulation.pl)
*  asiakkaan tietojen katselu (members/moremember.pl)
*  ilmoitusten katselu (members/notices.pl)
*  maksujen katselu (members/pay.pl)
*  hankintaehdotusten katselu (members/purchase-suggestions.pl)
*  kiertolistojen katselu (members/routing-lists.pl)
*  tilastojen katselu (members/statistics.pl)
*  lokitietojen katselu tai vienti csv:ksi (tools/viewlog.pl)

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 20.11.2023: Siirretään ja yritetään tarjota yhteisöön.

**Comment by ajrajala** [comment]
Testaustulokset vaski-nextillä:

- asiakastietojen muokkaus ja muokkausyritys (Patron/Modification.pm) **-> Muokkaus lokittuu. Millaisessa tilanteessa muokkausyrityksen pitäisi lokittua? Yritin tätä niin, että pakollinen kenttä oli täyttämättä ja muokkauksen tallennus ei mennyt läpi, siitä ei jää lokimerkintää nextillä eikä testillä.**

- käsittelyä odottavien asiakastietojen muutosten katselu (Patron/Modifications.pm) **-> OK**

- asiakashaku ja asiakasvalinta (REST/V1/Patrons.pm) **-> OK**

- lainausten katselu (circ/circulation.pl) **-> OK**

- asiakkaan tietojen katselu (members/moremember.pl) **-> OK**

- ilmoitusten katselu (members/notices.pl) **-> OK**

- maksujen katselu (members/pay.pl) **-> OK**

- hankintaehdotusten katselu (members/purchase-suggestions.pl) **-> OK**

- kiertolistojen katselu (members/routing-lists.pl) **-> OK**

- tilastojen katselu (members/statistics.pl) **-> OK**

- lokitietojen katselu tai vienti csv:ksi (tools/viewlog.pl) **-> Lokitietojen katselu OK, miten vienti csv:ksi pitäisi lokittua? Nyt lokittuu minusta vain Log page -sivun katselu, näin myös testillä.**

**Comment by ghost** [comment]
Muokkausyritys lokittuu ilmeisesti vain jos muokkausta yrittää ilman muokkausoikeutta.

Vienti csv:ksi lokittuu kun sen tekee Tulostus-kohdasta. Vie-painikkeen painaminen ei lokitu erikseen.

**Comment by ajrajala** [comment]
En saa tuosta Tulostus-kohdastakaan muodostumaan erillistä lokimerkintää mutta sama juttu on minulla kyllä tuotannossakin, eli lokitus sinänsä minusta näyttää toimivan samalla tavalla.

**Comment by AnneliO** [comment]
Toimii
