### ISSUE TITLE
Do not allow script-tags in systempreferences - ksdev/ks-0035-KD-4346

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#23]
### Siirrettävä ominaisuus

Do not allow script-tags in systempreferences.

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 20.11.2023: Siirretään, yritetään tarjota yhteisölle.

**Comment by CodoDerDritte** [comment]
Testillä nyt ja näyttäisi toimivan. Periaatteessa voi vetää ensi tiistaina tuotantoon (jos uskaltaa). Itse olen lomalla. Branchi on   ksdev/ks-0035-K23-23-no-scripts-in-sysprefs.

**Comment by emta001** [comment]
Testipläni:
1. Mene Järjestelmäasetuksiin 
2. Etsi sieltä mikä tahansa asetus, jossa on tekstikenttä (esim. IntranetCirculationHomeHTML, PurgeSuggestionsOlderThan,  NotifyBorrowerDeparture).
3. Lisää kenttään seuraava teksti <script>alert("Alert")</script>.
4. Yritä tallentaa.
=> Tallennuksen tulisi epäonnistua virheeseen "Internal Server Error, please reload the page".

**Comment by pknuuti** [comment]
Kun yritin tallentaa tuon scriptitekstin kenttään [opacnavigation](https://vaara-test.koha-suomi.fi/cgi-bin/koha/admin/systempreferences.pl?op=add_form&searchfield=opacnavigation), sain virheilmoituksen 
"Virhe!
Virhe 500
Tämä viesti johtuu jostain seuraavasta syystä:

    Ulkoinen lähde on ohjannut sinut nimekkeeseen, jota ei ole enää olemassa
    Seurasit vanhaa linkkiä esim. hakukoneesta tai kirjanmerkeistä
    Yritit päästä sivulle, jonne pitää kirjautua.
    Linkki oli virheellinen ja sivua ei ole olemassa

Mitä seuraavaksi?

    Käytä ylävalikkoa siirtyäksesi toiseen Kohan osioon.
    Raportoidaksesi toimimattoman linkin tai muun ongelman, ota yhteys ylläpitoon. [Lähetä sähköposti](mailto:noreply%40koha-suomi.fi)"
    
Muissa yrityksissä tuli mainitsemasi sisäinen virhe, joka käski lataamaan sivun uudelleen ja teksti oli hävinnyt kentästä. Tuossa Virhe 500:ssa teksti jäi kenttään edelleen. Sama tapahtuu muissakin Paikallisten järjestelmäasetusten kohdalla.

**Comment by emta001** [comment]
> Kun yritin tallentaa tuon scriptitekstin kenttään [opacnavigation](https://vaara-test.koha-suomi.fi/cgi-bin/koha/admin/systempreferences.pl?op=add_form&searchfield=opacnavigation), sain virheilmoituksen "Virhe! Virhe 500 Tämä viesti johtuu jostain seuraavasta syystä:
> 
> ```
> Ulkoinen lähde on ohjannut sinut nimekkeeseen, jota ei ole enää olemassa
> Seurasit vanhaa linkkiä esim. hakukoneesta tai kirjanmerkeistä
> Yritit päästä sivulle, jonne pitää kirjautua.
> Linkki oli virheellinen ja sivua ei ole olemassa
> ```
> 
> Mitä seuraavaksi?
> 
> ```
> Käytä ylävalikkoa siirtyäksesi toiseen Kohan osioon.
> Raportoidaksesi toimimattoman linkin tai muun ongelman, ota yhteys ylläpitoon. [Lähetä sähköposti](mailto:noreply%40koha-suomi.fi)"
> ```
> 
> Muissa yrityksissä tuli mainitsemasi sisäinen virhe, joka käski lataamaan sivun uudelleen ja teksti oli hävinnyt kentästä. Tuossa Virhe 500:ssa teksti jäi kenttään edelleen. Sama tapahtuu muissakin Paikallisten järjestelmäasetusten kohdalla.

Lokeille tulee tuon asetuksen tallentamisen jälkeen "Forbidden tag script in input at /home/koha/Koha/C4/Context.pm line 450." kuten pitääkin. Ilmeisesti noissa paikallisissa järjestelmäasetuksissa ei ole samanlaista hienostunutta virhekäsittelyä kuin muissa asetuksissa :sweat_smile:

**Comment by sksandel** [comment]
Vaski-testillä tämän testaaminen PurgeSuggestionsOlderThan -asetuksella päätyi "Palvelinvirhe, lataa sivu uudestaan" -ilmoitukseen.

**Comment by LeenaKinnunen** [comment]
Myös Lapin testillä PurgeSuggestionsOlderThan -asetuksella päätyi "Palvelinvirhe, lataa sivu uudestaan" -ilmoitukseen.

**Comment by Kati-Helle** [comment]
Helle-nextissä lisäsin järjestelmäasetukseen PurgeSuggestionsOlderThan tekstin <script>alert("Alert")</script>
Tallennuksen tuloksena Kohan ilmoitus: Error. Internal Server Error

![Image](https://github.com/user-attachments/assets/1f6a249a-de28-4163-a730-9e52c2d0fa76)
