### ISSUE TITLE
Web-Kake-integraatio - ksdev/ks-0036-KD-4601-ILL

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#24]
### Siirrettävä ominaisuus

Kaukolainaohjelma WebKakeen on tehty integraatiot, joissa asiakastiedot haetaan Kohasta WebKakeen ja asiakkaan kaukolainat näytetään Kohassa lainojen alapuolella Lainat-sivulla.

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 20.11.2023: Siirretään

**Comment by emta001** [comment]
Koha-Suomen palaveri 22.4.2024: Tehdään uusi tiketti Web-Kake-liitännäisestä.
