### ISSUE TITLE
Omatoimikirjastojen blokkaukset - ksdev/ks-0038-KD-4572

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#26]
### Siirrettävä ominaisuus

Omatoimikirjastojen blokkaukset välitetään SIP2-sanomassa omatoimikoneelle. Blokki lisätään borrower_ss_blocks-tauluun.

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 20.11.2023: Siirretään

**Comment by lmstrand** [comment]
Yhdistetyssä branchissa ksdev/ks-0043-K23-15-SIP2.

**Comment by lmstrand** [comment]
Varmistetaan toimivuus tuotantoon siirryttyä ja avataan tiketti tarvittaessa.
