### ISSUE TITLE
Järjestelmäsetus: BorrowerCategoryTimeout - ksdev/ks-0039-on-0024-KD-4564

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#27]
### Siirrettävä ominaisuus

Asiakastyyppikohtainen timeout, tehty Kohan itsepalvelulainausta (SCO:ta) varten, jotta itsepalvelun käyttäjätunnukset eivät noudattaisi normaalia timeoutia.

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 20.11.2023: Siirretään

**Comment by CodoDerDritte** [comment]
Yhdistetty #14 (ksdev/ks-0024-K23-14-auth-extra)

**Comment by AnneliO** [comment]
Kirjauduin outi-nextin itsepalvelussa AUTOM-tyyppisellä tunnuksella ja kokeilin noin tunnin välein lainata tai palauttaa. Tunnus oli pysynyt kirjautuneena.

**Comment by AnneliO** [comment]
Testasin nyt vielä niin, että kirjauduin muulla kuin AUTOM-tyyppisellä tunnuksella. Sivu näytti kuin olisi kirjautuneena sisään, mutta jos yritin lainata, tuli kirjautumissivu. Eli toimi tuossakin tapauksessa oikein.

**Comment by CodoDerDritte** [comment]
Lienee siis kunnossa, suljen tämän.
