### ISSUE TITLE
Hyllytarkenne - ksdev/ks-0040-K22-7-items_sublocation

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#28]
### Siirrettävä ominaisuus

items-tauluun on lisätty sub_location-sarake, johon tallennetaan Hyllytarkenne. Se näkyy tietueen perustiedot-näytöllä nidetaulussa Kotikirjasto-sarakkeessa hyllypaikan jälkeen sulkeissa:

![224313844-75577053-6d6b-4177-90bd-4bfc26fb458f](https://github.com/KohaSuomi/Koha-23x/assets/33121325/5f8bedd9-9d96-4451-a08a-7b1e45a99659)

Palautuksessa omana sarakkeenaan:
![224316230-4b26e4ff-870e-46b5-b236-98bfa0be8162](https://github.com/KohaSuomi/Koha-23x/assets/33121325/1798442c-d47b-43b9-957c-6a7ab3dedf67)

**Comment by emta001** [comment]
Tätä tuodessa kannattaa myös muuttaa atomicupdate filun pääte perlistä pl:ksi. Muuten se ei asennu uusiin kantoihin.

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 20.11.2023: Siirretään

Voiko yhdistää toiseen hyllytarkenne-branchiin?

**Comment by emta001** [comment]
> Koha-Suomen asiantuntijaryhmä 20.11.2023: Siirretään
> 
> Voiko yhdistää toiseen hyllytarkenne-branchiin?

Toinen branch sisältää pelkkiä API-muutoksia, jotka mahdollistavat hyllytarkenteen käyttämisen sitä kautta (https://github.com/KohaSuomi/Koha-22x/commit/71c48e8bdaa70b030ce3cb9eea8b2ef5c4e24a94 ja https://github.com/KohaSuomi/Koha-22x/commit/e8ddf6b1b8d56d0c9a4623438190d609712a7cc7). Tää branchi ei siis liity pelkästään hyllytarkenteeseen (branchin nimen vois kyllä vaihtaa :smile: ).

**Comment by Kati-Helle** [comment]
Helle-Nextillä Hyllytarkenne-arvo näkyy tietueen Perustiedot-näytöllä Kotikirjasto-sarakkeessa kirjaston nimen jälkeen
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/9dc46f94-8170-49f0-93b7-3467a5b9e21f)

Näkyy myös Palautus-toiminnossa Hyllypaikka-sarakkeessa hyllypaikka-arvon jälkeen
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/b43e1ce3-2d33-41e6-af76-eefe4956432e)

**Comment by ajrajala** [comment]
Vaski-nextillä hyllytarkenne näkyy kuten tuotannossakin.

**Comment by emta001** [comment]
Testattu ja toimii.
