### ISSUE TITLE
Tietuenäytön muutokset - ksdev/ks-0041-KD-4592-intra-xslt-display

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#29]
### Siirrettävä ominaisuus

Tietuenäytön xslt-muutokset.

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 20.11.2023: Siirretään

**Comment by pirliis** [comment]
OUTIssa tuotannon ja nextin tietuenäytöt näyttäisivät vastaavan muutoin toisiaan, mutta nextiltä puuttuu:
- aineistotyyppi
- "Julkaisutiedot"-kohdan linkitys, esim. Helsinki
- "Valmistaja" -kohdan linkitys, esim. Tallinna

Esim. tietue: https://outi-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2332321&searchid=scs_1729861288547
![Image](https://github.com/user-attachments/assets/24f060ab-c575-4eed-95d2-c59505693256)

- Tuottajan maa
- Luontiaika
- Ikäraja
esim. tietue:  https://outi-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2315803&searchid=scs_1729860979524

**Comment by pknuuti** [comment]
Vaaran nextillä testattu, nyt näkyy kaikki samat tiedot kuin tuotannossakin. Joitakin käännöksiä puuttuu.
![2023kuvat 562](https://github.com/user-attachments/assets/0c7f5c16-0389-435b-8901-a82b9578748b)

**Comment by AnneliO** [comment]
Koha-Suomen käännökset voidaan luoda, kunhan xslt-tiedot on todettu toimivaksi: https://github.com/KohaSuomi/Koha-24.05/issues/127

**Comment by pirliis** [comment]
Myös OUTIn nextillä näyttäisi nyt tietueet vastaavan tuotantoa.

**Comment by annavii** [comment]
Vaskin nextillä vastaa tuotantoa.

**Comment by LastuJanneS** [comment]
Onko tällaista esiintynyt muilla? En onnistunut löytämään haulla enkä tiketeistäkään. Nextille on ilmestynyt tietuenäytölle tuollainen "Tekijän ominaisuudet"-kohta. MARC-tietueessa tuo näyttää olevan 386 $m ja $a (samat kuvailutiedot sekä tuotannossa että nextillä), HTML:n puolella tuon kentän luokkina on puolestaan results_summary ja creator_characteristics.

Tuotanto:
![Image](https://github.com/user-attachments/assets/0626ea55-7254-4825-a5ba-9c3688aaac28)

Next:
![Image](https://github.com/user-attachments/assets/0907484d-a686-4af8-91c6-b2627c08c2a0)

Tarkistin ettei ollut piilotettuna tuotannossa.

**Comment by AnneliO** [comment]
Tuo tieto on lisätty näkyviin nexteillä tässä tiketissä: https://github.com/KohaSuomi/Koha/issues/841

**Comment by AnneliO** [comment]
Tuosta kuvasta huomasin, että Tekijän ominaisuudet: -käännöksen jälkeen puuttui välilyönti. Se on nyt lisätty ja tulee näkyville seuraavassa buildissä.

**Comment by AnneliO** [comment]
Tämä on version 23.11 tiketti, joten suljen tiketin.
