### ISSUE TITLE
Noutoaika asiakastyypin, aineistolajin ja kirjaston mukaan - ksdev/ks-0008-bug-8367-hold-pickup-rule

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#3]
### Siirrettävä ominaisuus

Yhteisön (ei vielä masterissa) ominaisuus , jolla varaukselle voidaan määritellä noutoaika laina- ja maksusäännöissä.

**Comment by emta001** [comment]
Tämäkin on nyt yhteisön masterissa ja tulee mukaan versioon 23.11.

**Comment by pknuuti** [comment]
En hoksaa, mikä tässä on uutta nykyiseen tuotantoversioon nähden Vaaran nextillä.

**Comment by emta001** [comment]
> En hoksaa, mikä tässä on uutta nykyiseen tuotantoversioon nähden Vaaran nextillä.

Ei pidäkään olla eli ominaisuus toimii kuten pitääkin jos kaikki toimii :D 

Tää on siis tähän mennessä kulkenut meillä mukana omana ominaisuutena, nyt se vaan tulee suoraan uudesta versiosta.

**Comment by pknuuti** [comment]
En pysty testaamaan toimiiko ajan muuttaminen, koska en saa palautettua nidettä joka voisi tarttua varaukseen. Esim. nide [167N11571266](https://vaara-next.koha-suomi.fi/cgi-bin/koha/catalogue/moredetail.pl?itemnumber=101640129&biblionumber=11707023&bi=11707023#item101640129)

**Comment by emta001** [comment]
Palautus ei toimi myöskään OUTI-nextillä, lokiin tulee herjaa sub_location-sarakkeesta.

**Comment by emta001** [comment]
> En pysty testaamaan toimiiko ajan muuttaminen, koska en saa palautettua nidettä joka voisi tarttua varaukseen. Esim. nide [167N11571266](https://vaara-next.koha-suomi.fi/cgi-bin/koha/catalogue/moredetail.pl?itemnumber=101640129&biblionumber=11707023&bi=11707023#item101640129)

Sain palautettua tuon niteen, skeemassa oli jotain häikkää koska buildin ajaminen ja palveluiden uudelleenkäynnistys auttoi.

**Comment by pknuuti** [comment]
Vaaran nextillä toimii noutoajan vaihtaminen kuten pitääkin. Testasin muuttamalla lyhytlainan noutoajan ja tein varauksen lyhytlainaniteeseen. Kun varaus jäi kiinni, noutoaika oli asetuksen mukainen.

**Comment by Kati-Helle** [comment]
Helle-Nextillä 
- tänään 23.1.2024 tärpänneelle varaukselle, jonka noutokirjasto on  Degerbyn närbibliotek, vanhenee-arvoksi oikein 1.2.2024

Kirjaston kaikkien varattavien niteiden noutoaika on 2 (päivää). 
Kirjaston kalenterinäkymää
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/6c3035b1-0be6-401e-bd29-66f9b67f2563)

Noutoaika on määriteltynä kahteen paikkaan - toinen turhako?
- Degerby närbibliotek laina- ja maksusäännöt/Varauksen noutoaika (päiviä) -sarake
- paikalliset tiedot/reservesmaxpickupdelaybranch (tyyliin INKDK: 2)

**Comment by MikkoLiimatainen** [comment]
Vaski-Nextillä toimii myös oikein. Varaus sai aina oikean noutoajan asiakastyypin, nidetyypin ja kirjaston mukaan.

**Comment by ElinaUotila** [comment]
No siis, meillähän on ollut tuotannossa Tuusulan kirjastoautossa se ongelma, että laina-aika 28 vrk yleinen antaa seitsemän päivän noutoajan, vaikka asetuksissa on 14 päivää. Nyt kun testailin tätä Kirkes-nextillä, havaitsin, että noutoajat tulivat oikein asiakastyypin, nidetyypin ja kirjaston mukaan, _paitsi_ siinä tapauksessa kun yritin muuttaa 28 vrk yleiselle lyhyemmän noutoajan muissa kirjastoissa kuin kirjastoautoissa. Edelleen tuli seitsemän päivää. (Ja kirjastoautoissa 28 vrk yleinen oli se seitsemän päivää 14 sijaan samalla tavalla kuin tuotannossa).

tl;dr asetus toimii kaikilla muilla nidetyypeillä, paitsi yhdellä, jossa näyttää olevan Kirkes-spesifi ongelma sekä tuotannossa että testillä ja nextillä.

**Comment by emta001** [comment]
> No siis, meillähän on ollut tuotannossa Tuusulan kirjastoautossa se ongelma, että laina-aika 28 vrk yleinen antaa seitsemän päivän noutoajan, vaikka asetuksissa on 14 päivää. Nyt kun testailin tätä Kirkes-nextillä, havaitsin, että noutoajat tulivat oikein asiakastyypin, nidetyypin ja kirjaston mukaan, _paitsi_ siinä tapauksessa kun yritin muuttaa 28 vrk yleiselle lyhyemmän noutoajan muissa kirjastoissa kuin kirjastoautoissa. Edelleen tuli seitsemän päivää. (Ja kirjastoautoissa 28 vrk yleinen oli se seitsemän päivää 14 sijaan samalla tavalla kuin tuotannossa).
> 
> tl;dr asetus toimii kaikilla muilla nidetyypeillä, paitsi yhdellä, jossa näyttää olevan Kirkes-spesifi ongelma sekä tuotannossa että testillä ja nextillä.

Oliko tästä vielä olemassa tiketti? Voisin yrittää metsästää mikä tässä nyt oikein mättää, mutta sen voisi tehdä jonkin muun kuin tämän tiketin alla.

**Comment by ElinaUotila** [comment]
> > No siis, meillähän on ollut tuotannossa Tuusulan kirjastoautossa se ongelma, että laina-aika 28 vrk yleinen antaa seitsemän päivän noutoajan, vaikka asetuksissa on 14 päivää. Nyt kun testailin tätä Kirkes-nextillä, havaitsin, että noutoajat tulivat oikein asiakastyypin, nidetyypin ja kirjaston mukaan, _paitsi_ siinä tapauksessa kun yritin muuttaa 28 vrk yleiselle lyhyemmän noutoajan muissa kirjastoissa kuin kirjastoautoissa. Edelleen tuli seitsemän päivää. (Ja kirjastoautoissa 28 vrk yleinen oli se seitsemän päivää 14 sijaan samalla tavalla kuin tuotannossa).
> > tl;dr asetus toimii kaikilla muilla nidetyypeillä, paitsi yhdellä, jossa näyttää olevan Kirkes-spesifi ongelma sekä tuotannossa että testillä ja nextillä.
> 
> Oliko tästä vielä olemassa tiketti? Voisin yrittää metsästää mikä tässä nyt oikein mättää, mutta sen voisi tehdä jonkin muun kuin tämän tiketin alla.

No nyt on: https://github.com/KohaSuomi/Koha/issues/1099 

Testailin viime viikolla vielä vähän lisää, mutta en silloin ehtinyt tiketöidä.

**Comment by emta001** [comment]
> > > No siis, meillähän on ollut tuotannossa Tuusulan kirjastoautossa se ongelma, että laina-aika 28 vrk yleinen antaa seitsemän päivän noutoajan, vaikka asetuksissa on 14 päivää. Nyt kun testailin tätä Kirkes-nextillä, havaitsin, että noutoajat tulivat oikein asiakastyypin, nidetyypin ja kirjaston mukaan, _paitsi_ siinä tapauksessa kun yritin muuttaa 28 vrk yleiselle lyhyemmän noutoajan muissa kirjastoissa kuin kirjastoautoissa. Edelleen tuli seitsemän päivää. (Ja kirjastoautoissa 28 vrk yleinen oli se seitsemän päivää 14 sijaan samalla tavalla kuin tuotannossa).
> > > tl;dr asetus toimii kaikilla muilla nidetyypeillä, paitsi yhdellä, jossa näyttää olevan Kirkes-spesifi ongelma sekä tuotannossa että testillä ja nextillä.
> > 
> > 
> > Oliko tästä vielä olemassa tiketti? Voisin yrittää metsästää mikä tässä nyt oikein mättää, mutta sen voisi tehdä jonkin muun kuin tämän tiketin alla.
> 
> No nyt on: [KohaSuomi/Koha#1099](https://github.com/KohaSuomi/Koha/issues/1099)
> 
> Testailin viime viikolla vielä vähän lisää, mutta en silloin ehtinyt tiketöidä.

Jes, kiitos! Kattelen tuota ja suljen tän tiketin.
