### ISSUE TITLE
SIP muutos - ksdev/ks-0044-KD-913

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#31]
### Siirrettävä ominaisuus

SIP-muutos.

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 20.11.2023: Mitä tämä tekee?

**Comment by AnneliO** [comment]
Lisää alertin niteen tilan muutoksesta. Esim. laskutettu nide.

Voiko yhdistää toisen SIP muutos -branchin kanssa?

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 20.11.2023: Siirretään

**Comment by lmstrand** [comment]
Yhdistetyssä branchissa ksdev/ks-0043-K23-15-SIP2.

**Comment by lmstrand** [comment]
Varmistetaan toimivuus tuotantoon siirryttyä ja avataan tiketti tarvittaessa.
