### ISSUE TITLE
Verkkokirjastossa tehdyt uusinnat kirjautuu Finna-api-käyttäjän kotikirjaston mukaan - ksdev/ks-0047-KD-5452

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#32]
### Siirrettävä ominaisuus

Verkkokirjastossa tehdyt uusinnat kirjautuu Finna-api-käyttäjän kotikirjaston mukaan.

Lari teki verkkokirjastouusintoihin korjauksen, että se seuraa OpacRenewalBranch-järjestelmäasetusta statistics-taulun osalta. Korjaus viedään tuotantoon maanantaina. Kaikkien kannattaa käydä tarkistamassa, että tuossa asetuksessa on nyt se valinta, jonka mukaan haluatte verkkokirjastouusintojen tilastoituvan.

Sen sijaan verkkokirjasto seuraa eräpäiväkalenteria valitessaan circcontrol- ja HomeorHoldingbranch-järjestelmäasetuksia. Ne kannattaa säätää siten, kuin haluatte uusintojen seuraavan. Esim. OUTIssa halutaan uusinnan seuraavan lainanneen kirjaston eräpäiväkalenteria, jolloin valitsemme asetuksiin seuraavat:

circcontrol: the library where the item is from
homeorholdingbranch: holdingbranch

HomeOrHoldingbranch-asetuksessa määritetään, käytetäänkö niteen koti- vai sijaintikirjastoa. Kun nide lainataan eri kirjastossa kuin sen kotikirjastossa, on sen sijaintikirjasto lainaava kirjasto, jolloin asetukseen valitaan sijaintikirjasto, mikäli halutaan uusinnan seuraavan lainannutta kirjastoa.

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 20.11.2023: Siirretään

**Comment by lmstrand** [comment]
Branchissa ksdev/ks-0047-K23-17-api-OpacRenewalBranch

**Comment by pknuuti** [comment]
Vaaran nextillä näyttäisi alkuhämmennyksen jälkeen toimivan kuten halutaan eli uusintakirjastona näyttää lainauskirjaston, kun uusiminen tehdään Finnan kautta.

**Comment by ElinaUotila** [comment]
Testattu Kirkes-Nextillä: 

Kun OpacRenewalBranch-asetuksessa on valittuna niteen lainannut kirjasto, Finna-Nextillä tehdyn uusinnan uusintakirjastoksi tulee lainauskirjasto. 

Kun OpacRenewalBranch-asetuksessa on valittuna niteen kotikirjasto, Finna-Nextillä tehdyn uusinnan uusintakirjastoksi tulee niteen kotikirjasto.
