### ISSUE TITLE
Kimpan logot näkyviin - ksdev/ks-0050-K22-18-ks-images

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#34]
### Siirrettävä ominaisuus

Kimppojen logot näkyviin virkailijaliittymässä.

**Comment by paxed** [comment]
Pienet kuvat voi tehdä CSS:n base64 data URI:lla, esim.

```
      body {
      background: url(data:image/gif;base64,R0lGODlhEAAQAMQAAORHHOVSKudfOulrSOp3WOyDZu6QdvCchPGolfO0o/XBs/fNwfjZ0frl3/zy7////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAkAABAALAAAAAAQABAAAAVVICSOZGlCQAosJ6mu7fiyZeKqNKToQGDsM8hBADgUXoGAiqhSvp5QAnQKGIgUhwFUYLCVDFCrKUE1lBavAViFIDlTImbKC5Gm2hB0SlBCBMQiB0UjIQA7)
      no-repeat
      left center;
      }
```

Ja netissä on useita sivuja joilla voi käydä konvertoimassa kuvan base64 datauriksi

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 20.11.2023: Testataan uusi tapa. Jos toimii, ei siirretä.

**Comment by MikkoLiimatainen** [comment]
Vaski-Nextillä toimii. Logon alkuperäinen koko 317x92 pikseliä. Muodostunut data URI on aika pitkä, mutta se toimii ja nähdäkseni tuossa ei ole mitään visuaalista eroa alkuperäiseen kuvaan nähden.

**Comment by pknuuti** [comment]
Tarttee varmaan lisää ohjeita. Vaaran nextillä logo tuli vasempaan alareunaan

**Comment by MikkoLiimatainen** [comment]
Itse loin tuon Base64 data ULI:n tämän sivun avulla https://dopiaza.org/tools/datauri/index.php

Sitten laitoin saamani datan Kohan logon korvaavaan IntranetUserCSS:ään näin

`#logo.navbar-brand:after {
  background-image: url(Tähän tulee base64 data URI);
  background-size: 103px 30px;  
  display: block;
  width: 103px; 
  height: 30px;
  content:"";` 

Tuo css on varmaan eri kimpoissa hieman erilainen, mutta tässä ei tarvitse tehdä muuta kuin vaihtaa tuon backgound-imagen url.

**Comment by pknuuti** [comment]
Kiitos Mikko, mutta Vaarassa ei näytä onnistuvan noin. Tai sitten mä vaan en osaa.
Sain kolmannella yrittämällä melkein oikein, logokuvan tausta vaan ei näy oikean värisenä.

**Comment by AnneliO** [comment]
Lisäsin perjantaina IntranetUserCSS-wikiin ohjeen: 
https://github.com/KohaSuomi/Koha-23x/wiki/IntranetUserCSS#muita

(joka taitaa olla aika sama kuin Mikon ohje :) )

**Comment by AnneliO** [comment]
> Kiitos Mikko, mutta Vaarassa ei näytä onnistuvan noin. Tai sitten mä vaan en osaa. Sain kolmannella yrittämällä melkein oikein, logokuvan tausta vaan ei näy oikean värisenä.

Minkä kuvan muutat base64-muotoon? Voitko pistää sen tiedoston vaikka tänne kommenttina? :)

**Comment by pknuuti** [comment]
![vaaralogo2024lapinakyva](https://github.com/KohaSuomi/Koha-23x/assets/73887264/24756a93-3535-4d9c-b4b2-4e3a6860b9f5)
Vaikka tausta on läpinäkyvä, se tulee erivärisenä kuin tausta tuonne yläpalkkiin.

**Comment by AnneliO** [comment]
@pknuuti ongelmana oli tuo läpinäkyvä tausta, eli muuntotyökalu teki siitä harmaan. Muutin kuvan taustan väriksi saman kuin palkin väri, niin se istuu nyt minusta nätisti palkkiin. Säädin myös kokoa. Meni aika pieneksi, mutta saa siitä vielä selvää. Käy vilkasemassa Vaaran nextillä, miltä se sinusta näyttää. :)

**Comment by pknuuti** [comment]
Logo on nyt jotenkin epätarkka, en tykkää. Mikä tuon pohjavärin koodi on, niin voisin vaihtaa sen itsekin?

**Comment by MikkoLiimatainen** [comment]
Onkohan tuo muuntotyökalusta riippuvainen asia? Vaskin logo on nimittäin myös läpinäkyvä ja se ei muutu harmaaksi vaan säilyttää läpinäkyvyytensä. Molemmat tiedostot näyttävät kuitenkin olevan samanlaisia png-tiedostoja.

**Comment by pknuuti** [comment]
> Onkohan tuo muuntotyökalusta riippuvainen asia? Vaskin logo on nimittäin myös läpinäkyvä ja se ei muutu harmaaksi vaan säilyttää läpinäkyvyytensä. Molemmat tiedostot näyttävät kuitenkin olevan samanlaisia png-tiedostoja.

Outoa, käytin tuota samaa muuntotyökalua, minkä neuvoit.

**Comment by MikkoLiimatainen** [comment]
Tuo Vaaran logon tausta ei ole täysin läpinäkyvä. Siitä johtuu tuo harmaa sävy.

**Comment by AnneliO** [comment]
> Logo on nyt jotenkin epätarkka, en tykkää. Mikä tuon pohjavärin koodi on, niin voisin vaihtaa sen itsekin?

Epätarkkuus voi johtua siitä, että säädin niitä leveyksiä ja korkeuksia ja ne eivät välttämättä ole nyt kohdillaan.

Löysin sen värin aiemmin Kohasta selaimen Tarkastele-toiminnolla, mutta jostain syystä se ei nyt löydy enää. xD

**Comment by lmstrand** [comment]
https://github.com/KohaSuomi/Koha-22x/tree/ksdev/ks-0050-K22-18-ks-images/koha-tmpl/koha-suomi-images

Tuolta löytyy Koha-Suomen palvelinta varten kerätyt logot kaikista kimpoista. SVG-tiedostojakin näköjään pystyy muuttamaan base64:ksi.

**Comment by pknuuti** [comment]
Kiitos kaikista huomioista. Nyt Vaaran nextillä logo ainakin minua tyydyttävässä kuosissa.

**Comment by lmstrand** [comment]
Nuo favico-ikonit (selaimen ylälaidan pikkuikonit tabeissa) saa muunnettua base64:ksi, kun asetukseen IntranetFavicon laittaa tiedon muodossa:

```
data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAA lwSFlzAAALEwAACxMBAJqcGAAAAVlpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADx4 OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IlhNUCBDb3 JlIDUuNC4wIj4KICAgPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9y Zy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICAgICAgPHJkZjpEZXNjcmlwdG lvbiByZGY6YWJvdXQ9IiIKICAgICAgICAgICAgeG1sbnM6dGlmZj0iaHR0cDovL25z LmFkb2JlLmNvbS90aWZmLzEuMC8iPgogICAgICAgICA8dGlmZjpPcmllbnRhdGlvbj 4xPC90aWZmOk9yaWVudGF0aW9uPgogICAgICA8L3JkZjpEZXNjcmlwdGlvbj4KICAg PC9yZGY6UkRGPgo8L3g6eG1wbWV0YT4KTMInWQAABLJJREFUWAnFV+trW2UY/yVN0j S32q6bnWunQ1e11k3YXMUy8AbDoSBDv4mfFPTj/gD9ug/7B/woqCCISnGItcyppbgN Rhn2st5G2yxt1svSJe1yPYnP703fcs7JSZo4YS9Ncs57eX6/5/Y+T12fX7hYdAHy92 iG+1GCU2X3/6V3k9sNl8uFUqnUkMiHJkDfuQV4M7WFbC4Hr8fTEAlPQ3RtmwleFI0z mQxO95/EQP8pLEaj+PaHQbS3RmAUi7YTla8PRYDGLhgGPnz/HI719Srp0VgMhszRHf WM/+wC+jy1tY2zb72uwOl7WmPi1gwCfr887609CdZtAfpZa0XNc/k8nug8gBPHjylF uTY7N4/JmVmEQkFlBbWwx9eeBNyiKbVLZ7IKlEAtomEmm0Vvz1G0tLQoiKXoHXzz/Y 9qX75QgM/jhb/ZB5KtlRk1CdDM2+k0SKLn6SM4KBoXRHhsOY6J2XmsbWxgdv42Jqdn cH3sJo4c7sKhg50oFku4s7yMuYUleJqahEizzDm7pCoBgt8XH7/Q8wzOvPmamLtz1w UMvPjdu1hYjIrPp9He9hjOf/oJ9rW37e5hBiwuRXFpaBjR5RWEgkFHEq4vLlysuDkI nhTwV068hPfeOau0oJ21KXUsKNvbvux7suKq734axNT0nLhOLCHuNI8KC1B4Wg7RnO ++fUaB03x0gxlYA1EYZcoxta73cJ3PD8SFuWxOnbdCl2k4EuCN9sbpATT7fMpsBLcP DcR5gpuHBk8mU/jyq6+xcW8TYckMpziwSKagvKTX4x0deOpwt5JpBjKD1PM8eu064q vraI2EHcEpw0pAqnK+YODA/n3wS6pxNEpAa58TK05IdoQl+AyjoGQ5fVkI0JbFoqEi tlFgu/C01IeM3B2UY4s7y1YrAbXUeEm1SNx58Un8sDJKiNbsdiwEaD6m4JakoFPAOA HZ57TleFs+2d2lMsotl1G1YSHATR5PEzYSCXXt8p2kGh36zED/y+o8qyNridOwEOBB j5htI7GJ1bU1p/11zZX9XkJ31yF89MG5nTpScAxoCwFKZ86z8NxeWKwLrNom7YrjL/ bh/GcfY39Hu2RYJYkKAvR9KBjAjZv/CJHMThQ37gYS066IhMNgWmpSZtIVBHio2euV AhLH+OSU2qsFmQ828jx69Rpi8VX4vJX9YgUBCmbBCIsVhv8cQTKVKt/jDsFIYvpjJ0 RLUuPYygqujF5FG3tEo7IkOxKgUObwvcR9DF2+omRTmE5NDco5/dFzSoGd4sWaMvjL kCJZJQmsV7FZC9bziBSQv2+M4Y+RUbWki5IGZXPC1oy/eo4buY9W/PnX3zC/uFTuEa VJcRoV1dC8iSRawyFcGv4dqe1tvHrqpFS1EFbX1zE+dQvT0hVlpNSyzvc+exR9zz8n zUmbVL8ELv81grHxSbTK/lrtuWNDYibBZ14iSSEQlP6PGbIpZTadzkg/6Fdr1PaBvI cCLYgIYa7TKsFAYNdtdpn6vaYF9CYCREQTxkBS/gPySZb42SvIvDhYNQRsQBlkal3i R/cSWka137oI8LAOQF7VDDiDwHrw3Si/l9eFl5CtZzhmQa2DZlynfXut28/8C/JOMz 7+5SRKAAAAAElFTkSuQmCC
```
Korvaa base64-koodipätkä omallasi, ellet halua omenaa ikoniksi.

**Comment by lmstrand** [comment]
ksdev/ks-0050-K22-18-ks-images -branchin voi tiputtaa versionvaihdossa. Ikonit/kuvat/linkit palvelimelle voi korvata ja kuvat näyttää base64-muodossa tekemällä tarvittavat muutokset järjestelmäasetuksiin.

**Comment by AnneliO** [comment]
Dokumentoin IntranetFavicon-järjestelmäasetuksen ohjeen Koha-Suomen verkkosivuille Ohjeet-osioon -> Järjestelmäasetukset -> [IntranetFavicon](https://koha-suomi.fi/dokumentaatio/jarjestelmaasetukset/#intranetfavicon)

**Comment by ReettaSiili** [comment]
Siiliin sain ohjeilla hyvin tehtyä tuon logon vasempaan yläkulmaan, mutta IntranetFavicon-asetuksen kuva ei oikein tyydytä ikonina, kunnan logo on siinä aivan liian pieni ja epäselvä.

**Comment by LeenaKinnunen** [comment]
Sain tehtyä myös logon, mutta se on suttuinen. Kannattaako alkuperäisen kuvan olla iso vai pieni, että se asettuisi paremmin?

**Comment by AnneliO** [comment]
> Sain tehtyä myös logon, mutta se on suttuinen. Kannattaako alkuperäisen kuvan olla iso vai pieni, että se asettuisi paremmin?

En osaa sanoa, mutta kokeilitko säätää CSS-rimpsussa korkeutta ja leveyttä, jos ne on vaikka vähän väärät?

**Comment by LeenaKinnunen** [comment]
Jep, kokoa muuttamalla onnistui.
