### ISSUE TITLE
Asiakastiedon valittavien asiakastyyppien järjestys uutta asiakastietoa lisätessä

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-23x#36]
### Mikä vikana?

MIten saisi uuden asiakastiedon lisäyksessä asiakastyypit aakkosjärjestykseen asiakastyypin nimen mukaan?

![kuva](https://user-images.githubusercontent.com/99952449/223031726-3337b850-c140-4988-a86b-fa32a4bf4320.png)

Esimerkiksi kuvailupohjien järjestys kuvailu-toiminnossa on kuvailupohjan kuvauksen mukaan
![kuva](https://user-images.githubusercontent.com/99952449/223032735-3d65ead3-1c6b-49a2-bed1-f94e3de9a0c2.png)

**Comment by AnneliO** [comment]
Huomattu myös, että *tuotannossa* asiakashaussa _Hae asiakkaita_ -kohdassa oikeassa reunassa Asiakastyyppi-valikossa myös asiakastyypit järjestyvät kuvauksen, ei tunnuksen mukaan.

![kuva](https://user-images.githubusercontent.com/33121325/223063148-7b3c56d4-830b-4789-94c6-6676b134f43c.png)

**Comment by AnneliO** [comment]
Ja myös tuo sama valikko on nykyisessä versiossakin samassa tunnuksen mukaisessa järjestyksessä.

![kuva](https://user-images.githubusercontent.com/33121325/223084896-5472f3de-f325-437f-a26b-75b0adc73e9b.png)

Tämä ei siis ole versionvaihtoon liittyvä ongelma, joten siirrän tiketin Koha-repositorioon kehitysehdotukseksi. :)

**Comment by emta001** [comment]
Yhteisössä nämä vaikuttaisivat järjestyvän kuvauksen mukaan, voidaan kaivella sieltä korjaus. Toki jos tämä ei ole mikään tulenpalava ongelma, niin voidaan odotella seuraavaa versionvaihtoakin.

**Comment by emta001** [comment]
Yhteisön tiketti [32127](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=32127).

**Comment by Kati-Helle** [comment]
> Yhteisössä nämä vaikuttaisivat järjestyvän kuvauksen mukaan, voidaan kaivella sieltä korjaus. Toki jos tämä ei ole mikään tulenpalava ongelma, niin voidaan odotella seuraavaa versionvaihtoakin.

Seuraava versionvaihto ok ajankohta tälle. Sopii myös muille kimpoille. (Kysyin tänään 11.7.2023 pääkäyttäjäpalaverissa.)

**Comment by Kati-Helle** [comment]
Helle-Nextillä asiakastyypit aakkostuvat oikein uutta asiakastietoa lisätessä 
![Image](https://github.com/KohaSuomi/Koha-23x/assets/99952449/9ac3c8a7-6fa1-4039-862a-530c11591b42)

**Comment by pknuuti** [comment]
Vaaran nextillä myös asiakastyypin nimen mukaan järjestyksessä, ei tunnuksen.

**Comment by iinaniemi** [comment]
Vaskin nextillä myös aakkostuvat asiakastyypin nimen mukaan
