### ISSUE TITLE
Työkalut/Asiakkaan muokkaus eräajona -toiminto: Asiakasmääre-kentän vieressä oleva Uusi-painike ei lisää uutta Asiakasmääre-kenttää

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha-23x#37]
### Mikä vikana?

Asiakkaiden muokkaus eräajona -toiminnossa on Asiakasmääre-kentän vieressä Uusi-painike, jota klikkaamalla pitäisi saada lisättyä uusi Asiakasmääre-kenttä.

![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/1f2c22cd-39fc-4d8b-8e21-3061dfabb72e)

Nyt Uusi-painikkeen klikkaus ei lisää uuttaa Asiakasmääre-kenttää, vaan klikkaus vie toimintosivun alkuun. Myös englannikielisessä Kohassa.

Koha 22.11 -manuaalissa kerrotaan tämä:

![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/bde21ca6-e9ec-4217-9b23-b3083e4be5a8)

**Comment by AnneliO** [comment]
Testasin tätä PTFS Europen sandboxissa (versio 23.06) ja siellä Uusi/New-linkki toimii normaalisti. En löytänyt myöskään bugzillasta tähän liittyvää tikettiä.

**Comment by AnneliO** [comment]
@Kati-Helle testaatko, rikkooko joku meidän oma javascript tämän toiminnon? Eli kaikki pois IntranetUserJS:stä (ja CSS:stä) ja uusi testaus. :)

**Comment by Kati-Helle** [comment]
Testasin Helle-testissä rimpsuja poistamatta. 

Uuden/uusia Asiakasmääre-kenttiä saa nyt lisättyä.

Asiakasmääre-kenttään valitsin arvon Käyttökieli 
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/5a685e4c-364e-4091-b418-50f87096c5ce)

Lisäsin Uusi-painikkeella toisen Asiakasmääre-kentän
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/9c871e96-9d7f-41a7-98eb-56e31c1e619a)

Kun valitsin tälle toiselle Asiakasmääre-kentälle vain Automaatti-asiakastyypille kuuluvan asiakasmääreen, tuli asiakasmääreen tyyppikohtaisuudesta maininta molempiin lisättyihin asiakasmääreisiin (kuten pitäneekinkö?)
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/9c1e11c3-20c2-4f76-810a-91790e714e27)

**Comment by AnneliO** [comment]
Testasin outi-testillä ja siellä ei pysty edelleenkään lisäämään useampaa asiakasmäärettä. Sivu hyppää sivun alkuun, kun klikkaa Uusi-painiketta.

**Comment by Kati-Helle** [comment]
No jopas, nyt kun testaan Helle-testissä uudestaan, ei uuden Asiakasmääre-kentän lisäys enää onnistukaan.
Kokeilin eri asiakastyypeillä.

**Comment by Kati-Helle** [comment]
Testasin poistamalla IntranetUserCSS-rimpsut ja IntranetUserJS-rimpsut. Ei auttanut, sillä Asiakasmääre-kentän lisääminen ei onnistu. Uusi-painikkeesta hyppäys toimintosivun alkuun.

**Comment by Kati-Helle** [comment]
Nextillä testaus: uuden Asiakasmääre-kentän lisäys onnistuu Uusi-painikkeella.

Pieni Helle-erikoisuus. Tuon ihmettelyn aika lienee myöhemmin :)
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/46365cf0-aad5-4668-aad9-bbc0d477f72d)

**Comment by AnneliO** [comment]
> Pieni Helle-erikoisuus. Tuon ihmettelyn aika lienee myöhemmin :) ![kuva](https://private-user-images.githubusercontent.com/99952449/297038512-46365cf0-aad5-4668-aad9-bbc0d477f72d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MDczNDUsIm5iZiI6MTcwNTQwNzA0NSwicGF0aCI6Ii85OTk1MjQ0OS8yOTcwMzg1MTItNDYzNjVjZjAtYWFkNS00NjY4LWFhZDktYmJjMGQ0NzdmNzJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDEyMTA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmOGRhMTczZjkxYTMyNWQwY2ZiZTc3ZThkMTlhYWEwMWE0ZWY4YWI3ZWQ5N2IyYjEwNTc5MzA0MzJjMDA4YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a5T4FOwIdW58173-XCQ5gYGLQjGYhIY3QbpGrkFotWQ)

Tuo on käännösjuttu. Tekisitkö siitä erillisen tiketin tänne 23x-version tietovarantoon? :)

**Comment by AnneliO** [comment]
> Tuo on käännösjuttu. Tekisitkö siitä erillisen tiketin tänne 23x-version tietovarantoon? :)

Kysyin tuosta Koha-yhteisön ircissä. Tää oli itseasiassa ihan bugi, jonka Joubu korjasi ja [laittoi sign offattavaksi](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=35817). Eli tuossa Äidinkieli-sanan tilalla pitäisi olla se asiakastyyppi, jolle määre on rajoitettu. :)

**Comment by Kati-Helle** [comment]
Tiketti on nyt 23x-version tietovarannossa.
