### ISSUE TITLE
Kellutusryhmät - ksdev/ks-0010-bug-9525-floatgroups

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#4]
### Siirrettävä ominaisuus

Yhteisöön ehdotettu ominaisuus, jolla kirjastoille voidaan määritellä kellutusryhmät.

![kuva](https://github.com/KohaSuomi/Koha-23x/assets/33121325/0aab0038-4300-4c84-a80f-cd1893eba922)

**Comment by AnneliO** [comment]
Asiantuntijaryhmä 12.10.2023: Jos kellutus voidaan toteuttaa pelkästään floatrules-asetuksella, niin sitten voidaan luopua varausryhmistä.

**Comment by AnneliO** [comment]
Varausryhmät ovat yhteisössä, tarvitsee vain testauksen uudessa versiossa.

**Comment by emta001** [comment]
Testailin ja vaikuttaisi toimivan kuten pitää. Laitan tämän "Testattava" tilaan.

EDIT. Enpä laitakkaan, kun tää olikin jo "Testattava" :D

**Comment by Kati-Helle** [comment]
Helle-nextillä Kellutusryhmät toimii oikein. 
Porvoon kirjastojen aineisto kelluu Porvoon kirjastoissa kuten kirjastoryhmään on määritelty.
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/a59cb617-1154-4de3-99bf-11dbc08bf5c9)

**Comment by ajrajala** [comment]
Vaksi-nextillä testattu myös tekemällä kellutusryhmä kirjastoille, joille ei ole mitään floatrules-sääntöä. Aineisto jää kellumaan kirjastojen välillä kuten kuuluukin.

**Comment by emta001** [comment]
Testattu ja toimii.
