### ISSUE TITLE
Aineistotyyppi näkyviin asiakkaan lainoihin ja palautustoimintoon - ksdev/ks-0074-K22-23-checkouts-and-returns-itemtype

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-23x#40]
### Siirrettävä ominaisuus

Aineistotyyppi näkyviin asiakkaan lainoihin ja palautustoimintoon.

**Comment by Kati-Helle** [comment]
Helle-Nextillä tietueen aineistotyyppi näkyy niteen palautuksessa Aineistotyyppi-sarakkeessa
![Image](https://github.com/KohaSuomi/Koha-23x/assets/99952449/f8b346c9-c18c-415c-927d-2c82d94bd8c7)

sekä asiakkaan lainoissa Aineistotyyppi-sarakkeessa
![Image](https://github.com/KohaSuomi/Koha-23x/assets/99952449/0a04c3d5-5771-4c62-a96b-49230b48e39f)

**Comment by AnneliO** [comment]
> sekä asiakkaan lainoissa Aineistotyyppi-sarakkeessa ![Image](https://private-user-images.githubusercontent.com/99952449/298569998-0a04c3d5-5771-4c62-a96b-49230b48e39f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MjM2OTksIm5iZiI6MTcwNTkyMzM5OSwicGF0aCI6Ii85OTk1MjQ0OS8yOTg1Njk5OTgtMGEwNGMzZDUtNTc3MS00YzYyLWE5NmItNDkyMzBiNDhlMzlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDExMzYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzZDUwNmYwNjIwYWE3N2IxZGU4MTdiZDRkMDQ0Mzk3ZDc4YmFhM2E3ZjRlZGM2ZTMwNDJjNTJkZTczY2Q2MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5VV-BlEeV_lIfsOKUzctD2Xzjj2IrnuoCMMNlRBz8_0)

Tässä näyttäisi näkyvän aineistotyypin koodi, ei kuvaus.

**Comment by iinaniemi** [comment]
Vaski-nextillä näyttää samalta kuin Hellessä.

**Comment by ElinaUotila** [comment]
Kirkes-nextillä myös, eli palautuksessa aineistotyypin kuvaus ja asiakkaan lainoissa aineistotyypin koodi.

**Comment by emta001** [comment]
Todettu toimivaksi, suljen tiketin.

**Comment by Kati-Helle** [comment]
Helle-Nextillä asiakkaan lainoissa näkyvillä edelleen aineistotyypin auktorisoitu arvo (eikä kuvaus)
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/9510b461-2ebc-40d4-b1fa-ecf7923ad99c)

**Comment by emta001** [comment]
Oon sitten näköjään onnistunut ymmärtämään lukemani täysin väärin ja todennut, että tää toimii kuten pitää. Vasta nyt kun rupesin tunkkaamaan tätä uuteen versioon, tajusin että eihän tää ihan toimikaan kuten pitää :sweat_smile:
