### ISSUE TITLE
Suomi.fi-palvelua ei voi lisätä asiakkaan viestiasetuksiin - ksdev/ks-0076-K22-24-suomifi-msg-prefs

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-23x#41]
### Siirrettävä ominaisuus

Suomi.fi-palvelua ei voi lisätä asiakkaan viestiasetuksiin.

**Comment by pknuuti** [comment]
Vaaran nextillä testattu: asiakkaan tiedoissa voi valita Suomi.fi-palvelun viestiasetuksissa.
