### ISSUE TITLE
Tietueen Varaukset-sivulla asiakas-sarakkeen tietoja ei ladata jos käyttäjältä puuttuu edit_borrowers-oikeus-  ksdev/ks-0080-bug-32502-api-holds-permission

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-23x#42]
### Siirrettävä ominaisuus

Jos käyttäjällä ei ole edit_borrowers-oikeutta, mitään asiakas-sarakkeessa olevia tietoja ei ladata. APIa muutettu niin, että tiedot ladataan kun käyttäjällä on view_borrower_infos_from_any_libraries-oikeus.

**Comment by ajrajala** [comment]
Testasin Varaukset-sivun katselua käyttäjätunnuksella, jolla borrowers-oikeuksista ainoastaan view_borrower_infos_from_any_libraries -käyttöoikka. Asiakas-sarakkeeseen latautuu kirjastokortti-linkki kuten kuuluukin.

**Comment by pknuuti** [comment]
Vaaran nextillä testattu toimivaksi (kuten ajrajala mainitsee).

**Comment by ReettaSiili** [comment]
Siilin nextillä asiakastieto latautuu asiakas-sarakkeeseen pelkällä view_borrower_infos_from_any_libraries-oikeudella. Linkistä ei kuitenkaan pääse katsomaan asiakastietoja ilman edit_borrowers-oikeutta. Menikö siis oikein?

**Comment by ghost** [comment]
Ilmeisesti ennenkin toiminut näin kuin Siilillä. Voisi olla käyttäjäystävällisempää että korttinumero ei edes näkyisi linkkinä jos edit_borrowers-oikeus puuttuu. Ei toistaiseksi kuitenkaan lähdetä selvittämään kuinka työlästä olisi korjata.

**Comment by AnneliO** [comment]
Kohassa yleisesti ottaen voi olla olemassa linkkejä toimintoihin, joihin käyttäjällä ei ole oikeuksia. Niitä klikatessa tulee tosiaan kirjautumisikkuna (kuten tässä tapauksessa käy) ja kerrotaan, ettei käyttäjällä ole tarvittavia oikeuksia. Tarkoitus olisi silloin kirjautua sellaisilla tunnuksilla joilla on oikeus kyseiseen toimintoon.

view_borrower_infos_from_any_libraries-käyttäjäoikeus ei anna oikeutta hakea, katsoa tai muokata asiakkaita, joten "uloskirjautuminen" on oikea lopputulos tässä tapauksessa. :)

**Comment by ghost** [comment]
Eiköhän tätä ole testattu tarpeeksi, suljen tiketin.
