### ISSUE TITLE
Raporttien kyselyiden siirtäminen tietokantaslavelle - ksdev/ks-0082-K22-163-altdbh

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-23x#43]
### Siirrettävä ominaisuus

Tietokantapalvelimella on suhteellisen paljon kuormaa. Tästä noin 20-25% aiheutuu pelkästään hyllyvarausraporttien generoinnista kaikille kimpoille. Samaan aikaan tietokantaslave ei tee käytännössä mitään. Järkevä toimintatapa tässä on raporttikyselyjen siirtäminen tietokantaslaven hoidettavaksi. Silloin raskaillakaan tietokantakyselyillä ei olisi vaikutusta Kohan päivittäiskäyttöön ja kuormaa master ja slave -palvelinten välillä saataisiin tasattua.

Muutentaan ensi vaiheessa Koha-Suomi spesifi hyllyvarausraportti käyttämään valinnaisesti tietokantaslavea, jolloin kuormaa saadaan tasattua jo heti tässä vaiheessa varsin pienillä toimenpiteillä.

Jatkossa siirretään myös muiden raporttien ajo valinnaisesti slave-palvelimelle. Tästä on yhteisön bugzillassa tiketti https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=29938

**Comment by AnneliO** [comment]
Toimii
