### ISSUE TITLE
Elasticsearch: mappings-tiedosto Koha-repositorion alle - ksdev/ks-0084-K22-105-elasticsearch_mappings

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-23x#45]
### Siirrettävä ominaisuus

Koha-Suomen omat mappings-tiedostot.

**Comment by CodoDerDritte** [comment]
Siirretty koha-repositorion sijasta utilityn alle etc/ -hakemistoon. Siellä on nyt myös koha-oai.conf. Tätä paikkaa voidaan jatkossa käyttää konttien kesken jaetuille konfiguraatiotiedostoille.
