### ISSUE TITLE
Keskeytä kaikki varaukset, Jatka kaikki keskeytetyt varaukset -toiminnot eivät toimi muilla kuin superlibrarianeilla - ksdev/ks-0094-bug-30732-holds-permissions

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-23x#46]
### Siirrettävä ominaisuus

Varausten massamuokkaus (Keskeytä kaikki varaukset, Jatka kaikki keskeytetyt varaukset) ei onnistu uudessa versiossa vaikka henkilökunnan käyttäjätunnuksilla olevien varausten käsittely-oikeuksien pitäisi siihen hyvinkin taipua. Yrittäessä muokata Koha heittää ulos sanoen, että oikeudet eivät riitä: ”Virhe: sinulla ei ole oikeuksia tähän sivuun”.

Superlibrarian-oikeuksilla massamuokkaus onnistuu.

Varausten yksittäinen muokkaus onnistuu henkilökunnan tunnuksilla, joille on asetettu oikeus tehdä varauksia asiakkaille (place_holds), mutta ei siis massamuokkaus.

Ongelma ei liity Kohasession aikakatkaisuun.

**Comment by ghost** [comment]
Korjattu yhteisössä? Testattava.

**Comment by AnneliO** [comment]
Linkkaatko Lasse yhteisön tiketin?

**Comment by ghost** [comment]
Tiketistä ei tietoa mutta koodi näyttää nyt tältä (rivillä 33 `reserveforothers => '*'` kuten meidän muutoksessa):

https://github.com/KohaSuomi/Koha-23x/blob/ks23/reserve/modrequest_suspendall.pl

**Comment by Kati-Helle** [comment]
Helle-Nextillä toimii myös ei-superlibrarian-tunnuksella

Asiakkaalla varauksia kaksi
![Image](https://github.com/KohaSuomi/Koha-23x/assets/99952449/b22e37c9-69f3-465f-9812-a1d79e93d35e)

Valitsin Keskeytä kaikki varaukset (ilman päivämäärää)
![Image](https://github.com/KohaSuomi/Koha-23x/assets/99952449/3c1ffdb3-8ea0-447b-8ce0-d8715facea25)

Valitsin Jatka kaikki keskeytetyt varaukset
![Image](https://github.com/KohaSuomi/Koha-23x/assets/99952449/a96c8961-45d8-4864-a337-ba77831c8239)


Toimii oikein myös päivämäärän kanssa, eli määrittelemällä päivämäärän, jolloin varauksia jatketaan.

**Comment by pknuuti** [comment]
Vaaran nextillä testasin ei-superlibrariantunnuksella asiakkaalla, jolla oli useampi varaus https://vaara-next.koha-suomi.fi/cgi-bin/koha/circ/circulation.pl?borrowernumber=1068373 
Varausten keskeyttäminen onnistui ihan oikein. Kun klikkasin "Jatka kaikki keskeytetyt varaukset", ohjelma heitti käyttäjän ulos "Virhe. Sinulla ei ole oikeuksia tähän sivuun". Kun palasin selaimen nuolinäppäimellä takaisin asiakkaan varausten näkymään ja päivitin sivun, varaukset olivat päällä eli keskeytys oli poistettu. Joku ongelma tässä siis vielä on.
***HUOM! Ongelma oli tunnusten antajassa eli puuttui yksi asiakastietojen oikeus. Kun lisäsin sen, toimi kuten pitikin. Tulipahan testattua :)

**Comment by Kati-Helle** [comment]
Testasin Helle-Nextillä uudestaan ei-pääkäyttäjäoikeuden omaavalla tunnuksella ja toimii edelleen.

**Comment by ajrajala** [comment]
Myös vaski-nextillä toimii halutulla tavalla.
