### ISSUE TITLE
Taustatöiden työlistalla "Only include jobs started in the last hour" -valinta toimii väärin - ksdev/ks-0095-K22-170-fix-background-jobs-filters

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-23x#47]
### Siirrettävä ominaisuus

Taustatöiden listalla taas jos ottaa täpän pois kohdasta Only include jobs started in the last hour, katoaa listalta työt lähitunneilta/lähiajalta kokonaan.

Tämä pitäisi testata yhteisössä ja mahdollisesti etsiä/tehdä sinne bugiraportti.

**Comment by johannaraisa** [comment]
Taisi löytyä tälle [yhteisöbugi](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=36217).

**Comment by ajrajala** [comment]
Testailin täppiä Taustatyöt-sivulla. Nyt "Only include jobs enqueued in the last hour" -täpän laittaminen/poistaminen käyttäytyy minusta oikein.

**Comment by pirliis** [comment]
Testasin myös OUTIssa, kohata "Sisällytä vain taustatyöt, jotka on aloitettu viimeisen tunnin aikana" näyttäisi toimivan oikein.

**Comment by johannaraisa** [comment]
Tämän voinee siis sulkea.

**Comment by emta001** [comment]
Tähän liittyen, tuon meillä olevan korjauksen voisi viedä yhteisöön.
