### ISSUE TITLE
Korjaus valuebuilder-pluginien toistuville kentille - ksdev/ks-0097-K22-bug-30975-framework-plugins-cloned-subfield-fix

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-23x#48]
### Siirrettävä ominaisuus

Finto-plugit korjaus.

Sisältää bugit 30975, 32813 ja 33744, jokainen tarkistettava erikseen onko jo yhteisössä.

**Comment by johannaraisa** [comment]
30975 on Failed QA -tilassa, muut ovat jo versiossa 23.11

**Comment by johannaraisa** [comment]
Meillä ei ole tuotannossa aktiivisena kuin tuo 33744, sillä nuo muut kommitit on revertoitu branchistä. Emme siis tarvitse tätä, sillä tuo löytyy jo yhteisön versiosta.
