### ISSUE TITLE
Add cancellation reason to holds delete endpoint - ksdev/ks-0013-bug-30660-holds-del-endpoint 

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#5]
### Siirrettävä ominaisuus

Varauslistan sivutukseen tarvittava endpoint. Mahdollistaa peruutuksen syyn lisäämisen varauksen poiston yhteydessä.

**Comment by AnneliO** [comment]
Asiantuntijaryhmä 12.10.2023: Asiantuntijat kyselevät kimpoista, onko tarvetta lisätä peruutuksen/poiston syytä.

**Comment by ajrajala** [comment]
Vaskissa ei tarvetta lisätä peruutuksen syytä varauksen poiston yhteydessä.

**Comment by pknuuti** [comment]
Vaarassakaan ei ole tarvetta peruutuksen syyn lisäämiseen.

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 20.11.2023: Ei siirretä
