### ISSUE TITLE
Finto-plugit - ksdev/ks-0099-K22-22-Finto-value-builders

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-23x#50]
### Siirrettävä ominaisuus

Finto-plugit.

**Comment by johannaraisa** [comment]
Testaussuunnitelma:

1. Tee kuvailutietue tati-nextille.
2. Kokeile toimiiko Finto-plugit kentissä:
    1. 100$a, finto_finaf.pl           
    2. 382$a, finto_seko_nouri_noind.pl
    3. 655$a, finto_slm-local.pl       
    4. 648$a, finto_yso-aika_noind.pl  
    5. 388$a, finto_yso-aika.pl        
    6. 385$a, finto_yso-kauno_noind.pl 
    7. 650$a, finto_yso-kauno.pl       
    8. 257$a, finto_ysopaikat_noind.pl 
    9. 651$a, finto_ysopaikat.pl

**Comment by pknuuti** [comment]
Kuvailija testasi näitä plugareita Täti-nextillä ja ilmoitti kaikkien toimivan.

**Comment by ajrajala** [comment]
Myös Vaskin kuvailija tehnyt testauksen, todettu toimiviksi.

**Comment by johannaraisa** [comment]
Hyvä juttu, suljen tiketin.
