### ISSUE TITLE
Do not try to notify RabbitMQ of new enqueued jobs - ksdev/ks-0105-on-0104-K22-543-rabbitmq-warnings

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-23x#51]
### Siirrettävä ominaisuus

Kohan background_jobs_worker yrittää yhdistää RabbitMQ:hun jota meillä ei ole käytössä. Tästä tulee lokeihin runsaasti turhia varoituksia.

**Comment by AnneliO** [comment]
Branch 104 pitää pudottaa, jotta voidaan testata RabbitMQ:ta.

**Comment by ghost** [comment]
104 pudotettu jo nexteiltä (muutokset mukana masterissa), 105 pitää myös pudottaa jos RabbitMQ:ta testataan tai otetaan käyttöön.

**Comment by ghost** [comment]
Pidetään toistaiseksi mukana, kehittäjät testaavat.

**Comment by AnneliO** [comment]
Toimii
