### ISSUE TITLE
Turhien asiakastietojen piilotus - ks-0107-KD-G571-hide-table-borrowers-unwanted-fields

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-23x#52]
### Siirrettävä ominaisuus

Asiantuntijaryhmän palaverissa päätetty, että:
"Otetaan pois nykyinen hakutulostaulukon piilotus ja piilotetaan taulukosta syntymäaika, osoite ja puhelinnumero."

Taulukon sarakkeiden piilotusta ei siis tarvitse korjata. Korjataan yhteisössä ajallaan. Kovakoodataan näkyville vain sovitut kentät, jolloin kaikissa kimpoissa on sama halkutulosnäkymä riippumatta tauluasetuksista, jotka nyt eivät muutenkaan toimi.

**Comment by AnneliO** [comment]
Testattava, onko korjattu yhteisössä.

**Comment by AnneliO** [comment]
Testaa näin:

1. Hae jokin teos.
2. Mene varauksen tekoon.
3. Hae asiakasta sellaisella hakusanalla, että saat useamman hakutuloksen.
4. Tarkista, että hakutulostaulukossa ei näy sarakkeita syntymäaika, osoite ja puhelinnumero.

**Comment by pknuuti** [comment]
Vaaran nextillä varaustilanteessa näkyy vain sarakkeet Nimi, Kortti, Tyyppi ja Kirjasto.
![2023kuvat 358](https://github.com/KohaSuomi/Koha-23x/assets/73887264/54ed5a0e-73c1-4d41-89ad-a6a2277de04d)

**Comment by Kati-Helle** [comment]
Helle-nextissä ei näy sarakkeita Syntymäaika, Osoite, Puhelinnumero.
Nämä sarakkeet näkyvät: Nimi, Kortti, Tyyppi, Kirjasto.

**Comment by MikkoLiimatainen** [comment]
Vaski-Nextillä sarakkeet Nimi, Kortti, Tyyppi ja Kirjasto, kuten kuuluukin.

**Comment by emta001** [comment]
Tämä toiminee. Suljen tiketin.
