### ISSUE TITLE
Asiakashaku-toimintoihin oletushakutyypiksi sama arvo - ksdev/ks-0108-KD-G556-set-contains-as-default-patron-search

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-23x#53]
### Siirrettävä ominaisuus

Hae asiakkaita - oletushakutyyppiksi on määritetty Sisältää, aiemmin se oli Alkaa.

Tarkistettava onko korjaantunut yhteisössä ja saako tiputtaa.

**Comment by johannaraisa** [comment]
Tätä saa säädettyä järjetelmäasetuksella, DefaultPatronSearchMethod:
![Screenshot 2024-03-11 at 11-30-24 System preferences › Administration › Koha](https://github.com/KohaSuomi/Koha-23x/assets/1818117/e581eb2e-598a-48e8-a00e-9fdfdbfdcd72)

**Comment by johannaraisa** [comment]
Tässä samaisessa kehityshaarassa oli toinenkin kommitti, joka ei liity tuohon oletushakutyyppiin. 
https://github.com/KohaSuomi/Koha-22x/commit/51f5aaad31ec81259ed283a5166708666b148963
Halutaanko vielä piilottaa kenttiä, siitä varmaan pitäisi tehdä toinen tiketti?

**Comment by johannaraisa** [comment]
> Tässä samaisessa kehityshaarassa oli toinenkin kommitti, joka ei liity tuohon oletushakutyyppiin. [KohaSuomi/Koha-22x@51f5aaa](https://github.com/KohaSuomi/Koha-22x/commit/51f5aaad31ec81259ed283a5166708666b148963) Halutaanko vielä piilottaa kenttiä, siitä varmaan pitäisi tehdä toinen tiketti?

Tämä löytyykin jo haarasta: https://github.com/KohaSuomi/Koha-23x/commits/ksdev/ks-0107-KD-G571-hide-table-borrowers-unwanted-fields/

Emme siis tarvitse tätä kommittia enää.
