### ISSUE TITLE
Vanhenemispäivä jää puuttumaan varaukselta, jolta perutaan odottaa tai kuljetettavana -tila - ksdev/ks-0109-bug-34032-expirationdate-blank

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-23x#54]
### Siirrettävä ominaisuus

Mikäli varaus on jo tärpännyt noudettavaksi tai kuljetettavaksi noutopaikkaan, mutta tila joudutaan vielä peruuttamaan, ei varaukselle muodostu automaattisesti uutta vanhenemispäivää vaan kenttä jää tyhjäksi.

**Comment by Kati-Helle** [comment]
Helle-nextissä varauksen Vanhenee-kentän arvo muodostui perustuen varauksen Pvm-kentän arvoon
- kun peruin odottaa-tilaisen varauksen painikkeesta Peruuta odottaa-tila
- kun peruin kuljetettavana-tilaisen varauksen painikkeesta Peruuta kuljetustila

**Comment by pknuuti** [comment]
Myös Vaaran nextillä sama havainto kuin Hellessä, päivämäärät pysyivät ennallaan eivätkä tyhjentyneet. Testattu molemmat tavat, kuljetettava tai noutokirjastossa palautettu.

**Comment by sksandel** [comment]
Vaskin nextillä testattu kuljetettavan ja noudettavan varauksen peruminen. Vanhenee-kentän arvo säilyi tai päivittyi oikein. Jos noudettavan perui, sai varaus alkuperäisen vanhenemisarvonsa takaisin.

**Comment by ElinaUotila** [comment]
Kirkesissä testattu myös molemmat tavat, ja vanhenee-kentän arvo säilyi tai päivittyi oikein molemmissa.

**Comment by emta001** [comment]
Testattu toimivaksi, suljen tiketin.
