### ISSUE TITLE
Takaajan "suhde" putoaa pois jos asiakastietuetta ei voi tallentaa jo käytössä olevan varaustunnuksen takia - ksdev/ks-0115-bug-26558-guarantor-info-lost

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-23x#56]
### Siirrettävä ominaisuus

Jos asiakkaalle on lisäämässä takaajaa ja yrittää lisätä jo olemassa olevaa varaustunnistetta, niin kaikki muut tiedot säilyvät, mutta huoltajan "suhde" putoaa pois.

**Comment by emta001** [comment]
Ominaisuus on viety yhteisön masteriin ja se julkaistaan luultavasti versiossa 23.11.

**Comment by emta001** [comment]
Tämä on valmiina uudessa versiossa, testasin omilla testeillä ja toimii kuten pitää. Laitan tilaksi "Testattava", niin varmistetaan sillä vielä, että kaikki toimii kuten pitää.

**Comment by Kati-Helle** [comment]
Lisäsin olemassa olevalle lapsi-asiakastiedolle toisen takaajatiedon.
Ennen lapsi-asiakastiedon tallennusta vaihdoin lapsi-asiakastiedolle varaustunnuksen, joka on tallennettuna toiselle asiakkaalle.

Tallenna-painikkeesta Koha ilmoittaa
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/4c4b778b-0fc3-4d09-872c-1ac82295c453)

Jo lapsi-asiakastiedossa aiemmin tallennetun takaaja-tiedon ja uuden nyt lisätyn takaaja-tiedon suhde takaaja pysyy eikä poistu
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/ccecac92-936b-4082-9687-6aefed801128)

**Comment by ajrajala** [comment]
Huoltajan suhde näyttäisi säilyvän kuten pitää. Huomasin, että viestiasetukset tippuvat pois jos yrittää tallentaa ei-uniikilla varaustunnisteella. Tämä tapahtuu tuotannossakin. Teenkö tästä tiketin versionvaihdon alle vai ihan normitiketin?

**Comment by AnneliO** [comment]
> Huoltajan suhde näyttäisi säilyvän kuten pitää. Huomasin, että viestiasetukset tippuvat pois jos yrittää tallentaa ei-uniikilla varaustunnisteella. Tämä tapahtuu tuotannossakin. Teenkö tästä tiketin versionvaihdon alle vai ihan normitiketin?

Jos tapahtuu tuotannossakin, niin sitten normitiketti. :)

**Comment by emta001** [comment]
> Huoltajan suhde näyttäisi säilyvän kuten pitää. Huomasin, että viestiasetukset tippuvat pois jos yrittää tallentaa ei-uniikilla varaustunnisteella. Tämä tapahtuu tuotannossakin. Teenkö tästä tiketin versionvaihdon alle vai ihan normitiketin?

Tästä on muistaakseni jo olemassa tiketti... [#KS-839](https://github.com/KohaSuomi/Koha/issues/839) näemmä.

**Comment by emta001** [comment]
Testattu ja toimii. Ihmetellään viestiasetusten häviämistä omassa tiketissään.
