### ISSUE TITLE
Veloitusaika muuttuu automaattisesti laina- ja maksusäännöissä muita saman rivin sääntöjä muokatessa - ksdev/ks-0116-bug-34585-circrule-whentocharge-column

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-23x#57]
### Siirrettävä ominaisuus

Kun laina- ja maksusäännöissä alkaa muokata jotain yksittäistä sääntöä, ko. nidetyypin Veloitusajankohta-sarakkeessa pudotusvalikon valinta hyppää oletuksena kohtaan "Aikavälin loppupäivä".

**Comment by Kati-Helle** [comment]
Helle-nextillä otin muokkaukseen laina- ja maksusääntöjen viimeisen sääntörivin. 
Tämä ei muuttanut veloitusaikaa.
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/993d6785-e9a8-40cd-b5d9-92ad809c678b)

Veloitusaikaa ei myöskään muuttanut säännön muokkauksessa tekemäni muutos (Maksun määrä)
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/1e01e55f-1fd9-40e7-a8d3-48d9bda8f523)

Eikä tallennettu muokattu sääntö (Maksun määrä)
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/8b59d272-419a-4553-a953-8effcdd1d73d)

**Comment by iinaniemi** [comment]
Vaski-nextillä en saanut myöskään pudotusvalikkoa hyppäämään oletuksella Jakson loppuun. Jos vaihdoin valinnan Jakson alkuun, se pysyi siinä vaikka otin uudelleen muokkaukseen.

**Comment by emta001** [comment]
Vaikuttaisi siis toimivan kuten pitää. Suljen tiketin.
