### ISSUE TITLE
Järjestelmäsetus: BorrowerCategoryTimeout - ksdev/ks-0120-on-0024-K22-12-SCO-timeout

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-23x#58]
### Siirrettävä ominaisuus

Asiakastyyppikohtainen timeout, tehty Kohan itsepalvelulainausta (SCO:ta) varten.

**Comment by CodoDerDritte** [comment]
Yhdistetty #14 (ksdev/ks-0024-K23-14-auth-extra)

**Comment by CodoDerDritte** [comment]
Tämä näyttäisi olevan #27 duplikaatti, joten suljen.
