### ISSUE TITLE
Able to update more hold parameters via REST API - ksdev/ks-0014-bug-30661-holds-update-params

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#6]
### Siirrettävä ominaisuus

Varauslistan sivutukseen tarvittava endpoint.

**Comment by ghost** [comment]
Voidaan pudottaa jos otetaan käyttöön yhteisöversio varaussivusta.

**Comment by ghost** [comment]
Ei pudoteta vielä.
