### ISSUE TITLE
Asiakkaan Lainaus- ja Tiedot- välilehdelle näkyviin kaikkien maksujen summa - ksdev/ks-0122-on-0032-KD-G762-include-all-charges-for-totals-in-intranet

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-23x#60]
### Siirrettävä ominaisuus

Virkailijaliittymään halutaan näkyviin Lainaus- ja Tiedot- välilehdille asiakkaan kaikkien maksujen summa (julkisoikeudelliset + ei-julkisoikeudelliset). Tällä hetkellä vain julkisoikeudelliset maksut näkyvät kyseisissä näkymissä.

Tämän kehitys on vielä kesken nykyisessä versiossa.

**Comment by lmstrand** [comment]
Branchissa [ksdev/ks-0122-on-0032-KD-G762-include-all-charges-for-totals-in-intranet](https://github.com/KohaSuomi/Koha-23x/tree/ksdev/ks-0122-on-0032-KD-G762-include-all-charges-for-totals-in-intranet).
