### ISSUE TITLE
Asiakkaan lisääminen onnistunut ilman osoitetietoja - ksdev/ks-0125-bug-34671-fieldset-collapse-error

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-23x#62]
### Siirrettävä ominaisuus

Asiakkaan pystyy tallentamaan ilman vaadittuja tietoja, jos niiden fieldset on piilotettu.

Tämän kehitys on vielä kesken nykyisessä versiossa.

**Comment by AnneliO** [comment]
On korjattu jo.

**Comment by emta001** [comment]
Korjattu nykyiseen versioon 22, muttei yhteisöön eikä versioon 23.

**Comment by Kati-Helle** [comment]
Helle-Nextillä asiakkaan tallennus ei onnistu ilman osoitetietoja (muissa pakollisissa kentissä on arvo)
![Image](https://github.com/KohaSuomi/Koha-23x/assets/99952449/11b53f14-3efe-4093-a931-8518b0a5c20a)

**Comment by pknuuti** [comment]
Vaaran nextillä asiakkaan lisääminen ei onnistu ilman osoitetietoja, vaikka osoiteosio olisi pienennetty pois näkyvistä (vain otsikko näkyy). 
![2023kuvat 274](https://github.com/KohaSuomi/Koha-23x/assets/73887264/7a01706f-8e50-4031-b8b4-1a564de11a54)

**Comment by Kati-Helle** [comment]
Aa, testasin aiemmin väärällä tavalla Helle-nextillä. Testasin uudestaan.
Kun uuden tallentamattoman asiakastiedon Osoite-kokonaisuus on piilossa ja ilman pakollisia arvoja, ei asiakkaan tallennus onnistu
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/bb90994f-2203-4a79-91a1-292f4c74f1ce)

Lisähuomiona: klikkasin Tallenna-painiketta tässä kohtaa asiakastietolomaketta. Näkymäksi ei muuttunut virheilmoituskohta (piilotettuun Osoite-osioon)
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/edaa2d24-7fa5-48ea-88d8-3f3b7a1e4b22)

Kun Osoite-osion osoitetietokentät ovat tyhjinä ja näkyvillä, siirtyy näkymä Tallenna-painikkeesta Osoite-osioon, josta pakolliset täytettävät tiedot puuttuvat.

**Comment by ajrajala** [comment]
Vaski-nextilläkään ei anna tallentaa, jos piilotetusta osiosta on pakollinen kenttä täyttämättä.

**Comment by emta001** [comment]
Kolmen testin perusteella homma pelittää kuten pitää. Suljen tiketin.
