### ISSUE TITLE
Asiakkaan maksujen kokonaismäärän näkymisessä puutteita, kun käytössä on asetus ManInvInNoissuesCharge=Älä sisällytä - ksdev/ks-0110-KD-G301-exclude-debit-types-from-noissuecharge

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-23x#63]
### Siirrettävä ominaisuus

Asiakkaalle lisätyt kimpan omien maksutyyppien maksut eivät sisälly asiakkaan lainaus -toiminnossa eikä asiakkaan tiedot -näytöllä näkyviin maksuihin.

Tästä oli hieman epävarmuutta tarviiko koko branchia edes siirtää. Tutkitaan vielä tiputetaanko tämä.

**Comment by AnneliO** [comment]
Eikö tämä ole sama kuin #60?

**Comment by lmstrand** [comment]
Tämän voi tiputtaa. 23-versiossa järjestelmäasetukset on poistettu ja määrittely tehdään maksutyyppien yhteydessä uudella tavalla.

**Comment by lmstrand** [comment]
Commitit https://github.com/KohaSuomi/Koha-22x/commits/ksdev/ks-0110-KD-G301-exclude-debit-types-from-noissuecharge/ -branchista siis jo ks23-branchissa mukana.
