### ISSUE TITLE
KTRAN - Koha-translations 

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#66]
### Siirrettävä ominaisuus

Koha-Suomi translation files

**Comment by AnneliO** [comment]
14.3.2024 tuotu uusimmat suomenkieliset po-tiedostot Weblatesta.

19.3.2024 tuotu uusimmat ruotsinkieliset po-tiedostot Weblatesta.

**Comment by pirliis** [comment]
Olisiko suomennoksissa pitänyt tulla myös asiakkaan muokkaussivulle tehdyt käännösmuutokset:
Ensisijainen puhelin -> Lankapuhelin
Muu puhelin -> Matkapuhelin

**Comment by AnneliO** [comment]
> Olisiko suomennoksissa pitänyt tulla myös asiakkaan muokkaussivulle tehdyt käännösmuutokset: Ensisijainen puhelin -> Lankapuhelin Muu puhelin -> Matkapuhelin

Koha-Suomen omat käännökset puuttuvat vielä kokonaan. En ole niitä vielä tehnyt, koska esim. perustiedot-näytölle tehtävät muutokset ja lisäykset puuttuvat vielä tiedostoista. Teen sitten kerralla kaikki. :)

**Comment by AnneliO** [comment]
Yhteisön Weblatesta tuotu taas uusimmat suomenkieliset po-tiedostot.

**Comment by AnneliO** [comment]
Koha-Suomen muutokset viety testattavaksi.

**Comment by pknuuti** [comment]
Vaaran nextillä on asiakkaan tiedoissa Lankapuhelin ja Matkapuhelin.

**Comment by AnneliO** [comment]
Ainakin tällaisia voi vilkuilla:

* [Koha-Suomen muutokset käännöstiedostoihin](https://github.com/KohaSuomi/Koha-translations/wiki/Koha%E2%80%90Suomen-muutokset-k%C3%A4%C3%A4nn%C3%B6stiedostoihin)
* Asiakastiedoissa käännökset huomautukseen lainauskieltoon vaikuttavista maksuista.
* näkyykö jossain kääntymättömiä?

**Comment by pknuuti** [comment]
Vaaran nextillä näkyy Ilmoitus: kirje -teksti asiakkaalla, jolla ei ole viestiasetuksia määritelty noutoilmoituksen kohdalla.
