### ISSUE TITLE
koha-plugin-self-service (KPSS)

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-23x#69]
### Siirrettävä ominaisuus

Self-service permission API for Koha ILS

**Comment by AnneliO** [comment]
Toveri-liitännäinen. Vastuu Hypernovalla.

**Comment by lmstrand** [comment]
Kysytty viime viikolla yhteensopivuutta 23.11-version kanssa sähköpostilla, ei vielä vastausta.
