### ISSUE TITLE
Sivutus tietueen Varaukset-sivulle - ksdev/ks-0015-bug-23269-holds-page-REST

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#7]
### Siirrettävä ominaisuus

Sivutus tietueen Varaukset-sivulle, jotta paljon varauksia sisältävien tietueiden varaussivu avautuu.

**Comment by AnneliO** [comment]
Huomioidaan [version 22 tiketin 37](https://github.com/KohaSuomi/Koha-22x/issues/37) käännösongelmat, kun viedään ominaisuutta versioon 23. Tehdään mielellään niin, että muutoksen saisi vietyä yhteisöön.

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 20.11.2023: Siirretään

**Comment by ghost** [comment]
Nexteillä testattavana varaussivusta yhteisöversio johon lisätty sivutus.

**Comment by pknuuti** [comment]
Tällainen näkymä tulee Vaaran nextillä, kun varauksia on nimekkeestä enemmän kuin yksi sivullinen. Olettaisin siis, että toimii kuten pitää.

![Image](https://github.com/KohaSuomi/Koha-23x/assets/73887264/7684d92a-12a7-4db9-bb81-7647e60ffce5)

**Comment by AnneliO** [comment]
OUTI-nextillä tietueessa [Jakob / Satu Rämö](https://outi-next.koha-suomi.fi/cgi-bin/koha/reserve/request.pl?biblionumber=2301650), jossa on yli 1300 varausta, tulee varaussivulla Virhe 500.

[36 uurnaa / Satu Rämö](https://outi-next.koha-suomi.fi/cgi-bin/koha/reserve/request.pl?biblionumber=2304549), jossa on 921 varausta, varaussivu avautuu.

**Comment by pknuuti** [comment]
Vaaran nextillä oli niin vähän varauksia valmiiksi, että piti itse niitä tehdä. Outissa on ilmeisesti koko tuotannon aineisto?

**Comment by AnneliO** [comment]
Jeps, OUTI-next on redusoimaton, jotta pystytään testaamaan myös massoja. :)

**Comment by johannaraisa** [comment]
Tässä virhe: Template process failed: undef error - WHILE loop terminated (> 1000 iterations). Template Toolkit ei halua käsitellä yli 1000 objektin silmukoita. Tähän kyllä tarvitaan se backend-sivutus, ja voidaan perustella tuolla yhteisölle sitä tarvetta.

**Comment by johannaraisa** [comment]
Tai sitten määritellään maksimimäärä mitä kerralla haetaan, onko oikeasti tarpeellista nähdä kaikki yli 1000 varausta?

**Comment by ajrajala** [comment]
Sellaisia tilanteita voi olla, joissa tietueeseen on yli 1000 varausta ja asiakkaan varaus pitää jonon lopusta siirtää jonon kärkeen. Eli silloin tarve nähdä tietueen viimeisetkin varaukset.

**Comment by ajrajala** [comment]
Yhteisöversion sivutukseen liittyy myös se ongelma, että jos sivulla tekee varaukseen jonkin muutoksen (esim. noutopaikan vaihdon), muutos ei tallennu ilman että käyttäjä painaa "Päivitä varaukset" -nappia. Nykyisessä tuotantoversiossa muutos päivittyy varaukselle ilman erillistä napin painamista.

**Comment by AnneliO** [comment]
Nextillä on ilmeisesti nyt voimassa muutos, että pystytään näyttämään enemmänkin kuin 1000 tulosta taulukossa.

Kokeilin avata [Jakob](https://outi-next.koha-suomi.fi/cgi-bin/koha/reserve/request.pl?biblionumber=2301650)-teoksen taas ja sivu avautui. Siihen meni noin minuutti.

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 21.3.2024: Koska yhteisön toteutus sivutuksesta on todella hidas verrattuna Koha-Suomen omaan (OUTIn tuotannossa Jakob-tietueen avautumiseen meni n. 7 s, varauksia parisataa vähemmän), pidetään toistaiseksi käytössä meidän oma REST-rajapinnan kautta toteutettu versio.

**Comment by ghost** [comment]
Pidetään meidän versio ja jos kaikki toimii ei tehdä enempää muutoksia ennen versionvaihtoa.

**Comment by MikkoLiimatainen** [comment]
Vaski-nextillä toimii.

**Comment by pirliis** [comment]
OUTIn nextillä toimii.

**Comment by AnneliO** [comment]
Toimii, suljetaan.
