### ISSUE TITLE
KPOKM -	koha-plugin-OKM-stats 

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#70]
### Siirrettävä ominaisuus

Tilastoliitännäinen

**Comment by emta001** [comment]
Ajot toimivat kuten pitää ja raportit näkyvät käyttöliittymässä oikein. Testasin siis siili-nextillä. Tämän perusteella plugarin tulisi toimia kuten pitääkin, enkä tiedä tarvitseeko tätä tämän enempää testailla.

**Comment by emta001** [comment]
Mutta laitanpa tämän silti "Testattava"-tilaan ja neuvotellaan jatkosta vielä myöhemmin 😄

**Comment by Kati-Helle** [comment]
Helle-nextillä OKM-Tilastot  hakutulosta
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/c765aefa-e770-4e20-b8e4-3bdf72d15caf)


Asiakasmäärä ikäryhmittäin -hakutulosta
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/06e2c8df-fcde-4f1d-ab34-1f172b007cfd)

**Comment by emta001** [comment]
Käyn ajamassa kaikille nuo OKM-tilastot, niin saatte kateltua ne ainakin kokoelman osalta. Jos tulee tarve katella hankintoja tms. ja saatte niitä kantaan aikaiseksi, niin pyytäkää uusi ajo.

Ajo tehty:

- [x] Siili
- [x] Lumme
- [x] Kyyti
- [x] Helle
- [x] Kirkes
- [x] Vaara
- [x] Lappi
- [x] OUTI
- [x] Vaski

**Comment by MikkoLiimatainen** [comment]
Kokoelman osalta vaikuttaisi olevan kunnossa.

**Comment by Kati-Helle** [comment]
Helle-nextin kokoelmatietojen ja hankintatietojen arvoissa on muitakin arvoja kuin 0.

**Comment by emta001** [comment]
Tämä lienee kunnossa. Suljen tiketin.
