### ISSUE TITLE
KPODUE - koha-plugin-overdue-tool 

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#72]
### Siirrettävä ominaisuus

Laskutusliitännäinen

**Comment by ajrajala** [comment]
En varmastikaan keksinyt kokeilla kaikkea mitä pitäisi, mutta testasin seuraavia asioita:
- Laskun luominen Luo Finvoice ja Luo pdf -painikkeilla (myös useammalle kerralla) toimii; asiakkaalle muodostuu rajoitus ja laskutettu nide ei ole lainoissa uusittavissa
- Korvaushinnan muuttaminen toimii
- Laskujäljennöksen pystyy tulostamaan
- Laskutettu asiakas ei tule enää työkaluun näkyville ellei rastita kohtaa "Näytä laskutetut"
- Aikaväli-, asiakasryhmä- ja minimisummarajaus toimii

**Comment by pirliis** [comment]
Testailin OUTIssa myös laskutustyökalua. Muuten näytti toimivalta, mutta rajoituksen automaattinen poistuminen ei toiminut silloin, jos kaikki laskutetut lainat palautti, mutta asiakkaalle jäi lainaan vielä muita myöhässä olevia lainoja, joita ei ole laskutettu. Rajoitus poistui kyllä automaattisesti, jos asiakkaalle jäin lainaan vielä muita lainoja, jotka eivät olleet myöhässä.
Esim. lainaaja borrowernumber=363.

**Comment by pirliis** [comment]
Testasin rajoitteen automaattista poistumista myös niin, että kävin muuttamassa tämän järjestelmäasetuksen näin:
![image](https://github.com/KohaSuomi/Koha-23x/assets/98814860/81468d4f-14e1-450e-a44a-56dbb1dd1e00)
Ei näyttänyt olevan vaikutusta laskutetusta aineistosta johtuvaan rajoitukseen. Asetuksessahan kyllä puhutaan vain myöhästymisilmoituksesta. :)

**Comment by emta001** [comment]
> Testasin rajoitteen automaattista poistumista myös niin, että kävin muuttamassa tämän järjestelmäasetuksen näin: ![image](https://private-user-images.githubusercontent.com/98814860/323962245-81468d4f-14e1-450e-a44a-56dbb1dd1e00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3Njk2MDUsIm5iZiI6MTcxMzc2OTMwNSwicGF0aCI6Ii85ODgxNDg2MC8zMjM5NjIyNDUtODE0NjhkNGYtMTRlMS00NTBlLWE0NGEtNTZkYmIxZGQxZTAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA3MDE0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2MzY4MDA2MTFiYmMyODJjZWMxZmU5N2UzY2UxZjA2YzRlYTVkMzk1N2U4Y2EzOTIzZGViMjEzZDFmNjcyNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wRd5uyYj91immqwPHh25QIgRKE2ujdZ20xAQM1HT5OI) Ei näyttänyt olevan vaikutusta laskutetusta aineistosta johtuvaan rajoitukseen. Asetuksessahan kyllä puhutaan vain myöhästymisilmoituksesta. :)

Tuo asetus ei liity laskutusliitännäiseen. Liitännäinen tekee muita muutoksia, Anneli lupasi vilkaista mitä ne oli.

**Comment by pirliis** [comment]
Oulun laskuttajalta sain tänään tiedon, että tuotannossa toimii tällä hetkellä samalla tavalla eli jos asiakkaalla jää lainaan vielä myöhässä olevia lainoja (ei laskutettuja), rajoite ei poistu automaattisesti. Eli ei ole uuden version bugi.

**Comment by emta001** [comment]
> Oulun laskuttajalta sain tänään tiedon, että tuotannossa toimii tällä hetkellä samalla tavalla eli jos asiakkaalla jää lainaan vielä myöhässä olevia lainoja (ei laskutettuja), rajoite ei poistu automaattisesti. Eli ei ole uuden version bugi.

Tästä voisi tehdä ihan oman tiketin, tuskin keretään korjaamaan tätä enää versionvaihtoon mennessä.

**Comment by AnneliO** [comment]
Toimii.
