### ISSUE TITLE
koha-plugin-delete-biblio-components (KPDELC)

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-23x#78]
### Siirrettävä ominaisuus

Osakohteiden poistoliitännäinen

**Comment by ajrajala** [comment]
Vaski-nextillä testattu osakohteellisen tietueen poisto (sekä Muokkaa-valikon että eräpoiston kautta), myös osakohteet poistuivat.

**Comment by Kati-Helle** [comment]
Helle-nextissäkin osakohteellisen tietueen osakohteetkin poistuvat. 
Testasin poistotavat
- niteettömän tietueen perustiedot, Muokkaa/Poista tietue
- tietueiden poisto eräajona
- niteiden poisto eräajona, kun toiminnossa on valittuna: Poista tietueet, jos kaikki niteet poistettu.

**Comment by pirliis** [comment]
OUTIn nextillä myös osakohteet poistuivat, kun poistin osakohteellisia tietueita samalla tavalla kuin Kati oli Hellessä testannut.

**Comment by AnneliO** [comment]
Tuotannossa, suljen.
