### ISSUE TITLE
KPCPU - koha-plugin-ceepos-integration

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#79]
### Siirrettävä ominaisuus

Koha-Ceepos-liitännäinen

**Comment by johannaraisa** [comment]
CPU:lla ei ole testijärjestelmää, joten tämän joutuu testaamaan kokonaisuudessaan tuotannossa. Nextillä voi käydä katsomassa tuleeko nappi näkyviin asetuksen kirjastopisteille.

**Comment by pirliis** [comment]
Oululla oli 12.4.2024 palaveri CPU:n kans ja palaverissa keskusteltiin Koha-Suomen ja CPU:n yhteistyön lisäämisestä. Laitoin asiasta myös matrixin Koha-Suomi Yleinen- kanavalle. Eli heiltä voisi varmaan saada esim. Ceeposin testiympäristön käyttöön näihin versiopäivityksiin ja ehkä muidenkin ongelmien selvittelyyn. Varmaan olisi hyvä, jos Koha-Suomen kehittäjät saisivat sovittua  CPU:lle ns. suoran linjan heidän maksurajapinnan asiantuntijoihin, ei tarvitsisi aina mennä heidän tuki-palvelun kautta.

Tsekkailin OUTIn nextillä Ceepos-painikkeita. Näytti olevan kirjastoilla, joissa Ceepos on käytössä ja ei ollut niillä kirjastoilla, joissa se ei ole käytössä. Eli tältä osin asia ok.

Tarvittaessa voin testata pienillä summilla maksujen lähettämistä nextiltä OUTIn Ceeposin tuotantoon, jos se nähdään tarpeelliseksi. Viime versiopäivityksen jälkeen meillä oli maksurajapinta pois käytöstä kuukauden, ennen kuin ongelma selvisi Kohan päästä.

**Comment by johannaraisa** [comment]
> Oululla oli 12.4.2024 palaveri CPU:n kans ja palaverissa keskusteltiin Koha-Suomen ja CPU:n yhteistyön lisäämisestä. Laitoin asiasta myös matrixin Koha-Suomi Yleinen- kanavalle. Eli heiltä voisi varmaan saada esim. Ceeposin testiympäristön käyttöön näihin versiopäivityksiin ja ehkä muidenkin ongelmien selvittelyyn. Varmaan olisi hyvä, jos Koha-Suomen kehittäjät saisivat sovittua CPU:lle ns. suoran linjan heidän maksurajapinnan asiantuntijoihin, ei tarvitsisi aina mennä heidän tuki-palvelun kautta.
> 
> Tsekkailin OUTIn nextillä Ceepos-painikkeita. Näytti olevan kirjastoilla, joissa Ceepos on käytössä ja ei ollut niillä kirjastoilla, joissa se ei ole käytössä. Eli tältä osin asia ok.
> 
> Tarvittaessa voin testata pienillä summilla maksujen lähettämistä nextiltä OUTIn Ceeposin tuotantoon, jos se nähdään tarpeelliseksi. Viime versiopäivityksen jälkeen meillä oli maksurajapinta pois käytöstä kuukauden, ennen kuin ongelma selvisi Kohan päästä.

Vein nextille tuotannosta voimassa olevat sertifikaatit, nämä on laitettu OUUL kirjastopisteelle. Sillä voi kokeilla meneekö maksu kassalle asti.

**Comment by pirliis** [comment]
Tein testimaksun nextiltä tuotannon Ceepos-kassalle OUUL15. Maksun lähetys Kohasta kassalle toimi ja maksetun maksun kuittaus Ceeposista Kohaan toimi. :)

**Comment by johannaraisa** [comment]
> Tein testimaksun nextiltä tuotannon Ceepos-kassalle OUUL15. Maksun lähetys Kohasta kassalle toimi ja maksetun maksun kuittaus Ceeposista Kohaan toimi. :)

Hurraa!!

**Comment by johannaraisa** [comment]
Tämän tiketin taitaa voida sitten sulkea.
