### ISSUE TITLE
Floatrules - ksdev/ks-0018-on-0010-K22-1-floatrules

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#8]
### Siirrettävä ominaisuus

Floatrules-järjestelmäasetus, jolla määritetään kirjasto/kuntakohtaisia kellutussääntöjä.

![209780999-f6a686bd-a89a-4a4c-900f-72d2dc1511bc](https://github.com/KohaSuomi/Koha-23x/assets/33121325/0f73591e-d5df-4fb0-813b-646ace3e762f)

**Comment by emta001** [comment]
Lisätään ohjeistukseen hoksautus siitä, että asetuksessa voi käyttää kommentteja https://github.com/KohaSuomi/Koha/issues/709

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 20.11.2023: Siirretään

**Comment by ajrajala** [comment]
Vaski-nextillä testailtu kellutusta, näyttäisi toimivan kuten pitää. Testattu seuraavia:
- Katkaisumerkin % käyttö kirjaston määrittelyssä toimii
- Sekä yhteen että molempiin suuntiin kelluttavat säännöt toimivat
- Kellutus toimii halutusti myös, jos säännössä useampi eri ehto

**Comment by Kati-Helle** [comment]
Helle-nextillä floatrules-asetuksessa on Loviisan kirjastot ja näiden av-aineiston nidetyyppien kellutus.
Testaamani Loviisan av-nidetyyppiset niteet kelluivat Loviisan kirjastoissa.

**Comment by emta001** [comment]
Testattu ja toimii.
