### ISSUE TITLE
koha-plugin-print-pdf-notices (KPPDF)

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-23x#80]
### Siirrettävä ominaisuus

Koha plugin for printing notices

**Comment by emta001** [comment]
Tämä vaikuttaisi toimivan ilman suurempia korjauksia. Perustoiminnallisuutta voi siis testata jo nyt. 

Kannattaa huomata, että tähän liittyy tiketti [KPPDF-2](https://github.com/KohaSuomi/koha-plugin-print-pdf-notices/issues/2), joka on vielä tekemättä.Mutta sen testaukset kirjataan sitten tuohon tikettiin.

**Comment by Kati-Helle** [comment]
Helle-nextillä testausta.
Tulosta ilmoituksia -toiminnossa tulostettavana viesti (tänään muodostunut noutoilmoitus)
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/7b77dffa-5a03-4a9b-b55d-6518b5753079)

Tulosta-painikkeesta aukeaa noutoilmoitus tulostettavaksi
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/f8ae565f-7751-40f3-b396-6832e4d15ec6)

**Comment by Kati-Helle** [comment]
Takaisin-painike säilyttää ilmoituksen toiminnossa.
Tulosta-painikkeesta ilmoitus tulostuu ja myös poistuu toiminnosta.

**Comment by emta001** [comment]
Lisätäänpä testaussuunnitelma (tai ennemmin tsekkauslistan):

1. Onko plugin ulkoasu kunnossa?
2. Haetaanko tulostuslistalle oikeat viestit?
3. Suodattuvatko viestit oikein?
4. Onnistuuko viestin avaaminen tulosta-painikkeesta?
5. Onko viestin sisältö oikein?
6. Saako viestin tulostettua?
7. Saako viestin peruttua?

**Comment by Tuomas-Kyyti** [comment]
Ainakin saapumisilmoitusten osalta vaikuttaa toimivan. Muistutuskirjeet varmaan vaativat jokun cronin, jotta muodostuvat.

**Comment by emta001** [comment]
> Ainakin saapumisilmoitusten osalta vaikuttaa toimivan. Muistutuskirjeet varmaan vaativat jokun cronin, jotta muodostuvat.

Varmaankin overdue_notices.pl. Käyn laittaa sen Kyytiin päälle.

**Comment by emta001** [comment]
> > Ainakin saapumisilmoitusten osalta vaikuttaa toimivan. Muistutuskirjeet varmaan vaativat jokun cronin, jotta muodostuvat.
> 
> Varmaankin overdue_notices.pl. Käyn laittaa sen Kyytiin päälle.

Se olikin jo päällä, pyörähtää aina kello 9 aamulla.

**Comment by ReettaSiili** [comment]
Siilin saapumisilmoitukset toimivat. Suodatus tapahtuu edelleen asiakkaan kotikirjaston mukaan. Tsekkauslista on ok. Jo tulostetun ilmoituksen saa myös takaisin tulostettavien listalle lähetä uudelleen -painikkeella kuten pitääkin.

Onko Siilin nextillä myös myöhästymisilmoitusten croni päällä?

Seuraavasta pienestä ongelmasta, on myös tuotanto-Kohassa, en ole muistanut tiketöidä:
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/98806001/293ad661-d72c-4a1c-a471-fae709e5f333)
Tulostuslistaa läpikäydessä/tulostettaessa ilmoitukset välillä "tuplaavat" itsensä, mutta tuplakappale poistuu itsestään kun tekee jonkin toiminnon, eli ei jää sitten enää haittaamaan eikä tuplatulostaminen ole mahdollista. En tiedä mistä tuo johtuu.

**Comment by emta001** [comment]
> Siilin saapumisilmoitukset toimivat. Suodatus tapahtuu edelleen asiakkaan kotikirjaston mukaan. Tsekkauslista on ok. Jo tulostetun ilmoituksen saa myös takaisin tulostettavien listalle lähetä uudelleen -painikkeella kuten pitääkin.
> 
> Onko Siilin nextillä myös myöhästymisilmoitusten croni päällä?
> 
> Seuraavasta pienestä ongelmasta, on myös tuotanto-Kohassa, en ole muistanut tiketöidä: ![kuva](https://private-user-images.githubusercontent.com/98806001/312087208-293ad661-d72c-4a1c-a471-fae709e5f333.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMTQ1NTcsIm5iZiI6MTcxMTAxNDI1NywicGF0aCI6Ii85ODgwNjAwMS8zMTIwODcyMDgtMjkzYWQ2NjEtZDcyYy00YTFjLWE0NzEtZmFlNzA5ZTVmMzMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDA5NDQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5NGRhMmNjMGVlN2I5ZTE4OTQ5MTI0OTM0MTdlM2NlNDc5N2M4NGRhZWU3ZDdhYWIyMTdkYmY3NjI4NjM0Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W78dUdng1EPF_RohzFr-1suhRxVNywFX4cF9r8azmWw) Tulostuslistaa läpikäydessä/tulostettaessa ilmoitukset välillä "tuplaavat" itsensä, mutta tuplakappale poistuu itsestään kun tekee jonkin toiminnon, eli ei jää sitten enää haittaamaan eikä tuplatulostaminen ole mahdollista. En tiedä mistä tuo johtuu.

Ajo on päällä myös Siilissä. Tuo tuplaantumisella oli jotain tekemistä käyttöliittymän kanssa, se ei aina ihan pysy perässä. Sitä tutkittiin muistaakseni viime versionvaihdossa jo, mutta silloin sille ei löytynyt mitään kummempaa syytä.

**Comment by emta001** [comment]
Tämä vaikuttaisi toimivan kuten pitääkin. Suljen tiketin. Ja teen tuosta Reetan mainitsemasta tuplaantumisesta oman tiketin.
