### ISSUE TITLE
koha-plugin-nalkutin (KPNAL)

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-23x#83]
### Siirrettävä ominaisuus

Plugin to complain if catalogued record fields do not match MARC21 format

**Comment by piiaseme** [comment]
Saisimmeko nalkuttimen myös OUTIn, Hellen ja Vaaran tietokantoihin.

**Comment by Hanna-Lumme** [comment]
Tämän voi lisätä myös Lumpeille.

**Comment by ajrajala** [comment]
Vaskissa haluttaisiin testata myös, joten saisiko samalla Vaskillekin.

**Comment by Tuomas-Kyyti** [comment]
Tuleeko tämä siis versionvaihdossa kaikille kimpoille erikseen pyytämättä?
