### ISSUE TITLE
KPRDI - koha-plugin-rest-di 

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#84]
### Siirrettävä ominaisuus

REST API plugin for Koha to provide additional functionality for discovery interfaces such as VuFind.

**Comment by lmstrand** [comment]
Nexteillä testattavana. Tarkistatteko, että asiakastiedot näkyvät ok ja asiakastietojen muutospyynnöt menevät läpi ok, varaaminen onnistuu ja saatavuustiedot ovat ok.

**Comment by pknuuti** [comment]
Testasin Vaaran nextillä ja Finna-nextillä. Muuten toimi asiakastiedot, varaaminen ja saatavuustiedot, mutta kun tein nextillä varaustunnuksen muutoksen, se ei päivity/näy Finna-nextillä. Toisin päin kyllä toimi eli Finnan puolella tehty muutos  tuli virkailijatyökaluun, mutta näkyi hyväksymisnäytöllä tyhjänä.
![2023kuvat 292](https://github.com/KohaSuomi/Koha-23x/assets/73887264/b02bbe2d-188c-4c4e-a001-bed5d41bb9fe)

**Comment by lmstrand** [comment]
Varaustunnus-tietona on nyt kutsumanimi-kenttä jonka pitäisi päivittyä tietokantaan ilman muutospyynnön syntymistä. Pitää tutkia, miksi noin käy. Ainakin siis vaaran Finna-next-ympäristöstä puuttuu tuo asiakasmääreellä HOLDID määritetyn varaustunnuksen käyttö varaustunnnuskentässä.

**Comment by pknuuti** [comment]
> Varaustunnus-tietona on nyt kutsumanimi-kenttä jonka pitäisi päivittyä tietokantaan ilman muutospyynnön syntymistä. Pitää tutkia, miksi noin käy. Ainakin siis vaaran Finna-next-ympäristöstä puuttuu tuo asiakasmääreellä HOLDID määritetyn varaustunnuksen käyttö varaustunnnuskentässä.

Pitääkö mun osata nyt tehdä tuolle jotain?

**Comment by lmstrand** [comment]
Pitäisi Finnatukea pyytää tekemään sama muutos, kun mitä tehtiin testi-Finnoihin.

**Comment by lmstrand** [comment]
Silti tuon muut nimet/othernames/kutsumanimi-tiedon pitäisi mennä suoraan läpi ilman, että syntyy tuollainen muutospyyntö kohaan. Tieto kyllä päivittyy asiakkaan tietoihin suoraan. Selvittelen asiaa.

**Comment by lmstrand** [comment]
Kutsumanimenkin muuttamisen pitäisi mennä vähintään virkailijan hyväksyttäväksi, jos sen muuttaminen sallitaan Finnasta käsin ylipäänsä. Lisäsin sen listaan muutospyyntötiedoista, jotka vaativat virkailijan hyväksymisen. Muutos tehty nexteille.

**Comment by lmstrand** [comment]
Pluginista on siis luotu 23.xx-branchiin natlib-repositorion main-branchin pohjalta 23-Kohan kanssa yhteensopiva versio meidän muutoksilla ja kaikki näyttäisi toimivan ok. Suljen tiketin.
