### ISSUE TITLE
koha-plugin-broadcast-biblios (KPBB) 

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-23x#87]
### Siirrettävä ominaisuus

Broadcast biblios via REST

**Comment by johannaraisa** [comment]
Valutus on siirretty liitännäiseen, se on testattavana.

**Comment by johannaraisa** [comment]
Melindaan vienti on testattavana myös.

**Comment by AnttHeik** [comment]
Testasin tätä TäTi-nextillä ja Melindasta tuonti tuo tietueen oikeaan TäTiin eikä nextille. Samoin näyttäisi, että tietueen vienti on yhteydessä varsinaiseen Melindaan. OUTIssa ei tietuesiirtäjä hakee tyhjää. Onkohan se päällä?

**Comment by johannaraisa** [comment]
Ehkä tässä on minulla tullut ajatuskatko. En ole vielä nexteille tätä kytkenyt, kun sitä testausta tehdään testin puolella. Yritän tässä lähiaikoina laittaa sinnekin.

**Comment by AnttHeik** [comment]
Ok! :)
