### ISSUE TITLE
Takaajan pakollisuus - ksdev/ks-0019-bug-12133

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#9]
### Siirrettävä ominaisuus

Toiminnallisuus, jolla takaajatiedon saa määritettyä pakolliseksi sellaisille asiakastyypeille, jotka on määritetty taattaviksi. Tähän liittyy järjestelmäasetus _ChildNeedsGuarantor_.

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 20.11.2023: Siirretään

**Comment by emta001** [comment]
Ominaisuus on valmiina uudessa versiossa, varmistettava että toimii kuten pitää.

**Comment by Kati-Helle** [comment]
Helle-Nextillä testatessa

Lapsi-asiakastyypin tallennus ilman takaajatietoa ja Koha ilmoittaa
![Image](https://github.com/KohaSuomi/Koha-23x/assets/99952449/af03633b-0707-4df6-b533-42013d896462)

Lapsiasiakas, omatoimi sallittu -asiakastyypin tallennus ilman takaajatietoa ja Koha ilmoittaa
![Image](https://github.com/KohaSuomi/Koha-23x/assets/99952449/03bd8e15-ef4e-41d9-afdd-c310e02b4d7c)

Holhottava aikuinen -asiakastyypin tallennus ilman takaajatietoa ja Koha ilmoittaa
![Image](https://github.com/KohaSuomi/Koha-23x/assets/99952449/83cbeccb-2998-4c35-8406-a47a58801c9e)

**Comment by pknuuti** [comment]
Vaaran nextillä tämä toimii samoin eli ei anna tallentaa huollettavaa ilman takaajatietoa.

**Comment by Tuomas-Kyyti** [comment]
Näin myös Kyytin nextillä. Ei anna myöskään poistaa takaajaa lapselta: "Takaajaa ei voi poistaa. Lapsiasiakas tarvitsee takaajan."

**Comment by emta001** [comment]
Kolemn testin perusteella toimii. Suljen tiketin.
