### ISSUE TITLE
KPEDX - koha-plugin-editx

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#90]
### Siirrettävä ominaisuus

EDItX-sanomia käsittelevä liitännäinen

**Comment by lmstrand** [comment]
Testattu kolmella sanomalla Vaara-nextillä toimivaksi ks22-branchissa.

runEditXImport.pl:n ajo  herjaa pluginien puuttumisesta, muttei vaikuta sanomien käsittelyyn:

[koha@vaara-next] last: 3s ~/koha-plugin-editx/Koha/Plugin/Fi/KohaSuomi/Editx/cronjobs $ ./runEditXImport.pl
Started Koha::Procurement
KirjavÃ¤litys 
Failed to load Koha::Plugin::Fi::KohaSuomi::AutoFrameworkCode: Could not find or check module 'Koha::Plugin::Fi::KohaSuomi::AutoFrameworkCode' at /home/koha/Koha/Koha/Plugins.pm line 124.
Failed to load Koha::Plugin::Fi::KohaSuomi::Nalkutin: Could not find or check module 'Koha::Plugin::Fi::KohaSuomi::Nalkutin' at /home/koha/Koha/Koha/Plugins.pm line 124.
Failed to load Koha::Plugin::Fi::KohaSuomi::ReportServices: Could not find or check module 'Koha::Plugin::Fi::KohaSuomi::ReportServices' at /home/koha/Koha/Koha/Plugins.pm line 124.
Use of uninitialized value $plugin_version in string ne at /home/koha/Koha/Koha/Plugins/Base.pm line 81.
Ended Koha::Plugin::Fi::KohaSuomi::Editx::Procurement
