### ISSUE TITLE
koha-plugin-visual-label-tool (KPVLT)

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha-23x#91]
### Siirrettävä ominaisuus

Tarratyökalu

**Comment by ajrajala** [comment]
Testailin tätä vaski-nextillä ja se pisti silmään, että Valitse lista -valikon vaihtoehdoista uupuu "Tänään vastaanotetut kausijulkaisut".

**Comment by ghost** [comment]
Nyt pitäisi näkyä.

**Comment by ajrajala** [comment]
Jeps, nyt näkyy tuokin vaihtoehto + sen valittua näkyville tulee tänään vastaanottamani lehtinide.

**Comment by Tuomas-Kyyti** [comment]
Tarratulostus ja tarrapohjien muokkaaminen vaikutti toimivan Kyyti-nextillä.

**Comment by emta001** [comment]
Testattu toimivaksi. Suljen tiketin.
