### ISSUE TITLE
Tiedonhaussa nimekkeellä järjestämiseen tullut muutos, joka vaatii Elasticsearchin mäppäysten resetoinnin ja uudelleenindeksoinnin

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#93]
### Mikä vikana?

[33594](http://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=33594) Sorting results by Title A-Z might use wrong title field

This changes the behavour of title search and sorting (Title (A-Z)) in the OPAC and staff interface when using Elasticsearch or Open Search. The title search now only uses 245 (for MARC 21) and 200 (for UNIMARC). Previously other title fields may have affected the search order, for example 240$a in MARC21.

To make this change for existing installations, reset the search engine mappings (Administration > Catalog > Search engine configuration (Elasticsearch) > Reset mappings (scroll down to the bottom of the page)) and rebuild the search index (koha-elasticsearch –rebuild -d -b -a ). If you have customized the search engine configuration, remember to record or back these up BEFORE resetting the mappings.

**Comment by CodoDerDritte** [comment]
Uudelleenindeksointi on käynnissä.

**Comment by CodoDerDritte** [comment]
Valmis muualla paitsi Outi ja Lastu vielä indeksoi. Testaus:

1. Tee haku
2. Järjestä hakutulokset nimekkeen mukaan
3. Tarkista että nimekkeet järjestyvät 245a -kentän perusteella aakkosjärjestykseen

**Comment by pknuuti** [comment]
En tiedä, onko Vaaran nextin haku vielä jossakin ihmevaiheessa, mutta tulos ei ole vakuuttava. Järjestetty siis nimekkeen mukaan suomi-sanalla tehty haku. Ensimmäisenä Rauhanlauluja, sitten numerolla alkavia nimekkeitä, joiden jälkeen nimeke Vuorten varjo. Ei siis mitään tolkkua.
![2023kuvat 341](https://github.com/KohaSuomi/Koha-23x/assets/73887264/e8d6b30c-46ca-49ba-907b-0337e1f60c72)

Koira-sanalla tehty haku antaa 9 tulosta, joiden järjestys on myös sekava nimekkeen mukaan järjestettynä eli ei toimi.

**Comment by CodoDerDritte** [comment]
En tehnyt tuolle muuta kuin kopioin mäppäystiedoston nykyisestä tuotannosta, vaatiikohan tämä vielä jotain muuta.

**Comment by CodoDerDritte** [comment]
Niijoo, sinnehän pitäisi jollain opilla nyt onnistua tietysti naittamaan ne yhteisön tekemät muutokset siihen meidän omaan mappingsiin. Se voikin olla jännittävä projekti, mutta katsotaan.

**Comment by CodoDerDritte** [comment]
https://github.com/KohaSuomi/koha-suomi-utility/blob/master/etc/elasticsearch-mappings.yaml

**Comment by CodoDerDritte** [comment]
Siili-next on nyt uudelleenindeksoitu uusilla mäppäyksillä. Jatkan muiden nextien indeksoinnilla.

**Comment by CodoDerDritte** [comment]
OUTIa ja Lastua lukuunottamatta kaikki next-kannat on nyt uudelleenindeksoitu. Elasticsearchin mappings-tiedosto on muuttunut paljon, joten testatkaa haku hyvin huolellisesti.

**Comment by Kati-Helle** [comment]
Helle-nextissä aakkostus 245a-kenttäarvon mukaan vaikuttaa toimivalta. Sekä tyyliin Nimeke (A-Z) että tyyliin Nimeke (Z-A) järjestäen. 

Hakutuloksen Ä-alkuinen 245a-kenttäarvo aakkostui A-alkuisiin 245a-kenttäarvoihin
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/db415ca4-6c93-4f5f-8b09-4ebdc10b72fc)

**Comment by Kati-Helle** [comment]
Ja Helle-nextissä
hakutuloksen Å-alkuinen 245a-kenttäarvo aakkostui A-alkuisiin 245a-kenttäarvoihin
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/69e1ff1e-eac5-4a33-8ba8-0459a4d937da)

ja hakutuloksen Ö-alkuinen 245a-kenttäarvo aakkostui O-alkuisiin 245a-kenttäarvoihin
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/6a6b88ff-ce74-49ba-a80a-545218fc7be2)

**Comment by CodoDerDritte** [comment]
Jaha, eli unicode-normalisointi, mitenköhän se korjataan XD

**Comment by CodoDerDritte** [comment]
Noiden skandien käsittely ei kyllä muutenkaan näytä hauissa toimivan oikein, esimerkiksi "vaarassa" mätsää "väärässä" ja "aidit" mätsää "äidit". Eli tämä normalisointikuvio on ehkä vähän tämän tiketin ulkopuolinen asia ja pitäisi hoitaa toimintakuntoon kokonaisuutena erillään tästä.

**Comment by CodoDerDritte** [comment]
https://github.com/KohaSuomi/Koha/issues/1177

**Comment by Kati-Helle** [comment]
Ei-kirjaimilla alkavien 245a-kenttäarvojen järjestäytymisestä esimerkki Helle-nextistä
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/35908cdb-1864-4a9a-8632-700715e8c50c)

**Comment by lmstrand** [comment]
Sovittiin pääkäyttäjäpalaverissa, että 245n-kenttäkin laitetaan sort-määritykseen. Muutettu ks-utilityn mapping-konfiguraatioon. Vaara-, Helle- ja Vaski-nextit indeksoitu uusiksi uudella konfiguraatiolla. Outi-next indeksoituu tänäiltana.

**Comment by AnneliO** [comment]
Järjestäminen toimii 245abnp-järjestyksessä. Suljen tiketin.
