### ISSUE TITLE
Uusi kuitti odottavasta varauksesta antoi viikon lisää noutoaikaa

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha-23x#95]
### Mikä vikana?

Työntekijä kertoo: "Jouduin tulostamaan yhdelle odottavalle varaukselle uuden kuitin. Aiemmin tulostuva kuitti on ollut identtinen, mutta nyt asiakkaalle putkahti viikko lisää noutoaikaa. Noudettava varaus oli kirja. Tarkastin, että asiakkaalla on vain yksi varaus voimassa. Nyt aamulla katsoin vielä viestit, eikä uutta noutoilmoitusta ole lähtenyt lauantaina. Asiakkaan ID 10908733."

Vastaava tapahtui viime viikolla yhden lehden kohdalla eli ilmeisesti ongelma johtuu nyt jostain Kohan uuden version bugista?

### Mitä pitäisi tapahtua

Noutoa odottavan niteen kuitti pitäisi pysyä sisällöltään samana, kun se tulostetaan uudelleen.

**Comment by pirliis** [comment]
OUTIssa kävi samoin. Kun noudettavissa olevan varauksen palautti uudestaan kesken noutoajan, Koha lisäsi varaukselle noutoaikaa järjestelmäasetuksissa määritellyn oletusnoutoajan verran. Kuten Päivi edellä laittoi, ennen varauksen infokuitin uudelleen tulostus palauttamalla säilytti alkuperäisen noutoajan varaukselle.

**Comment by AnneliO** [comment]
Tein Vaaran testille testitilanteen "päälle" borrowerille 11005913. Tietokannassa tilanne näyttää tältä. Tarkistan huomenna, miten tilanne muuttuu, kun palautan niteen uudelleen.

| reserve_id | waitingdate | reservedate | expirationdate | patron_expiration_date | timestamp           | found | biblionumber | itemnumber |
|---|---|---|---|---|---|---|---|---|
|    2084332 | 2023-08-02  | 2023-08-02  | 2023-08-10     | NULL                   | 2023-08-02 15:16:00 | W     |       401473 |  100480050 |

Samalla asiakkaalla oli myös toinen noudettavissa oleva varaus (joka oli oikeasti jo vanhentunut) ja palautin sen uudelleen. En muistanut ottaa lähtötilannetta talteen, mutta tältä näyttää palautuksen jälkeen:

| reserve_id | waitingdate | reservedate | expirationdate | patron_expiration_date | timestamp           | found | biblionumber | itemnumber |
|---|---|---|---|---|---|---|---|---|
|    2084331 | 2023-07-17  | 2023-07-17  | 2023-08-10     | NULL                   | 2023-08-02 15:18:42 | W     |       371298 |  100002052 |

expirationdate-kentän arvo on päivittynyt tämän päivän mukaiseen viimeiseen noutopäivään.

**Comment by AnneliO** [comment]
Jeps, asia vahvistettu. Palautin testivaraukseen kiinni jääneen niteen uudelleen vaaratestillä ja expirationdate meni päivällä eteenpäin.


| reserve_id | waitingdate | reservedate | expirationdate | timestamp           | found | biblionumber |
|---|---|---|---|---|---|---|
|    2084332 | 2023-08-02  | 2023-08-02  | 2023-08-11     | 2023-08-03 11:27:43 | W     |       401473 |

**Comment by AnneliO** [comment]
Testasin tätä vielä PTFS Europen sandboxissa (v. 23.06.00) ja siellä expirationdate säilyy ennallaan, vaikka odottamassa olevan niteen palauttaa uudelleen seuraavana päivänä.

**Comment by AnneliO** [comment]
Tämä ongelma on tosiaan korjattu versiossa 23.05. [Bugi 32627](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=32627). Siirrän tiketin Version 23.xx-tietovarantoon ja pistän sinne testattavaksi (kunhan saamme nextit pystyyn).

**Comment by Kati-Helle** [comment]
Helle-nextillä tesatessa toimii oikein, eli noutoaika ei lisääntynyt/muuttunut uuden kuitin tulostuksessa.

Ennen uuden kuitin tulostusta tietueen varauksissa Vanhenee = 01.02.2024 
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/a9b3d8da-61e8-472a-bc3d-a09761d3985f)

Nyt tulostetulla kuitilla sama päiväys 
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/99952449/9b3a00fe-32cd-42ce-936a-a12846cb993a)

Tietueen varauksen Vanhenee-päiväys ei muuttunut.

**Comment by pknuuti** [comment]
Vaaran nextilläkin testattu parin asiakkaan varauksilla eikä noutopäivä muutu, vaikka niteen palauttaa uudelleen.

**Comment by MikkoLiimatainen** [comment]
Vaskinkin nextillä testattu, että noutopäivä ei muutu palauttaessa ja tulostaessa uusi kuitti.

**Comment by MikkoLiimatainen** [comment]
Kirjaan tähän ylös Vaskissa huomatun tilanteen, jossa ilmeisesti on käynyt seuraavaa.

Varaus oli saanut noutopäiväksi 26.8.
Tärppäämisen jälkeen kirjaston kalenteri oli suljettu kokonaan heinä- ja elokuulta. Kalenteri on normaalistikin auki vain perjantaisin.
Varaus yritettiin palauttaa erääntyneenä varauksena ma 2.9, jolloin kirjasto oli vielä kiinni, eli yhtään mahdollisuutta varauksen erääntymiselle ei ollut ollut.
Varaus sai uuden noutopäivän 11.10, koska Koha laskee palautuksen yhteydessä uuden noutopäivän waitingdatesta eteenpäin varaussääntöjen ja kirjaston lomapäivien mukaan.

Käytännössä siis kalenterimuutokset muuttavat myös noutopäivää, jos nide palautetaan muutosten jälkeen uudelleen, mutta itse en pitäisi tuota varsinaisesti bugina. Tätä ominaisuutta voisi käyttää noutopäivien jatkamiseen yllättävässä sulkutilanteessa. Bugi tässä on ehkä se, että asiakas ei saa tietoa muuttuneesta noutopäivästä.
