### ISSUE TITLE
Uusintapäivämäärän asettaminen käsin -> kaksi eri erääntymiskellonaikaa syöttötavasta riippuen

### ISSUE THREAD

**Issue by IrinaHalminen** [KohaSuomi/Koha-23x#96]
### Mikä vikana?

Asiakkaan lainoille on joskus tarve antaa käsin muu eräpäivä kuin mitä järjestelmä tarjoaa, esim. koulun kortille kadoksiin jääneet lainat laitettiin kesäkuun alussa erääntymään seur. kerran vasta 1.8. Nyt havaittiin, että jos virkailija syöttää eräpäivän itse käsin ja painaa enter, erääntymiskellonajaksi tulee eräpäivänä 00.00. Tällöin lainat ovat myöhässä jo eräpäivän aamuna. Jos eräpäivän valitsee kalenterista, kellonajaksi tulee eräpäivänä 23.59, kuten pitääkin.

![kuva](https://github.com/KohaSuomi/Koha/assets/99409279/cb437f2d-ec38-442c-8b4f-5e995ebfc955)

**Comment by AnneliO** [comment]
Sama tapahtuu myös PTFS Europen sandboxissa versiossa 23.06.

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 24.8.2023: Tämä on yhteisön versiossa oleva "ominaisuus", joten se pitää muuttaa yhteisön versioon. Eli tästä pitää tehdä bugiraportti yhteisön Bugzillaan. Teetkö Irina tuon bugiraportin?

Mahdollista muutosta odotellessa kannattaa päivämäärän lisäksi kirjoittaa myös kellonaika, eli tyyliin "24.08.2023 23:59"

**Comment by IrinaHalminen** [comment]
Voin tehdä bugiraportin. -> https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=34680

**Comment by AnneliO** [comment]
Korjaakohan tämä yhteisön masteriin päätynyt tiketti tämän ongelman: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=34939

Siirrän tiketin Version 23.x-tietovarantoon ja laitan testattavaksi (kunhan saamme nextit tulille).

**Comment by pknuuti** [comment]
Testasin Vaaran nextillä ja nyt antaa samanlaisen eräpäivän eli loppuu klo 23:59 teenpä kummalla tavalla tahansa niteen uusinnan. Valitsemalla kalenterista päivämäärän tai syöttämällä pelkästään päiväyksen 1.6.2024, kellonaika tulee molemmissa tavoissa klo 23:59.

**Comment by Kati-Helle** [comment]
Helle-nextillä toimii samoin kuin Vaaran nextillä. Kellonaika muodostuu sekä päiväyksen kalenterista valitsemalla että päiväyksen kirjoittamalla.

**Comment by MikkoLiimatainen** [comment]
Vaskissakin testattu, että päiväykseen tulee nyt kellonaika 23:59 sekä kalenterista että kirjoittamalla.

**Comment by Hanna-Lumme** [comment]
Lumpeissa toimii myös oikein.

**Comment by AnneliO** [comment]
Tämä tuntuisi toimivan oikein, joten suljen tiketin. :)
