### ISSUE TITLE
Tietueen varaukset sivulle näkyviin asiakkaan kirjastokortin numero

### ISSUE THREAD

**Issue by MikkoLiimatainen** [KohaSuomi/Koha-23x#97]
### Kehitysehdotukseni

Tietueen varaussivulla näkyy kirjastokortin lukemisen jälkeen teksti "Asiakas: Kirjaston asiakas Turku, Pääkirjasto".
![Koha request pl varauksen tiedot asiakas](https://github.com/KohaSuomi/Koha/assets/98884651/270c666b-ab38-4f9d-9cbe-99820bcc4c5d)
Tähän näyttäisi sivupohjassa request.tt vaikuttavan arvo no_cardnumber => 1
![Github request tt no_cardnumber](https://github.com/KohaSuomi/Koha/assets/98884651/773d86a0-62a8-4669-97e1-2464bbda8857)
Varsinainen teksti tuohon tulee tuon patron-title.inc sivun kautta ja siellä tuo no_cardnumber asettaa display_cardnumber arvoksi 0.
![Github patron-title inc display_cardnumber](https://github.com/KohaSuomi/Koha/assets/98884651/36424b87-ab4d-45e2-9bcc-f0f6a266b95c)
Display_cardnumber puolestaan vaikuttaa siihen, mikä teksti tuohon varaussivulle tulee.
![Github patron-title inc Teksti varaussivulle](https://github.com/KohaSuomi/Koha/assets/98884651/a3f80b9e-b00d-417e-918b-9b4e185b89b9)
Nyt kun display_cardnumber asetetaan no_cardnumber-arvon avulla nollaksi, tulee patron-title.inc sivulta default-teksti. Jos no_cardnumber => 1 jätettäisiin request.tt-sivulta pois tuosta kohtaa, jäisi patron-title.inc:n display_cardnumber arvoksi yksi ja silloin varaussivulle tulostuvan tekstin pitäisi olla asiakkaan kortin numero.

Jos tulkintani koodin toiminnasta on oikea, niin tämä vaikuttaisi olevan yksinkertainen muutos, joka toisi erittäin suuren hyödyn varausten tekemiseen.

**Comment by pknuuti** [comment]
Tieto asiakkaasta olisi hyvä saada näkyville, varmistaisi varauksen teon oikealle henkilölle.

**Comment by AnneliO** [comment]
Tähän liittyy HidePatronName-järjestelmäasetus, joka piilottaa asiakastiedot perustiedot-näytöllä lainattujen niteiden kohdalta ja muuttaa varaustenteko-sivulla nimen tilalle "Kirjaston asiakas...".

Perustiedot-näytöllä nimen tilalle tulee kirjastokortin numero, mikä olisi looginen tapa myös varauksenteko-sivulla.

**Comment by AnneliO** [comment]
Tämä näyttäisi vaikuttavan myös ilmoitukseen, jossa kerrotaan varauksia olevan jo maksimimäärä:

![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/962ffe08-bd7f-4673-b2a7-19a0f7f104b4)


![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/25a0da45-72fd-42ce-b41a-1ef5e71ad3af)

**Comment by MikkoLiimatainen** [comment]
Juu, tuo no_cardnumber näyttää tosiaan olevan pitkin tuota reserve/request.tt sivupohjaa.
![Varauksen korttinumero no_cardnumber asetus varoituksissa](https://github.com/KohaSuomi/Koha/assets/98884651/e631f5d3-37d4-4d7e-b065-3dd874399536)
Minusta ei korttinumeron piilottamiseen tuolla sivulla ole mitään syytä, joten nuo voisi kaikki poistaa.
Noiden poistamisen jälkeen sivun pitäisi toimia niin, että tuolla HidePatronName-asetuksella voi kontrolloida näkyykö sivulla asiakkaan nimi, vai pelkkä korttinumero. Käytännössä siis samalla tavalla kuin tietueen perustiedot näytöllä lainattujen niteiden kanssa.

**Comment by AnneliO** [comment]
Versiossa 23.05.05 tulee muutos, jossa asiakkaan kirjastokortin numero lisätään varauksentekosivulle. Sandboxissa tehdyn testauksen mukaan, kirjastokortin numero näkyy, vaikka päälle laittaa HidePatronName-järjestelmäasetuksen.

[Bugi 34457](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=34457)

Siirrän tiketin version 23.x-tietovarantoon ja testattavaksi, kunhan saamme nextit käyttöön.

**Comment by Kati-Helle** [comment]
Helle-Nextillä asiakkaan kirjastokorttiarvo näkyy Asiakas-kentässä
![Image](https://github.com/KohaSuomi/Koha-23x/assets/99952449/afb0d033-9b4d-41e3-8a49-2726d5301c71)

**Comment by pknuuti** [comment]
Vaaran nextillä testattu, sama tulos kuin Hellessä eli asiakaskentässä näkyy kortin numero, mikä on hyvä juttu.

**Comment by ajrajala** [comment]
Varuilta lisään vielä tähän, että testasin myös usean nimekkeen varaamista yhdellä kertaa, silloinkin korttinumero näkyvissä. 👍
