### ISSUE TITLE
Salasanan vanhenemistoiminto

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha-23x#98]
### Siirrettävä ominaisuus

On käyty keskusteluja, voitaisiinko käyttäjätunnuksen vanhenemisskripti korvata lisäämällä käyttäjätunnuksille salasanan vanhenemispäivää.

Salasanan vanhenemispäivän valinta tulee näkyville Kirjautumistunnus-osioon vasta, kun uutta käyttäjätunnusta muokkaa ensimmäisen kerran:
![kuva](https://github.com/KohaSuomi/Koha-23x/assets/33121325/3727abbd-a661-4d21-bbdb-ce58fc485fd6)
* salasana vanhentuu sinä päivänä, mikä on valittuna kenttään. Eli jos siihen laittaa 28.11.2023, käyttäjä ei pääse kirjautumaan enää 28.11.2023.
* kirjautuminen onnistuu taas samantien, kun vanhentumispäivä vaihdetaan.
* Huom! Tällä hetkellä taitaa olla kaikilla piilotettuna Kirjautumistunnus-osio IntranetUserCSS:llä.

Tältä näyttää, kun yrittää kirjautua vanhentuneella salasanalla:

![kuva](https://github.com/KohaSuomi/Koha-23x/assets/33121325/5bad9b42-9ca4-433a-b040-3dd5beb054ae)

Alustava yhteenveto: Salasanan vanhentumispäivällä voi korvata tunnuksen vanhentamisskriptin, mutta vaatii toimintatapamuutoksen.

**Comment by CodoDerDritte** [comment]
Skripti on utilityssä, se voidaan poistaa käytöstä tuotantokontainerien crontabeista versiopäivityksen jälkeen (mange_expired_accounts.pl).

**Comment by ajrajala** [comment]
Testasin toiminnallisuutta ja vanhentunut salasana estää kirjautumisen. **Jos salasanan vaihtaa, näyttäisi se kuitenkin nollaavan salasanan vanhemispäivän; salasanan vaihdon jälkeen vanhenemispäivä on "Ei koskaan".** En keksinyt, että tähän olisi voinut jollakin asetuksella vaikuttaa?

Tuo päivämäärän nollautuminen on yksinään este, mutta mikäli se on selätettävissä niin kirjailin vielä joitakin muitakin huomioita/kysymyksiä:
- Vanhenevista tunnuksista on lähtenyt ilmoitus 30 päivää ennen vanhenemista, mutta saako vanhenevasta salasanasta vastaavaa ilmoitusta?
- Vaskissa virkailijatunnukset ovat voimassa kerrallaan 1 vuoden verran ja esihenkilöiden vastuulla on käydä vanhenevat tunnukset läpi ja jatkaa niiden voimassaoloaikaa jos työsuhde jatkuu. Jos läpikäytäviä tunnuksia paljon, on salasanan vanhenemispäivän muokkaaminen hitaampaa kuin tunnusten voimassaolon jatkaminen. Tämä olisi siis huononnus nykyiseen toiminnallisuuteen.
- Asiakkaita muokatessa olisi parempi, ettei salasanan vanhenemispäivä näkyisi ja vastaavasti virkailijatunnusta muokatessa voimassaolopäivän pitäisi olla piilossa jottei sitä vahingossa käytettäisi.

**Comment by CodoDerDritte** [comment]
Tässä en pidä Koha-Suomen oman toiminnallisuuden säilyttämistä näiden suhteen kovinkaan isona ongelmana. Se voidaan hyvin tehdä jos tuo salasanan vanhenemisaikaratkaisu ei meidän käyttöön sovi tai on työläs.

**Comment by CodoDerDritte** [comment]
Olisikohan tässä järkevintä lukita salasanan vanhenemispäivä seuraamaan tilin vanhenemispäivää ainakin virkailijatunnuksilla. Homman voisi toteuttaa triggerillä, jolloin:

- erillistä cron-ajoa ei enää tarvita
- tilin uusiminen (voimassaolon jatkaminen) asettaa sanasanan vanhenemispäiväksi automaattisesti tilin vanhenemispäivän
- tilin uusinnassa ollut viive poistuu ja tili tulee jälleen käyttöön välittömästi 
- salasanan vaihto ei muuta vanhenemispäivä (joka edelleen seuraa tilin vanhenemispäivää)
- kirjautujalle näytettävä ilmoitus on oikeampi ("salasanasi on vanhentunut" sen sijaan että kerrotaan vain kirjautumisvirheestä)
- salasanan vanhenemispäivän näkyvyydellä tai näkymättömyydellä ei ole vaikutusta toimintaan eikä siihen tarvitse erikseen kiinnittää huomiota
- koska salasana vanhenee aina samaan aikaan kuin tunnus, saadaan myös tuo ilmoitus 30 päivää ennen vanhenemista toteutettua helposti

**Comment by CodoDerDritte** [comment]
Triggerit on nyt lisätty next-kantoihin. Lisäsin uuden toiminnallisuuden olemassaoleviin before_borrowers_insert ja before_borrowers_update triggereihin:

```
DROP TRIGGER before_borrowers_insert;
DROP TRIGGER before_borrowers_update;

CREATE TRIGGER before_borrowers_insert
    BEFORE INSERT
    ON borrowers FOR EACH ROW
    SET new.userid=new.cardnumber,
        new.password_expiration_date=new.dateexpiry;

CREATE TRIGGER before_borrowers_update
    BEFORE UPDATE
    ON borrowers FOR EACH ROW
    SET new.userid=new.cardnumber,
        new.password_expiration_date=new.dateexpiry;

UPDATE borrowers SET password_expiration_date=dateexpiry;
```

**Comment by CodoDerDritte** [comment]
Testaa tunnuksen uusinta:

1. Tarkista tunnuksen vanhenemispäivä ja salasanan vanhenemispäivä
2. Jatka tunnuksen voimassaoloaikaa
3. Tarkista että tunnuksen vanhenemispäivä ja salasanan vanhenemispäivä muuttuivat ja ovat samat keskenään

Testaa tunnuksen lisääminen:

1. Luo uusi tunnus
2. Tarkista tunnuksen vanhenemispäivä ja salasanan vanhenemispäivä, pitäisi olla keskenään samat

Testaa vanhentuneella tunnuksella kirjautumisen esto kokeilemalla kirjautua järjestelmään vanhentuneella tunnuksella.

**Comment by ajrajala** [comment]
Testasin tätä ja toimii testausohjeiden mukaisesti. Kun tunnus ja salasana vanhentunut, kirjautuminen ei onnistu. Tuleekohan tuo "Ota yhteyttä kirjastoon palauttaaksesi salasanasi" -teksti asetuksista samaan tapaan kuin virheilmoitusta edeltävä teksti? Mietin jos siihen saisi vielä kustomoitua lyhyen toimintaohjeen kirjautumista yrittävälle virkailijalle.

![kuva](https://github.com/KohaSuomi/Koha-23x/assets/44638512/e7b43c95-647a-4d7a-83ee-48014a347c72)

**Comment by pknuuti** [comment]
Toimii Vaaran nextilläkin kuten Anni tuossa kirjoitti. Ensin mua hämäsi se, että yritin muuttaa käyttäjän tunnuksen vanhenemispäivää eikä tapahtunut mitään, kun valitsin kalenterista uuden päiväyksen ja tallensin. Näkymä palasi näyttämään kalenteria eikä sitä ongelmaa mikä oli syynä tallennuksen epäonnistumiseen eli syntymäajan puuttumiseen. 
Varaustunnus ei myöskään tule automaattisesti nextillä, siihen pitää itse syöttää jotain. Jos sen jättää tyhjäksi, tulee virheilmoitus "There are some required fields missing from this section. Please complete them."

**Comment by AnneliO** [comment]
>Varaustunnus ei myöskään tule automaattisesti nextillä, siihen pitää itse syöttää jotain. Jos sen jättää tyhjäksi, tulee virheilmoitus "There are some required fields missing from this section. Please complete them."

Varaustunnuksen generointi-rimpsussa on vielä ongelma, joten se ei ole teillä vielä käytössä. Tässä [lista ei-toimivista-rimpsuista](https://github.com/KohaSuomi/Koha-23x/wiki/IntranetUserJS#ei-viel%C3%A4-toimi).

**Comment by CodoDerDritte** [comment]
> Testasin tätä ja toimii testausohjeiden mukaisesti. Kun tunnus ja salasana vanhentunut, kirjautuminen ei onnistu. Tuleekohan tuo "Ota yhteyttä kirjastoon palauttaaksesi salasanasi" -teksti asetuksista samaan tapaan kuin virheilmoitusta edeltävä teksti? Mietin jos siihen saisi vielä kustomoitua lyhyen toimintaohjeen kirjautumista yrittävälle virkailijalle.
> 
Teksti tulee auth.tt templatesta. Käännöstä voidaan varmaankin tarvittaessa viilata, mutta kirjasto/kimppakohtainen kustomointi ei nykyisellään ole mahdollista.

**Comment by AnneliO** [comment]
Tapahtuuko tuo kopiointi nyt kaikilla asiakastyypeillä? Jos tapahtuu, niin olisiko tarve rajata se vain VIRKAILIJA-tyyppisiin tunnuksiin? Vai liittyikö meidän nykyiseen skriptiin toiminnallisuutta asiakkaidenkin tunnuksiin liittyen? Koitan tässä muistella, mutta en nyt millään muista.

**Comment by AnneliO** [comment]
Tuo käännös on staff-prog.po-tiedostossa ja sitä käytetään vain koha-tmpl/intranet-tmpl/prog/en/modules/auth.tt -kohdassa. Sen puolesta käännöstä voidaan muuttaa, mutta se olisi sitten todennäköisesti Koha-Suomi-muutos.

You must contact the library to reset your password
Ota yhteyttä kirjastoon palauttaaksesi salasanasi

Jos haluatte, teettekö tuosta kehitysehdotuksen, niin pohditaan asiantuntijaryhmässä, kannattaako muutosta tehdä ja ylläpitää.

**Comment by CodoDerDritte** [comment]
> Tapahtuuko tuo kopiointi nyt kaikilla asiakastyypeillä? Jos tapahtuu, niin olisiko tarve rajata se vain VIRKAILIJA-tyyppisiin tunnuksiin? Vai liittyikö meidän nykyiseen skriptiin toiminnallisuutta asiakkaidenkin tunnuksiin liittyen? Koitan tässä muistella, mutta en nyt millään muista.

Tällä hetkellä tapahtuu kaikilla asiakastyypeillä. Onko tästä erityistä haittaa?

**Comment by AnneliO** [comment]
> > Tapahtuuko tuo kopiointi nyt kaikilla asiakastyypeillä? Jos tapahtuu, niin olisiko tarve rajata se vain VIRKAILIJA-tyyppisiin tunnuksiin? Vai liittyikö meidän nykyiseen skriptiin toiminnallisuutta asiakkaidenkin tunnuksiin liittyen? Koitan tässä muistella, mutta en nyt millään muista.
> 
> Tällä hetkellä tapahtuu kaikilla asiakastyypeillä. Onko tästä erityistä haittaa?

Yritin miettiä ja testata, mitä haittaa siitä voisi mahdollisesti olla ja tässä jotain pohdintoja:
* kun asiakkaan kirjastokortti jostain syystä vanhenee, oletan hänen olevan käytännössä lainauskiellossa ainakin automaateilla. En tosin pystynyt tätä testaamaan käytännössä. Toisaalta, tämä ei taida muuttua nykyiseen tilanteeseen verrattuna mitenkään, koska asiakas on käytännössä lainakiellossa, kun kirjastokortti vanhenee.
* asiakas pääsee kirjautumaan verkkokirjastoon, koska ilmeisesti Finna-rajapinta ei tarkista salasanan voimassaoloaikaa. Jos tuki lisätään Finna-rajapintaan jossain vaiheessa, niin sitten asiakas ei pääse kirjautumaan. Hän pystyy palauttamaan uuden salasanan, mutta se vanhenee käytännössä samantien. Nykyisellään vanhentuneella kirjastokortilla pystyy kirjautumaan Finnaan.

Eli ehkä ongelmia ei synny, jos pidetään huolta, että asiakkaiden kirjastokorttien voimassaoloaika ei pääse umpeutumaan. Toki on poikkeuksia, joissa voimassaoloaika on tarkoituksella lyhyt ja silloin todennäköisesti on ok, että jotkin asiat estyy.

**Comment by CodoDerDritte** [comment]
Luulisin että tuo on tarvittaessa kyllä mahdollista rajata koskemaan esimerkiksi pelkkiä virkailijatunnuksia, mutta en oikein kanskaan keksinyt miksi se olis tarpeen.

**Comment by ajrajala** [comment]
>asiakas pääsee kirjautumaan verkkokirjastoon, koska ilmeisesti Finna-rajapinta ei tarkista salasanan voimassaoloaikaa. Jos tuki lisätään Finna-rajapintaan jossain vaiheessa, niin sitten asiakas ei pääse kirjautumaan. Hän pystyy palauttamaan uuden salasanan, mutta se vanhenee käytännössä samantien. Nykyisellään vanhentuneella kirjastokortilla pystyy kirjautumaan Finnaan.
> 
> 
> Eli ehkä ongelmia ei synny, jos pidetään huolta, että asiakkaiden kirjastokorttien voimassaoloaika ei pääse umpeutumaan. Toki on poikkeuksia, joissa voimassaoloaika on tarkoituksella lyhyt ja silloin todennäköisesti on ok, että jotkin asiat estyy.

Keskustelimme Vaskin pääkäyttäjien kesken vielä tästä. Meillä ajatuksena ei ole ollut automaattisesti jatkaa kirjastokorttien voimassaoloaikaa vaan saada asiakkaat ottamaan membership_expiry-viestin jälkeen yhteyttä kirjastoon ja päivittämään mahdolliset vanhat yhteystiedot samassa yhteydessä kun asiakkuuden voimassaoloaikaa jatketaan. Jos Finna-rajapintaan jossain vaiheessa lisätään tuki salasanan vanhenemiselle, tulee ainakin meillä olemaan varmasti ns. tavallisia henkilöasiakkaita joiden kirjautuminen verkkokirjastoon estyy ja jotka sitten ehkä yrittävät turhaan siinä vaiheessa vaihtaa salasanaansa. 🤔

**Comment by AnneliO** [comment]
Asiantuntijaryhmän päätös 29.4.2024:

Otetaan käyttöön virkailijatunnuksilla uusi salasanan vanhenemistoiminto niin, että salasanan vanhentumispäivä seuraa tunnuksen vanhentumispäivää. Triggeri hoitaa, että ne ovat samat ja että muutos koskee vain asiakastyyppiä VIRKAILIJA. Kaikissa kimpoissa asiakastyypin tunnus on sama.

**Comment by CodoDerDritte** [comment]
Triggerien uudet versiot:

```
DROP TRIGGER before_borrowers_insert;
DROP TRIGGER before_borrowers_update;

CREATE TRIGGER borrowers_insert_userid
    BEFORE INSERT
    ON borrowers FOR EACH ROW
    SET new.userid=new.cardnumber;

DELIMITER @@
CREATE TRIGGER borrowers_insert_password_expiration
   BEFORE INSERT
   ON borrowers 
      FOR EACH ROW
      BEGIN
         IF new.categorycode='VIRKAILIJA' THEN
            SET new.password_expiration_date=new.dateexpiry;
         END IF;
      END;
@@
DELIMITER ;

CREATE TRIGGER borrowers_update_userid
    BEFORE UPDATE
    ON borrowers FOR EACH ROW
    SET new.userid=new.cardnumber;

DELIMITER @@
CREATE TRIGGER borrowers_update_password_expiration
   BEFORE UPDATE
   ON borrowers 
      FOR EACH ROW
      BEGIN
         IF new.categorycode='VIRKAILIJA' THEN
            SET new.password_expiration_date=new.dateexpiry;
         END IF;
      END;
@@
DELIMITER ;

UPDATE borrowers SET password_expiration_date=dateexpiry WHERE categorycode='VIRKAILIJA';

**Comment by CodoDerDritte** [comment]
Triggerien uudet versiot, jotka määrittävät salasanan vanhentumispäivän ainoastaan virkailijatunnuksille.

```
DROP TRIGGER before_borrowers_insert;
DROP TRIGGER before_borrowers_update;

DELIMITER @@
CREATE TRIGGER before_borrowers_insert
   BEFORE INSERT
   ON borrowers 
      FOR EACH ROW
      BEGIN
         SET new.userid=new.cardnumber;
         IF new.categorycode='VIRKAILIJA' THEN
            SET new.password_expiration_date=new.dateexpiry;
         END IF;
      END;
@@
DELIMITER ;

DELIMITER @@
CREATE TRIGGER before_borrowers_update
   BEFORE UPDATE
   ON borrowers 
      FOR EACH ROW
      BEGIN
         SET new.userid=new.cardnumber;
         IF new.categorycode='VIRKAILIJA' THEN
            SET new.password_expiration_date=new.dateexpiry;
         END IF;
      END;
@@
DELIMITER ;

UPDATE borrowers SET password_expiration_date=dateexpiry WHERE categorycode='VIRKAILIJA';

**Comment by pknuuti** [comment]
Onko tämä otettu versionvaihdossa käyttöön?

**Comment by AnneliO** [comment]
On otettu. Salasanan vanhenemispäivä noudattaa nyt VIRKAILIJA-asiakastyypeillä tilin vanhentumispäivää.
