### ISSUE TITLE
Siilinjärvi: asiakkaan rajoitus ei poistu, vaikka laina on palautettu

### ISSUE THREAD

**Issue by ReettaSiili** [KohaSuomi/Koha-23x#99]
### Mikä vikana?

Onko tämä bugi vai Kohan ominaisuus? Vai onko nyt joku asetus pielessä?
Siilinjärvellä myöhästymisilmoitukset ovat 7 vrk ja 28 vrk eräpäivästä, jälkimmäinen aiheuttaa rajoitteen.
Asiakas id 40517 oli saanut ihan oikein 2. myöhästymisilmoituksen 9.11. ja samalla rajoitteen. Hän oli palauttanut kirjan 15.11. mutta rajoite ei ole poistunut automaattisesti, vaikka niin pitäisi tapahtua. Ihmettelin asiaa, mutta johtuuko se nyt asetuksesta _AutoRemoveOverduesRestrictions_ jonka selitys on _Salli MYÖHÄSSÄ-rajoitusten poistua automaattisesti lähetetystä myöhästymismuistutuksesta, kun asiakas palauttaa kaikki myöhässä olevat niteet_. Asiakkaalla on nimittäin 2 muuta lainaa eräpäivällä 9.11. ja niistä lähti 1. muistutus tänään.

### Mitä pitäisi tapahtua

Loogisempaa olisi että kun rajoitteen aiheuttanut laina palautetaan, rajoite poistuisi, riippumatta muista lainoista.

**Comment by AnneliO** [comment]
Tämä tuntuisi tosiaan olevan enemminkin ominaisuus. Testailin tätä joskus joku vuos sitten. Rajoite poistuu vasta sitten, kun KAIKKI myöhässä olevat lainat palautetaan/uusitaan. Rajoite ei ole kytketty mihinkään tiettyihin niteisiin, joten sitä ei voida poistaa tiettyjen niteiden palautuessa.

**Comment by ReettaSiili** [comment]
Kiitos Anneli kommenteista! Suljen tämän.

**Comment by AnneliO** [comment]
Versiossa 23.11 näyttäis tulleen AutoRemoveOverduesRestrictions-järjestelmäasetukseen uusi vaihtoehto "if patron has no remaining items that is cause for debarment". 

Kuvauksessa lukee näin:  The difference between removing restriction when no remaining overdue items exists and doing so only when any of the items would result in debarment is that the latter option will respect possible grace periods of overdue rules also on returns and not only when generating overdue notices.

Tuota kannattanee ainakin testata sitten nextillä, kun ne saadaan pystyyn. Avaan tiketin ja siirrän sen 23.xx-tietovarantoon testattavaksi.

**Comment by sksandel** [comment]
Vaskin Nextillä poistuu rajoitus, jos kaikki laskutetut niteet palautetaan. Testasin siten, että etsin asiakkaan, jolla laskutettuja niteitä. Asiakkaalla oli kaikki lainassa olevat laskutettuja, joten lainasin uuden niteen ohittamalla rajoituksen. Sen jälkeen palautin kaikki laskutetut niteet. Rajoitus poistui. 

Vaski-testillä rajoitus ei poistunut vaikka palautti kaikki laskutetut. 

Testatut asiakkaat Next: ID 486 ja Testi: ID 34681

**Comment by ReettaSiili** [comment]
Vaihdoin Siilin nextille AutoRemoveOverduesRestrictions-asetukseen vaihtoehdon "if patron has no remaining items that is cause for debarment".

Palautin asiakkaan lainauskiellon aiheuttaneet lainat. Rajoite poistui, vaikka muu myöhässä ollut kirja jäi edelleen lainaan. Asetus toimii nähdäkseni toivotulla tavalla. Jätän sen nextille voimaan ja tarkistan vielä tuotannossa, että toimii oikein.

**Comment by AnneliO** [comment]
Suljen tämän tiketin. :)
